### ISSUE TITLE
TextEditor: Doesn't set modified flag immediately after save

### ISSUE THREAD

**Issue by timmot** [SerenityOS/serenity#8902] opened 2021-07-20 11:29 UTC
Reproduce:
1. Open TextEditor
2. Enter some text and save file
3. Without moving the cusor bar, enter more characters or digits. Note that the modified `(*)` and `...` does not appear in the title bar.
4. Close the window and reopen the file, note that all data entered after the save is lost.

**Comment by KianFitz** [comment] 2021-07-20 14:18
Gonna take a look at this now, but i'm still a bit of a beginner in this project. I will keep updates here to show continued interest ;)

**Comment by KianFitz** [comment] 2021-07-22 23:10
Still looking at this, kinda having a hard time trying to design a system where the document knows that it's been saved.

I put in a message in Discord with my understanding of the code, if someone would be able to give any pointers? I think I may have dived into a project a little bit beyond my level, so sorry to waste people's time.

https://discordapp.com/channels/830522505605283862/830526926569209917/867064431548563478

**Comment by Mandar12** [comment] 2021-07-23 13:49
- Open TextEditor and enter some text.
--> `UndoStack` is created with `InsertTextCommand`

- Save file.
--> `UndoStack` is not flushed / emptied. This can be by design, providing undo support even after save, as long as process is running (in memory).
--> Also no extra command is pushed on `UndoStack` to indicate file save action.

- Insert new character.
--> `UndoStack` has `InsertTextCommand` on top and will merge new change into existing command.
--> This will make `UndoStack::push` to not call `on_state_change()` which leads to, modified state not changing and title not being updated.

- This works only for insert. Removing text is a new command which can not be merged with InsertText and triggers `on_state_change`.

**Fix:**
Save action can be a new Command, 
or after save, UndoStack does not merge new Command with last Command.

**Closed** 2021-10-07 07:01 UTC
Labels: bug, good first issue
