### ISSUE TITLE
Browser/ProtocolServer: Download of file:// image crashes

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#5836] opened 2021-03-16 21:57 UTC
```
Browser(42): Web::EventHandler: Clicking on a link to file:///res/html/misc/gifsuite.html
Browser(42): FrameLoader::load: file:///res/html/misc/gifsuite.html
Browser(42): I believe this content has MIME type 'text/html', , encoding 'utf-8'
ProtocolServer(43): StartDownload: No protocol handler for URL: 'file:///res/html/misc/gifsuite_files/static_nontransparent.gif'
Browser(42): USERSPACE(42) ASSERTION FAILED: m_download
../../Userland/Applications/Browser/DownloadWidget.cpp:60

... snip ...

CrashDaemon(20): New coredump file: /tmp/coredump/Browser_42_1615931746
CrashDaemon(20): --- Backtrace for thread #0 (TID 42) ---
CrashDaemon(20): 0x5b72b188: [libsystem.so]  +0x8 (syscall.cpp:35)
CrashDaemon(20): 0x7dba8c56: [libc.so] __assertion_failed +0x106 (syscall.h:44)
CrashDaemon(20): 0xb064bac8: [/bin/Browser] Browser::DownloadWidget::DownloadWidget(AK::URL const&) +0x1638 (RefCounted.h:119)
CrashDaemon(20): 0xb065d2fb: [/bin/Browser] Browser::start_download(AK::URL const&) +0x16b (Atomic.h:167)
CrashDaemon(20): 0x767bf306: [libgui.so] GUI::Action::activate(Core::Object*) +0x106 (Atomic.h:266)
CrashDaemon(20): 0x768b41b8: [libgui.so] GUI::WindowServerConnection::handle(Messages::WindowClient::MenuItemActivated const&) +0x58 (WindowServerConnection.cpp:263)
CrashDaemon(20): 0x768b81d0: [libgui.so] .L5846 +0x20 (WindowClientEndpoint.h:2211)
CrashDaemon(20): 0x768b7cf8: [libgui.so] IPC::Connection<WindShell(26): Job entry 'Browser -s' deleted in 9148 ms
owClientEndpoint, WindowServerEndpoint>::handle_messages() +0xa8 (OwnPtr.h:191)
CrashDaemon(20): 0x768b7e04: [libgui.so] AK::Function<void ()>::CallableWrapper<IPC::Connection<WindowClientEndpoint, WindowServerEndpoint>::Connection(WindowClientEndpoint&, AK::NonnullRefPtr<Core::LocalSocket>)::{lambda()#2}>::call() const +0x64 (Atomic.h:266)
CrashDaemon(20): 0xbaab2be4: [libcore.so] Core::Object::dispatch_event(Core::Event&, Core::Object*) +0x64 (Object.h:104)
CrashDaemon(20): 0xbaa9bfd4: [libcore.so] Core::EventLoop::pump(Core::EventLoop::WaitMode) +0x3e4 (Atomic.h:266)
CrashDaemon(20): 0xbaa9c59b: [libcore.so] Core::EventLoop::exec() +0x4b (EventLoop.cpp:390)
CrashDaemon(20): 0x767c2015: [libgui.so] GUI::Application::exec() +0x25 (Application.cpp:121)
CrashDaemon(20): 0xb063ded5: [/bin/Browser] main +0xd25 (main.cpp:253)
CrashDaemon(20): 0xb063e205: [/bin/Browser] _start +0x45 (crt0_shared.cpp:60)
```

**Comment by bcoles** [comment] 2021-03-17 01:36
Dupe of #4767

**Closed by bcoles** 2021-03-17 01:36 UTC
Labels: bug
