### ISSUE TITLE
FileManager crashes when triggering context menu in list view

### ISSUE THREAD

**Issue by nico** [SerenityOS/serenity#2787] opened 2020-07-13 13:29 UTC
1. Switch to list view, e.g. by hitting Ctrl-L
2. Right-click anything

Expected: Context menu
Actual: Null-ptr deref:

```
[FileManager(39:39)]: CPU[0] NP(error) fault at invalid address V0x0000000c
[FileManager(39:39)]: Unrecoverable page fault, read from address V0x0000000c
[FileManager(39:39)]: Note: Address V0x0000000c looks like a possible nullptr dereference
[FileManager(39:39)]: CRASH: CPU #0 Page Fault. Ring 3.
[FileManager(39:39)]: exception code: 0004 (isr: 0000
[FileManager(39:39)]:   pc=001b:0804d1eb flags=0206
[FileManager(39:39)]:  stk=0023:019024f0
[FileManager(39:39)]:   ds=0023 es=0023 fs=0023 gs=002b
[FileManager(39:39)]: eax=00000000 ebx=019312b6 ecx=00000000 edx=01902580
[FileManager(39:39)]: ebp=01902528 esp=c4493fe8 esi=0190250c edi=019025f8
[FileManager(39:39)]: cr0=80010013 cr2=0000000c cr3=0277e000 cr4=00100ee4
[FileManager(39:39)]: code: 8b 40 0c 66 25 00 f0 66
[FileManager(39:39)]: 0x0804d1eb  AK::Function<void (GUI::AbstractView const&, GUI::ModelIndex const&, GUI::ContextMenuEvent const&)>::CallableWrapper<run_in_windowed_mode(AK::RefPtr<Core::ConfigFile>, AK::String)::{lambda(GUI::AbstractView const&, GUI::ModelIndex const&, GUI::ContextMenuEvent const&)#32}>::call(GUI::AbstractView const&, GUI::ModelIndex const&, GUI::ContextMenuEvent const&) const +67

[FileManager(39:39)]: 0xc01656a6  Kernel::Process::crash(int, unsigned int, bool) +1010
[FileManager(39:39)]: 0xc0120937  illegal_instruction_handler +0
[FileManager(39:39)]: 0xc0121f42  page_fault_handler +945
[FileManager(39:39)]: 0xc011e1cf  page_fault_asm_entry +38
[FileManager(39:39)]: 0x0804af69  AK::Function<void (GUI::ModelIndex const&, GUI::ContextMenuEvent const&)>::CallableWrapper<DirectoryView::DirectoryView()::{lambda(auto:1&, auto:2&)#11}>::call(GUI::ModelIndex const&, GUI::ContextMenuEvent const&) const +63
[FileManager(39:39)]: 0x080574da  GUI::AbstractTableView::context_menu_event(GUI::ContextMenuEvent&) +330
[FileManager(39:39)]: 0x0808e54c  GUI::Widget::handle_mousedown_event(GUI::MouseEvent&) +168
[FileManager(39:39)]: 0x080c8d36  Core::Object::dispatch_event(Core::Event&, Core::Object*) +74
[FileManager(39:39)]: 0x080939d8  GUI::Window::event(Core::Event&) +1070
[FileManager(39:39)]: 0x080c8d36  Core::Object::dispatch_event(Core::Event&, Core::Object*) +74
[FileManager(39:39)]: 0x080c2429  Core::EventLoop::pump(Core::EventLoop::WaitMode) +307
[FileManager(39:39)]: 0x080c25a7  Core::EventLoop::exec() +43
[FileManager(39:39)]: 0x08050b26  run_in_windowed_mode(AK::RefPtr<Core::ConfigFile>, AK::String) +9941
[FileManager(39:39)]: 0x08048d35  main +2346
[FileManager(39:39)]: 0x080495be  _start +94
```

**Comment by bugaevc** [comment] 2020-07-14 06:54
Dupe of https://github.com/SerenityOS/serenity/issues/1440

**Closed** 2020-07-15 11:43 UTC
