### ISSUE TITLE
SerenityOS freezes when tries to open .so files.

### ISSUE THREAD

**Issue by xeriab** [SerenityOS/serenity#6391] opened 2021-04-17 01:12 UTC
I was jumping around in `FileManager` and when I accidentally hit `enter` on an `.so` file the whole system froze and I had to kill it.

I guess there is no such way to handle such a thing so the system spat the following error and froze:

```
[FileManager(28:28)]: ASSERTION FAILED: m_total_range.contains(allocated_range)
[FileManager(28:28)]: ../../Kernel/VM/RangeAllocator.cpp:165 in AK::Optional<Kernel::Range> Kernel::RangeAllocator::allocate_specific(VirtualAddress, size_t)
[#0 FileManager(28:28)]: 0xc053a514  .L1166 +0x91c
[#0 FileManager(28:28)]: 0xc050054a  Kernel::VolatilePageRanges::remove(Kernel::VolatilePageRange const&, bool&) +0x3ea
[#0 FileManager(28:28)]: 0xc05168c5  Kernel::Region::handle_inode_fault(unsigned long, Kernel::ScopedSpinLock<Kernel::RecursiveSpinLock>&) +0x1ead
[#0 FileManager(28:28)]: 0xc03a402e  Kernel::make_userspace_stack_for_main_thread(Kernel::Region&, AK::Vector<AK::String, 0ul>, AK::Vector<AK::String, 0ul>, AK::Vector<ELF::AuxiliaryValue, 0ul>)::{lambda(AK::String const&)#3}::operator()(AK::String const&) const [clone .isra.0] +0x248
[#0 FileManager(28:28)]: 0xc03a5cf2  Kernel::get_required_load_range(Kernel::FileDescription&) +0x745
[#0 FileManager(28:28)]: 0xc03a81ad  Kernel::load_elf_object(AK::NonnullOwnPtr<Kernel::Space>, Kernel::FileDescription&, unsigned int, Kernel::ShouldAllocateTls) +0xf0
[#0 FileManager(28:28)]: 0xc03b167f  Kernel::Process::do_exec(AK::NonnullRefPtr<Kernel::FileDescription>, AK::Vector<AK::String, 0ul>, AK::Vector<AK::String, 0ul>, AK::RefPtr<Kernel::FileDescription, AK::RefPtrTraits<Kernel::FileDescription> >, Kernel::Thread*&, unsigned int&, elfhdr const&) +0x4e39
[#0 FileManager(28:28)]: 0xc03b328a  Kernel::Process::do_exec(AK::NonnullRefPtr<Kernel::FileDescription>, AK::Vector<AK::String, 0ul>, AK::Vector<AK::String, 0ul>, AK::RefPtr<Kernel::FileDescription, AK::RefPtrTraits<Kernel::FileDescription> >, Kernel::Thread*&, unsigned int&, elfhdr const&) +0x6a44
[#0 FileManager(28:28)]: 0xc038a2c7  memmove +0x9f
[#0 FileManager(28:28)]: 0xc0388381  user_atomic_load_relaxed(unsigned int volatile*) +0xfd
```

[A screenshot of the frozen system](https://imgur.com/a/mnfnamM)

**Comment by xeriab** [comment] 2021-04-17 02:06
I tried to solve the problem by editing `Kernel/Syscalls/execve.cpp` file and made the following small change:

```C++
    if (main_program_header.e_type == ET_DYN) {
        // If it's ET_DYN with no PT_INTERP, then it's a dynamic executable responsible
        // for its own relocation (i.e. it's /usr/lib/Loader.so)
        if (path != "/usr/lib/Loader.so") {
            dbgln("exec(={}): WARNING - Dynamic ELF executable without a PT_INTERP header, and isn't /usr/lib/Loader.so", path);
            return ENOEXEC;
        } else {
            dbgln("exec(={}): WARNING - Hold on, you cannot execute the loader!", path);
            return ENOEXEC;
        }
    }
```

So instead of returning a `nullptr` it will return `ENOEXEC`. and It seems the change fixed the freezing problem.

If it's okay I can make a PR for it.

**Comment by bcoles** [comment] 2021-04-17 05:49
Duplicate of #5583

**Closed by bcoles** 2021-04-17 05:49 UTC
Labels: duplicate
