### ISSUE TITLE
After renaming a file the folder structure shown in the sidebar collapses

### ISSUE THREAD

**Issue by DankDuck09** [SerenityOS/serenity#15442] opened 2022-10-02 19:17 UTC
After renaming a file for example ReadMe.md to ReadMe.txt the folder structure shown in the sidebar collapses this has been an issue since September 2020. Better shown in the attached video.
 
https://user-images.githubusercontent.com/88255212/193472077-2c0eb6e0-3cf1-47a6-8ba2-d6fce492aa2e.mp4

**Comment by linusg** [comment] 2022-10-02 22:17
Duplicate of #6903, #11759, and #14913.

**Closed by linusg** 2022-10-02 22:17 UTC
