### ISSUE TITLE
kernel crash on expanding "proc" in FileManager sidebar

### ISSUE THREAD

**Issue by nico** [SerenityOS/serenity#4925] opened 2021-01-12 16:22 UTC
1. `fm`
2. click left sidebar
3. arrow-left until one level below /
4. arrow-down until keyboard focus is on "proc"
5. arrow-right to expand it

expected: shows subdirs of /proc in left sidebar

actual:

[FileManager(28:28)]: ASSERTION FAILED: read_callback
../Kernel/FileSystem/ProcFS.cpp:1124 in Kernel::KResult Kernel::ProcFSInode::refresh_data(Kernel::FileDescription&) const
[FileManager(28:28)]: 0xc01193ae  __assertion_failed(char const*, char const*, unsigned int, char const*) +0xe2
[FileManager(28:28)]: 0xc014d050  Kernel::ProcFSInode::refresh_data(Kernel::FileDescription&) const +0xe4
[FileManager(28:28)]: 0xc014d1db  Kernel::ProcFSInode::attach(Kernel::FileDescription&) +0x31
[FileManager(28:28)]: 0xc014023b  Kernel::FileDescription::attach() +0x5f
[FileManager(28:28)]: 0xc0141a7c  Kernel::FileDescription::create(Kernel::Custody&) +0x2ac
[FileManager(28:28)]: 0xc015ac43  Kernel::VFS::open(AK::StringView, int, unsigned short, Kernel::Custody&, AK::Optional<Kernel::UidAndGid>) +0xacb
[FileManager(28:28)]: 0xc019839e  Kernel::Process::sys$open(AK::Userspace<Kernel::Syscall::SC_open_params const*>) +0x462
[FileManager(28:28)]: 0xc01880fa  syscall_handler +0x6be
[FileManager(28:28)]: 0xc0187a34  syscall_asm_entry +0x31

**Comment by tomuta** [comment] 2021-01-12 16:33
Closing as a duplicate of #4830

**Closed by tomuta** 2021-01-12 16:33 UTC
