### ISSUE TITLE
LibJS: Crash on (0x80000000).toString(16)

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#5123] opened 2021-01-26 11:18 UTC
Oops:

```
$ Meta/Lagom/js 
> (0x80000000).toString(16)
Segmentation fault (core dumped)
```

**Comment by linusg** [comment] 2021-01-26 11:24
Duplicate of #3931 (note that the radix doesn't matter).

**Closed by linusg** 2021-01-26 11:24 UTC
Labels: bug
