### ISSUE TITLE
wget errors because we don't implement `clock_getres()`

### ISSUE THREAD

**Issue by erkinalp** [SerenityOS/serenity#13605] opened 2022-04-10 18:05 UTC
"Cannot get realtime clock frequency! No such syscall!"
virtual machine: QEMU 6.2 invoked by build script
actual machine: AMD Ryzen 9 5950X

**Comment by kleinesfilmroellchen** [comment] 2022-04-10 18:07
Could you please elaborate and provide reproduction info?

**Comment by erkinalp** [comment] 2022-04-10 18:11
step 1: invoke wget from terminal (even invoking with help spits out the same error in the first line)

**Comment by kleinesfilmroellchen** [comment] 2022-04-10 18:16
So this is not a bug as it doesn't prevent wget from working, though it would be nice if that didn't happen.

**Comment by erkinalp** [comment] 2022-04-10 18:17
It is a bug as it prevents the download speed from being calculated.

**Comment by timschumi** [comment] 2022-04-10 18:46
I remember fixing the download rate some time ago. Your test file is probably just too small for it to successfully calculate the speed.

**Comment by bgianfo** [comment] 2022-04-10 19:59
> I remember fixing the download rate some time ago. Your test file is probably just too small for it to successfully calculate the speed.

Yea, I get the same result when I run `wget www.example.com` on my host system.

**Comment by bgianfo** [comment] 2022-04-10 20:04
The bug here is that we only have a stub for `clock_getres()` in our LibC, it's not actually implemented. wget uses `clock_getres()` to detect if the OS supports a REALTIME clock. 


See: https://github.com/mirror/wget/blob/aab539bb44b5d7aeb093014c21fd4f4e4e728136/src/ptimer.c#L114-L164

The fix would be to actually implement `clock_getres()`.

**Comment by tcl3** [comment] 2024-01-15 22:18
I can no longer replicate this issue by running `wget www.example.com`.

Closing, as this appears to have been fixed by #14682.

**Closed by tcl3** 2024-01-15 22:18 UTC
Labels: bug, posix, ports
