### ISSUE TITLE
Kernel panic (I think) when changing screen resolution

### ISSUE THREAD

**Issue by Matrix2048** [SerenityOS/serenity#13007] opened 2022-03-11 22:52 UTC
I went to change the screen resolution for my monitor and got this...
![image](https://user-images.githubusercontent.com/83271285/157984164-f62b0cf2-01f3-4678-a35d-c93b300e322e.png)

**Comment by Matrix2048** [comment] 2022-03-11 22:53
Here's what the output has shown...
![image](https://user-images.githubusercontent.com/83271285/157985246-75f665eb-64cf-454f-8036-9dd57fb02c92.png)

**Comment by archanox** [comment] 2022-03-12 03:09
Duplicate of https://github.com/SerenityOS/serenity/issues/12970

**Closed** 2022-03-12 03:11 UTC
