### ISSUE TITLE
WindowServer+DisplaySettings: Settings background color does not work

### ISSUE THREAD

**Issue by MaxWipfli** [SerenityOS/serenity#7490] opened 2021-05-26 21:10 UTC
When setting a background color in the DisplaySettings app, it does not get applied and saved. Rather, the default color (`#505050ff`) continues to be stored in `/etc/WindowServer.ini`. This is probably related to #7488.

**Comment by linusg** [comment] 2021-05-26 21:14
Duplicate of #7382 _and_ #7469.

**Closed by linusg** 2021-05-26 21:14 UTC
