### ISSUE TITLE
TextEditor: Count of selected chars/words is zero if selection starts/end in an empty line

### ISSUE THREAD

**Issue by TobyAsE** [SerenityOS/serenity#6433] opened 2021-04-17 22:46 UTC
Pretty much what the title says.
When I select some text in te, if the selection starts or ends in an empty line, the count is set to 0, which is obviously wrong.

Selection starts in line 2
![image](https://user-images.githubusercontent.com/6002167/115128633-59ea9000-9fdf-11eb-9865-05251619bec9.png)
Selection ends in line 6
![image](https://user-images.githubusercontent.com/6002167/115128643-6838ac00-9fdf-11eb-9e80-ffcfb6ec6ab4.png)

**Comment by TobyAsE** [comment] 2021-04-17 22:46
Haven't you been working on this @ry-sev ?

**Comment by ry-sev** [comment] 2021-04-17 23:02
I will attempt to address this bug in my draft PR for HackStudio+TextEditor: https://github.com/SerenityOS/serenity/pull/6363/commits

**Comment by ry-sev** [comment] 2021-04-18 02:47
So the issue here is in TextDocument::text_in_range, specifically the condition line(range.start().line()).is_empty() in the first if-statement. I tried removing this check but, as expected, it crashes other applications. My PR mentioned earlier unfortunately does not fix this issue; i'm not sure how to go about fixing it.

**Comment by Granddave** [comment] 2021-04-18 13:08
Seems like this issue describes the same (or very similar) behavior as #6015.

**Comment by linusg** [comment] 2021-04-18 13:09
Duplicate of #6015.

**Closed by linusg** 2021-04-18 13:09 UTC
Labels: bug
