### ISSUE TITLE
ProcFS: race condition in procfs$all

### ISSUE THREAD

**Issue by DrewStratford** [SerenityOS/serenity#1267] opened 2020-02-21 14:07 UTC
**Steps to reproduce:**
1. Open two System monitors and set each's frequency to 0.25
2. Run the program below with an argument of 200.
```cpp
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

void foo(int id){
	sleep(2);
	printf("hi %d\n", id);
}
int main(int argc, char** argv){
	if(argc < 2)
		return 0;

	int target = atoi(argv[1]);
	printf("target %d\n", target);
	for (int i = 0; i < target; i++) {
		if(fork() == 0){
			foo(i);
			return 0;
		}
	}

	return 0;
}
```

**What should happen:**
The program will run for a bit before one of the SystemMonitors crash. The crash is not guranteed so you may have to repeat step 2 multiple times.
The crash log should be similar to this:
```
reaped unparented process many(142), exit status: 17
reaped unparented process many(141), exit status: 17
[SystemMonitor(22:22)]: SystemMonitor(22) Couldn't find user region for V0xaaaaaece
NP(error) fault at invalid address V0xaaaaaece
SystemMonitor(22:22) Unrecoverable page fault, read from address 0xaaaaaece
Note: Address 0xaaaaaece looks like it may be recently kfree()'d memory
CRASH: Page Fault. Process: SystemMonitor(22)
exception code: 0000 (isr: 0000)
  pc=0008:c012a905 flags=0086
 stk=0000:c01bb218
  ds=0010 es=0010 fs=0023 gs=07d3
eax=00000000 ebx=c010d010 ecx=00000000 edx=aaaaaaaa
ebp=c38f6cec esp=c01bb218 esi=c38f6cc8 edi=c38f6cbc
cr0=8001001b cr2=aaaaaece cr3=01fb6000 cr4=00100ee4
0xc012a905  Kernel::procfs$all(Kernel::InodeIdentifier)::{lambda(Kernel::Process const&)#1}::operator()(Kernel::Process const&) const [clone .isra.0] +1149
0xc0144e05  Kernel::Process::crash(int, unsigned int) +383
0xc01175f6  illegal_instruction_handler +0
0xc011787d  page_fault_handler +524
0xc0116568  page_fault_asm_entry +22
0xc012ae12  Kernel::procfs$all(Kernel::InodeIdentifier) +148
0xc0176cbc  AK::Function<AK::Optional<Kernel::KBuffer> (Kernel::InodeIdentifier)>::CallableWrapper<AK::Optional<Kernel::KBuffer> (*)(Kernel::InodeIdentifier)>::call(Kernel::InodeIdentifier) const +22
0xc017738c  AK::Function<AK::Optional<Kernel::KBuffer> (Kernel::InodeIdentifier)>::operator()(Kernel::InodeIdentifier) const +68
0xc012bb0f  Kernel::ProcFSInode::read_bytes(int, int, unsigned char*, Kernel::FileDescription*) const +493
0xc0126b99  Kernel::InodeFile::read(Kernel::FileDescription&, unsigned char*, int) +53
0xc0124982  Kernel::FileDescription::read(unsigned char*, int) +86
0xc014af0c  Kernel::Process::sys$read(int, unsigned char*, int) +542
0xc01584c6  syscall_handler +865
0xc015811f  syscall_asm_entry +28
0x0809a33e  Core::IODevice::read_all() +158
0x080a3bd9  Core::ProcessStatisticsReader::get_all() +185
0x0804aa31  ProcessModel::update() +49
0x08051df6  AK::Function<void ()>::CallableWrapper<main::{lambda()#1}>::call() const +32
0x0809ce6a  Core::Object::dispatch_event(Core::Event&, Core::Object*) +86
0x0809edda  Core::EventLoop::pump(Core::EventLoop::WaitMode) +462
0x0809ef8d  Core::EventLoop::exec() +71
0x0805ada9  GUI::Application::exec() +29
0x08049665  main +4761
0x08049f13  _start +94
```

**What's happening**
The SystemMonitors are constantly calling `procfs$all` which needs to atomically inspect a list of processes; to acomplish this it uses an `InterruptDisabler`. However, some of the JSON serializer code causes a page fault, meaning we can end up here:
https://github.com/SerenityOS/serenity/blob/1d2986ea15eab8ea8b8855147a16de7662729f31/Kernel/VM/Region.cpp#L376-L383
Either the `sti()` or the lock may swap to another thread and since, at this time, many processes are being reaped a process in `procfs$all`'s list may be freed.

**Comment by bugaevc** [comment] 2020-02-21 14:36
> What should happen: The program will run for a bit before one of the SystemMonitors crash.

:thinking:

**Comment by bugaevc** [comment] 2020-06-01 16:21
> Either the sti() or the lock may swap to another thread and since, at this time, many processes are being reaped a process in procfs$all's list may be freed.

I wonder if there could be some mechanism to say, while interrupts are disabled:
* if the lock is not locked, just give it to me,
* if it's locked, jump to whoever's holding it, with interrupts still disabled, and jump back as soon as they release the lock, giving the lock to me.

Here, it would give us the guarantee that some other thread may run, but it will be purely doing memory management, not reaping other processes.

**Comment by DrewStratford** [comment] 2020-06-03 04:09
> if it's locked, jump to whoever's holding it, with interrupts still disabled, and jump back as soon as they release the lock, giving the lock to me.

The problem with this is that we can't really ensure that the thread will keep interrupts disabled till it releases the lock. Alternatively, it may rely on interrupts being enabled in some way. For example: it may be about to take another lock, or it could be a device driver waiting for an interrupt.

I think that the problem with the `procfs$all` code is that we are using an `InterruptDisabler` when really, we only want some form of mutual exclusion. Alternatively, we could allow interrupts and instead use a lock for each process, to ensure that it isn't freed while being inspected.

**Comment by bugaevc** [comment] 2020-06-03 06:18
> The problem with this is that we can't really ensure that the thread will keep interrupts disabled till it releases the lock.

True :(

> I think that the problem with the `procfs$all` code

But the problem, as you've demonstrated, is not with that code, it's that any code that disabled interrupts can get them suddenly (and silently) temporary enabled on page faults, breaking its assumptions.

**Comment by kleinesfilmroellchen** [comment] 2022-12-12 20:36
Closing because I can't reproduce this.

**Closed by kleinesfilmroellchen** 2022-12-12 20:36 UTC
Labels: bug
