### ISSUE TITLE
TextEditor: Open file crash

### ISSUE THREAD

**Issue by zBl4ckUser** [SerenityOS/serenity#5828] opened 2021-03-16 17:40 UTC
The TextEditor crash when i try to open coredump files
 
Reproduction steps:
>Open /tmp/coredump
>Open any file with TextEditor

 Log:
```
CrashDaemon(20): 0x0e295188: [libsystem.so]  +0x8 (syscall.cpp:35)
CrashDaemon(20): 0x582b5c56: [libc.so] __assertion_failed +0x106 (syscall.h:44)
CrashDaemon(20): 0x58306e23: [libc.so] AK::Utf8CodepointIterator::operator*() const +0x113 (Utf8View.cpp:200)
CrashDaemon(20): 0x4051893d: [libgui.so] GUI::TextDocumentLine::set_text(GUI::TextDocument&, AK::StringView const&) +0x15d (Vector.h:176)
CrashDaemon(20): 0x40518aee: [libgui.so] GUI::TextDocument::set_text(AK::StringView const&) +0xee (TextDocument.cpp:72)
CrashDaemon(20): 0x40522616: [libgui.so] GUI::TextEditor::set_text(AK::StringView const&) +0x56 (TextEditor.cpp:127)
CrashDaemon(20): 0x14d9b46b: [/bin/TextEditor] TextEditorWidget::open_file(AK::String const&) +0xeb (TextEditorWidget.cpp:594)
CrashDaemon(20): 0x14d8d336: [/bin/TextEditor] main +0x396 (main.cpp:93)
CrashDaemon(20): 0x14d8d735: [/bin/TextEditor] _start +0x45 (crt0_shared.cpp:60)
```

**Comment by linusg** [comment] 2021-03-16 17:50
Duplicate of #4700

**Comment by drunderscore** [comment] 2021-03-16 17:51
Yes, the `Utf8View` does not gracefully handle binary files.

**Closed by linusg** 2021-03-16 17:50 UTC
