### ISSUE TITLE
Kernel Crash% candidates

### ISSUE THREAD

**Issue by BenWiederhake** [SerenityOS/serenity#10722] opened 2021-10-31 12:13 UTC
### @bcoles 
```
cat /dev/random>/dev/audio
```

### @Agni
```
su
cat /dev/mem
```
### Mine:
```
su
mount /dev/fb0 /mnt
```

**Comment by bcoles** [comment] 2021-10-31 14:40
An old system freeze bug #1858 (now patched):

```
su
rmdir /
```

**Comment by supercomputer7** [comment] 2021-10-31 18:09
Even though you say all of the below crashes, I have couple of notes:
> ### @bcoles
> 
> ```
> cat /dev/random>/dev/audio
> ```
> 

It's completely valid to push random data to the audio device... even if you want to prevent it, how do you do that?
You might want to set the audio device to be able to be opened one time and only that... still a bad idea imho.
> ### @agni
> 
> ```
> su
> cat /dev/mem
> ```
> 

It's also completely valid to read the entire memory device, the Kernel should restrict the userland from reading restricted physical memory areas.
> ### Mine:
> 
> ```
> su
> mount /dev/fb0 /mnt
> ```

Does it even work? there's no ext2 filesystem on it, so how could you proceed further?

**Comment by BenWiederhake** [comment] 2021-10-31 18:20
I'm not talking about what exactly the Kernel should do or how it should handle it. I'm just saying that it probably shouldn't crash :P

I agree that random audio and linearly reading memory should be a bog-standard usecase. I agree that mounting /dev/fb0 should probably fail in some non-crashing way.

**Comment by bcoles** [comment] 2021-11-01 08:28
> It's completely valid to push random data to the audio device... even if you want to prevent it, how do you do that?

The issue (#4557) is with the length of the data rather than the data contents. The kernel crashes due to a failed assertion if the data is larger than `PAGE_SIZE` (4096).

**Comment by supercomputer7** [comment] 2022-02-09 16:51
It seems like none of this kernel crashes are reproducible anymore, so closing this now.
Feel free to open this if I'm wrong about this (I'd be happy to check how to test this correctly if I haven't done it right).

**Closed by supercomputer7** 2022-02-09 16:51 UTC
Labels: bug

**Comment by supercomputer7** [comment] 2022-02-11 20:05
Well, it seems like the SB16 driver is broken after I tested the same command with #12445.
We will need to open a new issue, or to fix this in the very near future :)

**Comment by supercomputer7** [comment] 2022-02-11 20:32
The fourth commit in #12445 fixes the problem with SB16.
