### ISSUE TITLE
LibJS: Object prototype functions do not have the correct Function prototype

### ISSUE THREAD

**Issue by mattco98** [SerenityOS/serenity#2546] opened 2020-06-11 21:44 UTC
![photo](https://i.imgur.com/8tDaAKR.png)

I suspect this has something to do with the fact that the function and object prototypes are special-cased in `GlobalObject.initialize`, but I played around with it for a while and couldn't come up with a fix.

**Comment by linusg** [comment] 2020-09-12 16:09
This has been fixed - I don't know when (and can't be bothered looking through git history right now), but it works as intended:

```js
> Object.getPrototypeOf(Object.prototype.toString) === Function.prototype
true
```

cc @awesomekling to close the issue :)

**Closed** 2020-09-12 16:15 UTC
