### ISSUE TITLE
.run Crashes Terminal

### ISSUE THREAD

**Issue by CalebOtto** [SerenityOS/serenity#700] opened 2019-10-30 14:16 UTC
I decided to repull the project (from scratch, removing the old folder). Completed the build process with no errors. Upon running .run the terminal crashes and re-starting .run I get, "i686-pc-serenity-g++: not found"

I've had this error before and reusing"BuildIt and source UseIt" fixed the issue, however, that is no longer the case. I have retried the entire process 3 times and have even re-pulled the project fresh.

I'm using a VM with Lubuntu, on Windows 10. It worked previously with no issues, only with the newest commit it seems.

**Comment by awesomekling** [comment] 2019-11-01 20:45
"i686-pc-serenity-g++: not found"

This error means you have either not sourced UseIt.sh, or your toolchain is missing somehow.

**Comment by CalebOtto** [comment] 2019-11-02 01:55
I've tried the entire process multiple times, even deleting and repulling the project. It gets to .run without any errors, then crashes the terminal and trying .run again throws the error mentioned as if it was deleted when trying to run it.

Last time I had that error, I used BuildIt and source UseIt and it fixed the issue, this time it just doesn't run.

**Comment by CalebOtto** [comment] 2019-11-02 01:57
This is what I get when .run does work:
![image](https://user-images.githubusercontent.com/43943268/68064492-f9727f00-fd67-11e9-8177-949807017d78.png)

**Comment by awesomekling** [comment] 2019-11-04 11:58
Hm, I have no idea what that is. Based on the very last screenshot, it looks like your host machine's `/bin/sh` is having trouble interpreting the `run` script.

I'm not familiar with Lubuntu, so you'll have to debug this yourself.

**Comment by Pulgovisk** [comment] 2019-11-04 13:29
What is your user default shell?
$ echo $SHELL

**Comment by CalebOtto** [comment] 2019-11-04 13:46
> What is your user default shell?
> 
> ```shell
> $ echo $SHELL
> ```

/bin/bash is my default

**Comment by xeons** [comment] 2019-11-08 23:07
Is this a fresh VM? I have the latest Lubuntu on one of my machines at home, I may be able to look.

**Comment by xeons** [comment] 2019-11-09 01:47
I'm not able to reproduce the problem on Lubuntu 19.04

**Comment by awesomekling** [comment] 2020-01-26 17:43
Closing old build-related issues since we have a build bot and several people building the system many times per day.

**Closed by awesomekling** 2020-01-26 17:43 UTC
