### ISSUE TITLE
`rm -rf /` should produce a warning 

### ISSUE THREAD

**Issue by jpshokar** [SerenityOS/serenity#11270] opened 2021-12-15 14:59 UTC
`rm -rf /` is a dangerous command that has the potential to completely brick your serenity installation. 

There should be a way to alert the user of the consequences that it has.

Using the GNU coreutils version of this command this contains the following warning:
```
rm: it is dangerous to operate recursively on '/'
rm: use --no-preserve-root to override this failsafe
```

**Comment by linusg** [comment] 2021-12-15 15:01
Duplicate of #5253.

**Closed by linusg** 2021-12-15 15:01 UTC
