### ISSUE TITLE
OOM crash with /proc/$(pidof cv)/vm

### ISSUE THREAD

**Issue by bugaevc** [SerenityOS/serenity#410] opened 2019-08-05 16:32 UTC
To reproduce, start `cv` and run `cat /proc/$(pidof cv)/vm` (the Shell doesn't yet support `$()` substitutions, so perform it in your head :wink:).

The kernel OOM's at trying to kmallocate a ridiculously large byte buffer to serialize the JSON array of regions. There are 366 regions in the array, which also seems excessively high.

**Comment by awesomekling** [comment] 2019-08-05 17:05
Oh yeah, the ProcFS code still serializes into a temporary `ByteBuffer` and then copies it to a `KBuffer`. We need a way to go directly to a `KBuffer` to avoid flooding the kernel heap.

**Comment by awesomekling** [comment] 2019-08-05 17:11
I'm guessing the 366 regions are `malloc()` "big allocations" (anything above 4096 bytes just gets forwarded to `mmap()`.)
We probably want to improve that situation in `malloc()` but the kernel should also absolutely be able to handle a few hundred memory regions in a process :)

**Comment by bugaevc** [comment] 2019-08-06 17:57
I believe part of the reason for kmalloc OOM is that the kernel seems to regularly leak memory now, so by the time we get to the offending JSON serialization, most of the kmalloc pool is already exhausted.

To reproduce the leak, run a command (I used `cat`) repeatedly and observe `kmalloc`/`kfree` call counts in the ProcessManager. To reproduce kmalloc pool exhaustion, just run `allocate` and observe the immediate OOM — this definitely used to work.

Are there any ways or instruments to debug issues like these? I wish I could use Valgrind the way I can use GDB :(

**Comment by awesomekling** [comment] 2019-08-06 18:08
I don't know of any external instruments you can attach for this, no :(
On the bright side, we control the whole stack here, so we can build any instrument we like :)

**Comment by awesomekling** [comment] 2019-08-06 18:12
I see 2 leaks for each `cat` command that I spawn (and exit.) That's bad and we should definitely track down what they are, but I doubt they are the cause of OOMing.
I can't reproduce OOM with `allocate` on current master. Are you running anything else at the same time?

**Comment by bugaevc** [comment] 2019-08-07 09:20
> I can't reproduce OOM with `allocate` on current master. Are you running anything else at the same time?

No, just `allocate` in the default Terminal on the vanilla master. Weird.

**Comment by bugaevc** [comment] 2019-08-07 10:51
Okay, this is *really* weird, after some number of rebuilds it went away; now I also get two leaks per `cat`, `allocate` works and `cat /proc/$(pidof vm)/vm` doesn't OOM, still on the very same master checkout.

But it's not an error on my side, the issue was clearly there just a short while ago, it's just that I cannot reproduce it anymore/ATM.

**Comment by awesomekling** [comment] 2019-08-07 20:07
The issue with `/proc/$(pidof vm)/vm` has been fixed with 37ba2a7b658d1fff5b2d79d8cb689de7d4392c87 :)

There are definitely more memory issues, but we can open separate bugs about them as we go.
Thanks for reporting this!

**Closed by awesomekling** 2019-08-07 20:07 UTC
