### ISSUE TITLE
POSIX threads support

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#738] opened 2019-11-05 19:20 UTC
I recently ported nesalizer to serenity but we can't run it yet because SDL needs to be built with pthread support enabled, which we can't do until the serenity kernel gains support for the pthreads API. I've looked at porting a few other emus but most require pthreads support.

**Comment by awesomekling** [comment] 2019-11-05 21:08
Dupe of #223 :)

**Closed by awesomekling** 2019-11-05 21:08 UTC

**Comment by danboid** [comment] 2019-11-05 22:22
Ooops!

Sorry AK!
