### ISSUE TITLE
Opening ChanViewer Immediately Results in an Assertion Failure

### ISSUE THREAD

**Issue by JonArcherII** [SerenityOS/serenity#958] opened 2019-12-29 22:27 UTC
Seems to happen in the JSON parser.

```
USERSPACE(19) ASSERTION FAILED: consumed_ch == expected_ch
../../AK/JsonParser.cpp:41 in void AK::JsonParser::consume_specific(char)
```

Full log:
```
Process: New process PID=19 with name=WindowServer
Thread{0x0043e488}: New thread TID=19 in WindowServer(19)
Allocated ring0 stack @ 0xc2888000 - 0xc2898000
WindowServer(19) do_exec(/bin/ChanViewer): thread_count() = 1
VFS::create: 'rpc.19' in 4:1
sys$fcntl: fd=6, cmd=3, arg=0
sys$fcntl: fd=6, cmd=4, arg=2048
SystemServer(4): Ready to read on behalf of LookupServer
SystemServer(4): Spawning LookupServer
Process: New process PID=20 with name=SystemServer
Thread{0x00452828}: New thread TID=20 in SystemServer(20)
Allocated ring0 stack @ 0xc28aa000 - 0xc28ba000
SystemServer(20) do_exec(/bin/LookupServer): thread_count() = 1
VFS::create: 'rpc.20' in 4:1
LookupServer(20): Using network config file at /etc/LookupServer.ini
LookupServer(20): Loading hosts from /etc/hosts
LookupServer(20): Taking the socket over from SystemServer
sys$fcntl: fd=3, cmd=2, arg=1
LookupServer(20): Got request for 'a.4cdn.org' (using IP 1.1.1.1)
ARP table (1 entries):
52:55:0a:00:02:02 :: 10.0.2.2
sending as udp packet from 10.0.2.15:38799 to 1.1.1.1:53!
Got response (ID: 1)
  Question count: 1
  Answer count: 5
 Authority count: 0
Additional count: 0
LookupServer:     Answer #0: (question: a.4cdn.org.), type=1, ttl=9, length=4, data=104.16.58.249
LookupServer:     Answer #1: (question: a.4cdn.org.), type=1, ttl=9, length=4, data=104.16.59.249
LookupServer:     Answer #2: (question: a.4cdn.org.), type=1, ttl=9, length=4, data=104.16.60.249
LookupServer:     Answer #3: (question: a.4cdn.org.), type=1, ttl=9, length=4, data=104.16.61.249
LookupServer:     Answer #4: (question: a.4cdn.org.), type=1, ttl=9, length=4, data=104.16.62.249
LookupServer(20): Got request for 'a.4cdn.org' (using IP 1.1.1.1)
WindowServer(12): [WM] WSWindow{0x01d42806} title set to "ChanViewer"
WindowServer(12): WindowServer: Sharing icon buffer 16 with PID 13
handle_tcp: unexpected flags in Closing state
handle_tcp: unexpected flags in Closed state
ChanViewer(19): CTCPSocket{0x01575be6} connection appears to have closed in receive().
ChanViewer(19): Board list download finished, success=true, response=0x0156da16
ChanViewer(19): Board list payload size: 34670
USERSPACE(19) ASSERTION FAILED: consumed_ch == expected_ch
../../AK/JsonParser.cpp:41 in void AK::JsonParser::consume_specific(char)
signal: ChanViewer(19) sent 6 to ChanViewer(19)
terminate_due_to_signal ChanViewer(19) <- 6
Mark PID 19 TID 19 for death
Finalizing 1 dying threads
Finalizing Thread 19 in ChanViewer(19)
0x0014617e  errno +1335674
0x0014a872  errno +1353838
0x001477f4  errno +1341424
0x001474d1  errno +1340621
0x080b2475  raise +22
0x080482fd  abort +13
0x080b23fd  kill +0
0x080a73c1  AK::JsonParser::consume_specific(char) +47
0x080a7a29  AK::JsonParser::parse_object() +121
0x080a7b86  AK::JsonParser::parse() +174
0x080a7c9b  AK::JsonParser::parse_array() +85
0x080a7b3b  AK::JsonParser::parse() +99
0x080a7a39  AK::JsonParser::parse_object() +137
0x080a7b86  AK::JsonParser::parse() +174
0x080a6d5f  AK::JsonValue::from_string(AK::StringView const&) +83
0x0804a41f  AK::Function<void (bool)>::CallableWrapper<BoardListModel::update()::{lambda(bool)#1}>::call(bool) const +219
0x0808d69d  CNetworkJob::did_finish(AK::NonnullRefPtr<CNetworkResponse>&&) +125
0x0808c4a4  AK::Function<void (CObject&)>::CallableWrapper<CHttpJob::finish_up()::{lambda(auto:1&)#1}>::call(CObject&) const +48
0x0808f72c  CEventLoop::pump(CEventLoop::WaitMode) +464
0x0808f911  CEventLoop::exec() +71
0x0804f06b  GApplication::exec() +29
0x08048787  main +990
0x08048e54  _start +94

~Thread{0x0043e488}
Finalizing Process ChanViewer(19)
Connection: Client disconnected: 6
WindowServer(12): Done
reap: ChanViewer(19)
~Process{0x0043b9e8} name=ChanViewer pid=19, m_fds=0, m_thread_count=0
reaped unparented process ChanViewer(19), exit status: 6
Event type 3012 with no receiver :(
handle_tcp: No TCP socket for tuple 10.0.2.15:49434 -> 104.16.58.249:80
handle_tcp: source=104.16.58.249:80, destination=10.0.2.15:49434 seq_no=1344002, ack_no=51, flags=0010 (ACK ), window_size=8760, payload_size=1024
```

**Comment by awesomekling** [comment] 2019-12-29 22:35
cc @deoxxa 
Suspect this is the same as #948 
Looks like more TCP badness. Could it be out-of-order packets?

**Comment by awesomekling** [comment] 2020-01-26 14:54
Dupe of #948

**Closed by awesomekling** 2020-01-26 14:54 UTC
