### ISSUE TITLE
DisplaySettings: Changing background color not working sometimes

### ISSUE THREAD

**Issue by tomuta** [SerenityOS/serenity#7469] opened 2021-05-25 21:18 UTC
Steps to reproduce:
1. Right click on desktop, select "Display Settings"
2. Pick a new desktop color
3. Click Apply or OK, notice that the background color does not change

Also slightly weird was when I had a desktop wallpaper set, it wasn't quite obvious to me how to change back to a solid background color. Right now it requires you to deselect the wallpaper and pick a color, but the preview doesn't reflect this.

**Comment by linusg** [comment] 2021-05-25 21:45
Duplicate of #7382.

**Closed by linusg** 2021-05-25 21:45 UTC
Labels: bug
