### ISSUE TITLE
male focused language alienating non men 

### ISSUE THREAD

**Issue by lavenderdotpet** [SerenityOS/serenity#24649] opened 2024-07-02 20:09 UTC
https://github.com/SerenityOS/serenity/pull/24647

as someone who is not a man this indeed is pushing me away from this project 

as a gal who loves Unix like and Unix based operating systems having all the language around the project be male focus really tells us that 
you are not considering non men as part of your project or community 

especially when you respond like this by locking a thread that was hosting a discussion about it 

if you only want to cater to men alright 
i'll go elsewhere i'll know that i am not wanted here

but if you want to do as you say you want and not alienate people 
you are currently doing a pretty poor job at that right now

please please reconsider how you are handling this

**Comment by sylv256** [comment] 2024-07-02 20:54
As far as I'm aware, there wasn't any controversial or heated discussion, and I don't think that would arise from a PR specifically trying to avoid that. Preemptively deeming something "too political" or "too heated" is a petty way to shut down discussion and constructive criticism of real impactful issues with your project. I suggest the project managers reconsider their attitudes toward people making good-faith contributions like this.

**Comment by 0atman** [comment] 2024-07-02 20:54
Ah yes, of course, the two genders:
![image](https://github.com/SerenityOS/serenity/assets/114097/9f6ff7ab-a7d2-45ca-ae66-47e4b9ecfdd0)

Shame on you @gmta, it would have been so easy to allow language in #24647 that included women in this tiny way, but you chose not to, hiding behind cowardly weasel-words.

**Comment by BertalanD** [comment] 2024-07-02 20:56
The linked PR is on track to being merged after the commit message is amended to match our style.

**Comment by Shadlock0133** [comment] 2024-07-02 20:58
the situation certainly did alienate me :v

**Comment by SarcevicAntonio** [comment] 2024-07-02 21:06
I'm a man and also would like the option to use they them pronouns. Why is gender even an option just make it neutral. 😐

**Comment by lavenderdotpet** [comment] 2024-07-02 21:07
@0atman 
it is thankfully being fixed in this pull req

https://github.com/SerenityOS/serenity/pull/24648

just a shame that this had to be a conflict at all

**Comment by ADKaster** [comment] 2024-07-02 21:38
While it may look like the 24647 was preemptively closed for 'possible' controversy, it was created as a direct response to a heated mastodon discussion about a 3 year old, closed PR. That older PR was already being brigaded and hosting the start of a flame war before we locked it and 24647 around the same time. Its good-faith status is questionable at best.

As has been said, the second, linked PR tackles the root cause of the controversial language, and should be accepted once it is fixed up to match the contribution guidelines.

**Closed** 2024-07-02 22:17 UTC
