### ISSUE TITLE
Makefile:75: recipe for target error!

### ISSUE THREAD

**Issue by FerhatGec** [SerenityOS/serenity#325] opened 2019-07-17 12:26 UTC
raries/LibCore/CEventLoop.o
make: Leaving directory '/home/ferhatgec/Masaüstü/serenity-master/DevTools/FormCompiler'
Building ../Libraries/LibC
make: Entering directory '/home/ferhatgec/Masaüstü/serenity-master/Libraries/LibC'
CLEAN
make: Leaving directory '/home/ferhatgec/Masaüstü/serenity-master/Libraries/LibC'
make: Entering directory '/home/ferhatgec/Masaüstü/serenity-master/Libraries/LibC'
CXX ../../AK/StringImpl.cpp
CXX ../../AK/String.cpp
i686-pc-serenity-g++: invalid option -- 'M'
Usage: i686-pc-serenity-g++ [options] [mangled names]
Options are:
  [-_|--strip-underscore]     Ignore first leading underscore
  [-n|--no-strip-underscore]  Do not ignore a leading underscore (default)
  [-p|--no-params]            Do not display function arguments
  [-i|--no-verbose]           Do not show implementation details (if any)
  [-R|--recurse-limit]        Enable a limit on recursion whilst demangling.  [Default]
  ]-r|--no-recurse-limit]     Disable a limit on recursion whilst demangling
  [-t|--types]                Also attempt to demangle type encodings
  [-s|--format {none,auto,gnu-v3,java,gnat,dlang,rust}]
  [@<file>]                   Read extra options from <file>
  [-h|--help]                 Display this information
  [-v|--version]              Show the version information
Demangled names are displayed to stdout.
If a name cannot be demangled it is just echoed to stdout.
If no names are provided on the command line, stdin is read.
Makefile:75: recipe for target '../../AK/StringImpl.o' failed
make: *** [../../AK/StringImpl.o] Error 1
make: *** Bitmemiş işler için bekliyor....
i686-pc-serenity-g++: invalid option -- 'M'
Usage: i686-pc-serenity-g++ [options] [mangled names]
Options are:
  [-_|--strip-underscore]     Ignore first leading underscore
  [-n|--no-strip-underscore]  Do not ignore a leading underscore (default)
  [-p|--no-params]            Do not display function arguments
  [-i|--no-verbose]           Do not show implementation details (if any)
  [-R|--recurse-limit]        Enable a limit on recursion whilst demangling.  [Default]
  ]-r|--no-recurse-limit]     Disable a limit on recursion whilst demangling
  [-t|--types]                Also attempt to demangle type encodings
  [-s|--format {none,auto,gnu-v3,java,gnat,dlang,rust}]
  [@<file>]                   Read extra options from <file>
  [-h|--help]                 Display this information
  [-v|--version]              Show the version information
Demangled names are displayed to stdout.
If a name cannot be demangled it is just echoed to stdout.
If no names are provided on the command line, stdin is read.
CXX ../../AK/StringBuilder.cpp
Makefile:75: recipe for target '../../AK/String.o' failed
make: *** [../../AK/String.o] Error 1
CXX ../../AK/StringView.cpp
i686-pc-serenity-g++: invalid option -- 'M'
Usage: i686-pc-serenity-g++ [options] [mangled names]
Options are:
  [-_|--strip-underscore]     Ignore first leading underscore
  [-n|--no-strip-underscore]  Do not ignore a leading underscore (default)
  [-p|--no-params]            Do not display function arguments
  [-i|--no-verbose]           Do not show implementation details (if any)
  [-R|--recurse-limit]        Enable a limit on recursion whilst demangling.  [Default]
  ]-r|--no-recurse-limit]     Disable a limit on recursion whilst demangling
  [-t|--types]                Also attempt to demangle type encodings
  [-s|--format {none,auto,gnu-v3,java,gnat,dlang,rust}]
  [@<file>]                   Read extra options from <file>
  [-h|--help]                 Display this information
  [-v|--version]              Show the version information
Demangled names are displayed to stdout.
If a name cannot be demangled it is just echoed to stdout.
If no names are provided on the command line, stdin is read.
i686-pc-serenity-g++: invalid option -- 'M'
Usage: i686-pc-serenity-g++ [options] [mangled names]
Options are:
  [-_|--strip-underscore]     Ignore first leading underscore
  [-n|--no-strip-underscore]  Do not ignore a leading underscore (default)
  [-p|--no-params]            Do not display function arguments
  [-i|--no-verbose]           Do not show implementation details (if any)
  [-R|--recurse-limit]        Enable a limit on recursion whilst demangling.  [Default]
  ]-r|--no-recurse-limit]     Disable a limit on recursion whilst demangling
  [-t|--types]                Also attempt to demangle type encodings
  [-s|--format {none,auto,gnu-v3,java,gnat,dlang,rust}]
  [@<file>]                   Read extra options from <file>
  [-h|--help]                 Display this information
  [-v|--version]              Show the version information
Demangled names are displayed to stdout.
If a name cannot be demangled it is just echoed to stdout.
If no names are provided on the command line, stdin is read.
Makefile:75: recipe for target '../../AK/StringView.o' failed
make: *** [../../AK/StringView.o] Error 1
Makefile:75: recipe for target '../../AK/StringBuilder.o' failed
make: *** [../../AK/StringBuilder.o] Error 1
make: Leaving directory '/home/ferhatgec/Masaüstü/serenity-master/Libraries/LibC'

**Comment by rburchell** [comment] 2019-07-20 18:29
Duplicate of #216 by the looks of it. Make sure you are sourcing UseIt from *inside* the Toolchain directory, otherwise the paths you get in your environment won't be correct.

**Comment by awesomekling** [comment] 2019-08-12 17:02
Dupe of #216.

**Closed by awesomekling** 2019-08-12 17:02 UTC
