### ISSUE TITLE
FileManager: Deleting a file with the same name as an utility crashes FileManager

### ISSUE THREAD

**Issue by anarchyrucks** [SerenityOS/serenity#11763] opened 2022-01-09 14:32 UTC
When I create a filename with the same name as an utility eg. "sort.txt" and try to delete it, FileManager crashes. However, the deletion is successful. Tested with the following filenames: "sort.txt", "sort", "uniq" and "ls.txt".

Backtrace:
![image](https://user-images.githubusercontent.com/8762472/148686752-53c7e618-3516-4518-9936-bfef4fae81b7.png)

```
1679.642 [#0 FinalizerTask(4:4)]: Generating coredump for pid: 98
1679.874 CrashDaemon(9:9): New coredump file: /tmp/coredump/FileManager_98_1641738791
1679.960 CrashReporter(100:100): Started thread "", tid = 101
1680.257 [#0 SyncTask(3:3)]: Ext2FS: Flushed 3 blocks to disk
1681.031 CrashReporter(100:101): Generating backtrace took 1066 ms
1681.031 CrashReporter(100:101): --- Backtrace for thread #0 (TID 98) ---
1681.035 CrashReporter(100:101): 0x2816202e: [libsystem.so] syscall2 +0xe (syscall.cpp:25 => syscall.cpp:24)
1681.035 CrashReporter(100:101): 0x31ca3824: [libc.so] raise +0x24 (syscall.h:35 => signal.cpp:22 => signal.cpp:37)
1681.040 CrashReporter(100:101): 0x31c8ea79: [libc.so] abort +0x29 (stdlib.cpp:221)
1681.044 CrashReporter(100:101): 0x31c8f50c: [libc.so] __assertion_failed +0x6c (assert.cpp:33)
1681.044 CrashReporter(100:101): 0x371004dc: [libgui.so.serenity] AK::Function<void (GUI::AbstractView&)>::CallableWrapper<GUI::SortingProxyModel::sort_mapping(GUI::SortingProxyModel::Mapping&, int, GUI::SortOrder)::{lambda(GUI::AbstractView&)#2}>::call(GUI::AbstractView&) +0x1ec (Vector.h:139 => Vector.h:147 => Iterator.h:56 => ModelSelection.h:50 => SortingProxyModel.cpp:197)
1681.050 CrashReporter(100:101): 0x370d8176: [libgui.so.serenity] GUI::Model::for_each_view(AK::Function<void (GUI::AbstractView&)>) +0x76 (Function.h:91)
1681.053 CrashReporter(100:101): 0x370fff08: [libgui.so.serenity] GUI::SortingProxyModel::sort_mapping(GUI::SortingProxyModel::Mapping&, int, GUI::SortOrder) +0x158 (SortingProxyModel.cpp:192)
1681.056 CrashReporter(100:101): 0x371001d6: [libgui.so.serenity] GUI::SortingProxyModel::sort(int, GUI::SortOrder) [clone .localalias] +0x56 (SortingProxyModel.cpp:229)
1681.060 CrashReporter(100:101): 0x370ff5ee: [libgui.so.serenity] GUI::SortingProxyModel::update_sort(unsigned int) [clone .localalias] +0x3e (SortingProxyModel.cpp:34)
1681.060 CrashReporter(100:101): 0x370d82e6: [libgui.so.serenity] GUI::Model::for_each_client(AK::Function<void (GUI::ModelClient&)>) +0x76 (Function.h:91)
1681.068 CrashReporter(100:101): 0x370d8440: [libgui.so.serenity] GUI::Model::did_update(unsigned int) [clone .localalias] +0x60 (Model.cpp:54)
1681.068 CrashReporter(100:101): 0x3709ce05: [libgui.so.serenity] GUI::FileSystemModel::handle_file_event(Core::FileWatcherEvent const&) [clone .part.0] +0x55 (FileSystemModel.cpp:446)
1681.072 CrashReporter(100:101): 0x8c0aea86: [libcore.so.serenity] AK::Function<void ()>::CallableWrapper<Core::FileWatcher::FileWatcher(int, AK::NonnullRefPtr<Core::Notifier>)::{lambda()#1}>::call() +0xd6 (Function.h:91)
1681.072 CrashReporter(100:101): 0x8c0bbea9: [libcore.so.serenity] Core::Notifier::event(Core::Event&) [clone .localalias] +0x99 (Function.h:91)
1681.077 CrashReporter(100:101): 0x8c0bd1e0: [libcore.so.serenity] Core::Object::dispatch_event(Core::Event&, Core::Object*) +0xb0 (Object.cpp:219)
1681.077 CrashReporter(100:101): 0x8c0a77ce: [libcore.so.serenity] Core::EventLoop::pump(Core::EventLoop::WaitMode) [clone .localalias] +0x17e (EventLoop.cpp:415)
1681.081 CrashReporter(100:101): 0x8c0a837a: [libcore.so.serenity] Core::EventLoop::exec() +0x6a (EventLoop.cpp:372)
1681.081 CrashReporter(100:101): 0x37049bf7: [libgui.so.serenity] GUI::Application::exec() +0x27 (Application.cpp:119)
1681.081 CrashReporter(100:101): 0x06befde3: [/bin/FileManager] run_in_windowed_mode(AK::String const&, AK::String const&) +0x5ad3 (main.cpp:1319)
1681.089 CrashReporter(100:101): 0x06bf11c0: [/bin/FileManager] serenity_main(Main::Arguments) +0x840 (main.cpp:128)
1681.089 CrashReporter(100:101): 0x9a32a1d2: [libmain.so.serenity] main +0x72 (Main.cpp:20)
1681.089 CrashReporter(100:101): 0x06bc932c: [/bin/FileManager] _entry +0x5c (crt0.cpp:46)
```

**Comment by math2001** [comment] 2022-01-11 08:10
can you still replicate? I think i saw that crash but after pulling i couldn't get it.

**Comment by stefanos82** [comment] 2022-01-18 13:14
I would say this bug relates to #11342.

Here's the [explanation](https://github.com/SerenityOS/serenity/issues/11342#issuecomment-1015263730) by @sin-ack

**Comment by awesomekling** [comment] 2022-01-20 09:43
Duplicate of #11342

**Closed by awesomekling** 2022-01-20 09:43 UTC
Labels: bug
