### ISSUE TITLE
What is the vision for Ladybird ?

### ISSUE THREAD

**Issue by forrackun** [SerenityOS/serenity#20953] opened 2023-09-05 02:12 UTC
I have not contributed, and I do not think i have i will contribute in the near future, even though I think it is cool project would love to be involved. (i want to clear my position before i try to ask vision for project) 

Recently, I have been exploring a browser for running in a resource constrained environment (~512mb Linux arm soc) and think ladybird could be great for that, so my question is what vision for the project. Could ladybird be like QBE compiler alternative to more heavyweight LLVM. 

> QBE is a compiler backend that aims to provide 70% of the performance of industrial optimizing compilers in 10% of the code.. 

 Will Ladybird have multi tier JIT and other tricks to extract every bit of performance vs lightweight/portable embed friendly engine.
( multiprocess with IPC between different dedicated process VS single process but single tab ... if u need to run multi tab just run multiple separate instances ) It would really be nice if Ladybird targeted more niece use case, usually not specially targeted by other engines. 

- embed devices
- headless browser in backend (html2pdf, render dynamic site, scraping, run web test )
- crossplatfrom web view library
- etc

https://c9x.me/compile/

**Comment by awesomekling** [comment] 2023-09-05 06:11
The main goal is to make a browser capable of rendering the modern web with acceptable stability and performance. We're mainly targeting the desktop use case first, but mobile will probably happen as well.

Specialized embedded use-cases are not a goal.

Closing, as this is not a bug. :)

**Closed by awesomekling** 2023-09-05 06:11 UTC
