### ISSUE TITLE
FileManager: All processes spawned (e.g. through double-click) will be interrupted if the FM is interuppted from the shell

### ISSUE THREAD

**Issue by alimpfard** [SerenityOS/serenity#5306] opened 2021-02-12 16:49 UTC
repro:
```sh
$ fm
```
- Open some file, e.g. double-click whatever.txt to open a TextEditor
- press Ctrl-C in the terminal that FM is running in
- see it take TextEditor out too

**Comment by linusg** [comment] 2021-02-12 18:10
This only seems to be the case when running and interrupting FileManager in the shell, I can't reproduce this by just closing the FileManager window or doing `kill -2 $(pidof FileManager)`.

**Comment by alimpfard** [comment] 2021-02-12 18:15
Hmmm...then that's probably because it spawns the children in its own process group.
Not sure if that's correct behaviour

**Closed** 2022-07-09 10:41 UTC
Labels: bug
