### ISSUE TITLE
Seg-fault in WindowServer

### ISSUE THREAD

**Issue by DrewStratford** [SerenityOS/serenity#242] opened 2019-06-18 10:13 UTC
Encountered a seg fault in WindowServer, causing the entire OS to become unresponsive. I haven't been able to replicate it as of yet.

Attached is the debug log.
[WindowServerLog.txt](https://github.com/SerenityOS/serenity/files/3301009/WindowServerLog.txt)

**Comment by rburchell** [comment] 2019-06-18 12:22
Theory: WSClientConnection doesn't seem to clean up its windows if the WSClientConnection is torn down unexpectedly.

Since the windows in WSClientConnection are OwnPtr, I'd expect that deleting the connection tears up all those windows, but they'll still be referenced in WSWindowManager.

**Comment by awesomekling** [comment] 2019-06-19 04:42
Thanks for the crash log! I don't see anything obvious but I'll look closer when I have some time :)

**Comment by rburchell** [comment] 2019-06-19 08:17
Yeah, I looked more and didn't get anywhere either. The invalidate call when removing a window was a red herring..

**Comment by awesomekling** [comment] 2019-09-01 18:55
Since we don't have a way to reproduce this, and many things have changed, I'm just gonna close this.

**Closed by awesomekling** 2019-09-01 18:55 UTC
