### ISSUE TITLE
Desktop: File properties shouldn't be modal

### ISSUE THREAD

**Issue by tomuta** [SerenityOS/serenity#4724] opened 2021-01-01 23:03 UTC
If right-clicking a file on the desktop and showing its properties, we probably shouldn't show it as a modal dialog. If that properties window is covered by another application, clicking on the desktop won't work and also not give any clues as to why. We don't bring the modal window up top because the desktop window won't change its position in the stack, either. Those properties windows aren't modal at least on Windows and GNOME desktops, I think it makes sense to mimic the same behavior.

**Comment by linusg** [comment] 2021-01-01 23:06
Duplicate of #4648.

> Those properties windows aren't modal at least on Windows and GNOME desktops

They are on GNOME 3.

**Closed by linusg** 2021-01-01 23:06 UTC
Labels: enhancement
