### ISSUE TITLE
FileManager: Multiple crashes on boot

### ISSUE THREAD

**Issue by mrkct** [SerenityOS/serenity#7852] opened 2021-06-06 17:44 UTC
When I start Serenity sometimes the FileManager crashes, it restarts automatically and crashes again a few times. This is the backtrace for the 4 threads:
```
CrashDaemon(20:20): --- Backtrace for thread #0 (TID 31) ---
CrashDaemon(20:20): 0x790951ce: [libsystem.so] syscall2 +0xe (syscall.cpp:25)
CrashDaemon(20:20): 0x2b5a804f: [libc.so] kill +0x1f (signal.cpp:21)
CrashDaemon(20:20): 0x2b5a80f3: [libc.so] raise +0x23 (signal.cpp:34)
CrashDaemon(20:20): 0x2b592586: [libc.so] abort +0x2a (stdlib.cpp:233)
CrashDaemon(20:20): 0x2b59308b: [libc.so] __assertion_failed +0xeb (Format.h:236)
CrashDaemon(20:20): 0x9523537c: [libipc.so] IPC::Encoder::operator<<(IPC::File const&) +0x2bc (Encoder.cpp:156)
CrashDaemon(20:20): 0xb10f98a7: [libgui.so] Messages::WindowServer::SetWindowBackingStore::encode() const +0xb7 (WindowServerEndpoint.h:2784)
CrashDaemon(20:20): 0xb110889d: [libgui.so] IPC::Connection<WindowClientEndpoint, WindowServerEndpoint>::post_message(IPC::Message const&) +0x3d (Connection.h:54)
CrashDaemon(20:20): 0xb12035aa: [libgui.so] GUI::Window::set_current_backing_store(GUI::WindowBackingStore&, bool) +0xfa (WindowServerEndpoint.h:2719)
CrashDaemon(20:20): 0xb12036e4: [libgui.so] GUI::Window::flip(AK::Vector<Gfx::Rect<int>, 32ul> const&) +0x64 (Window.cpp:759)
CrashDaemon(20:20): 0xb1208e66: [libgui.so] GUI::Window::handle_multi_paint_event(GUI::MultiPaintEvent&) +0x8f6 (Window.cpp:412)
CrashDaemon(20:20): 0xb120b1ea: [libgui.so] GUI::Window::event(Core::Event&) +0x18a (Window.cpp:547)
CrashDaemon(20:20): 0x7966f101: [libcore.so] Core::Object::dispatch_event(Core::Event&, Core::Object*) +0xa1 (Object.h:113)
CrashDaemon(20:20): 0x79655c24: [libcore.so] Core::EventLoop::pump(Core::EventLoop::WaitMode) +0x404 (Atomic.h:246)
CrashDaemon(20:20): 0x7965648b: [libcore.so] Core::EventLoop::exec() +0x9b (EventLoop.cpp:362)
CrashDaemon(20:20): 0xb10ebd18: [libgui.so] GUI::Application::exec() +0x28 (Application.cpp:106)
CrashDaemon(20:20): 0x26f4a385: [/bin/FileManager] main +0x13f5 (main.cpp:422)
CrashDaemon(20:20): 0x26f4add8: [/bin/FileManager] _start +0x58 (crt0.cpp:39)
CrashDaemon(20:20): 
CrashDaemon(20:20): --- Backtrace for thread #1 (TID 32) ---
CrashDaemon(20:20): 0x790951bb: [libsystem.so] syscall1 +0xb (syscall.cpp:20)
CrashDaemon(20:20): 0x2b5bf537: [libc.so] serenity_mmap +0x77 (mman.cpp:19)
CrashDaemon(20:20): 0x2b59756d: [libc.so] malloc +0x64d (malloc.cpp:155)
CrashDaemon(20:20): 0x935fd10c: [libgfx.so] AK::Detail::ByteBuffer<32ul>::ensure_capacity_slowpath(unsigned long) +0x6c (ByteBuffer.h:242)
CrashDaemon(20:20): 0x7e5f01eb: [libcompress.so] AK::DuplexMemoryStream::write(AK::Span<unsigned char const>) +0xab (Vector.h:165)
CrashDaemon(20:20): 0x7e5ec103: [libcompress.so] Compress::DeflateDecompressor::decompress_all(AK::Span<unsigned char const>) +0x263 (Stream.h:24)
CrashDaemon(20:20): 0x7e5f073b: [libcompress.so] Compress::Zlib::decompress() +0x3b (Zlib.cpp:52)
CrashDaemon(20:20): 0x7e5f07bb: [libcompress.so] Compress::Zlib::decompress_all(AK::Span<unsigned char const>) +0x5b (Zlib.cpp:59)
CrashDaemon(20:20): 0x93650811: [libgfx.so] Gfx::decode_png_bitmap(Gfx::PNGLoadingContext&) +0x91 (Optional.h:130)
CrashDaemon(20:20): 0x93651e47: [libgfx.so] Gfx::load_png_impl(unsigned char const*, unsigned long) +0x177 (PNGLoader.cpp:795)
CrashDaemon(20:20): 0x93651fac: [libgfx.so] Gfx::load_png(AK::String const&) +0xbc (Atomic.h:246)
CrashDaemon(20:20): 0x935f721f: [libgfx.so] Gfx::Bitmap::load_from_file(AK::String const&, int) +0x110f (Bitmap.cpp:151)
CrashDaemon(20:20): 0xb1155e79: [libgui.so] GUI::render_thumbnail(AK::StringView const&) +0x49 (Atomic.h:246)
CrashDaemon(20:20): 0xb115fddd: [libgui.so] Threading::BackgroundAction<AK::RefPtr<Gfx::Bitmap, AK::RefPtrTraits<Gfx::Bitmap> > >::BackgroundAction(AK::Function<AK::RefPtr<Gfx::Bitmap, AK::RefPtrTraits<Gfx::Bitmap> > ()>, AK::Function<void (AK::RefPtr<Gfx::Bitmap, AK::RefPtrTraits<Gfx::Bitmap> >)>)::{lambda()#1}::operator()() const +0x9d (FileSystemModel.cpp:572)
CrashDaemon(20:20): 0xb11602be: [libgui.so] AK::Function<void ()>::CallableWrapper<Threading::BackgroundAction<AK::RefPtr<Gfx::Bitmap, AK::RefPtrTraits<Gfx::Bitmap> > >::BackgroundAction(AK::Function<AK::RefPtr<Gfx::Bitmap, AK::RefPtrTraits<Gfx::Bitmap> > ()>, AK::Function<void (AK::RefPtr<Gfx::Bitmap, AK::RefPtrTraits<Gfx::Bitmap> >)>)::{lambda()#1}>::call() +0x1e (Function.h:152)
CrashDaemon(20:20): 0xa3e31d96: [libthreading.so] background_thread_func() +0x106 (Atomic.h:206)
CrashDaemon(20:20): 0xa3e32695: [libthreading.so] Threading::Thread::start()::{lambda(void*)#1}::_FUN(void*) +0x55 (Function.h:91)
CrashDaemon(20:20): 0x78d04126: [libpthread.so] pthread_create_helper +0x36 (pthread.cpp:49)
CrashDaemon(20:20): 
CrashDaemon(20:20): --- Backtrace for thread #2 (TID 31) ---
CrashDaemon(20:20): 0x790951ce: [libsystem.so] syscall2 +0xe (syscall.cpp:25)
CrashDaemon(20:20): 0x2b5a804f: [libc.so] kill +0x1f (signal.cpp:21)
CrashDaemon(20:20): 0x2b5a80f3: [libc.so] raise +0x23 (signal.cpp:34)
CrashDaemon(20:20): 0x2b592586: [libc.so] abort +0x2a (stdlib.cpp:233)
CrashDaemon(20:20): 0x2b59308b: [libc.so] __assertion_failed +0xeb (Format.h:236)
CrashDaemon(20:20): 0x9523537c: [libipc.so] IPC::Encoder::operator<<(IPC::File const&) +0x2bc (Encoder.cpp:156)
CrashDaemon(20:20): 0xb10f98a7: [libgui.so] Messages::WindowServer::SetWindowBackingStore::encode() const +0xb7 (WindowServerEndpoint.h:2784)
CrashDaemon(20:20): 0xb110889d: [libgui.so] IPC::Connection<WindowClientEndpoint, WindowServerEndpoint>::post_message(IPC::Message const&) +0x3d (Connection.h:54)
CrashDaemon(20:20): 0xb12035aa: [libgui.so] GUI::Window::set_current_backing_store(GUI::WindowBackingStore&, bool) +0xfa (WindowServerEndpoint.h:2719)
CrashDaemon(20:20): 0xb12036e4: [libgui.so] GUI::Window::flip(AK::Vector<Gfx::Rect<int>, 32ul> const&) +0x64 (Window.cpp:759)
CrashDaemon(20:20): 0xb1208e66: [libgui.so] GUI::Window::handle_multi_paint_event(GUI::MultiPaintEvent&) +0x8f6 (Window.cpp:412)
CrashDaemon(20:20): 0xb120b1ea: [libgui.so] GUI::Window::event(Core::Event&) +0x18a (Window.cpp:547)
CrashDaemon(20:20): 0x7966f101: [libcore.so] Core::Object::dispatch_event(Core::Event&, Core::Object*) +0xa1 (Object.h:113)
CrashDaemon(20:20): 0x79655c24: [libcore.so] Core::EventLoop::pump(Core::EventLoop::WaitMode) +0x404 (Atomic.h:246)
CrashDaemon(20:20): 0x7965648b: [libcore.so] Core::EventLoop::exec() +0x9b (EventLoop.cpp:362)
CrashDaemon(20:20): 0xb10ebd18: [libgui.so] GUI::Application::exec() +0x28 (Application.cpp:106)
CrashDaemon(20:20): 0x26f4a385: [/bin/FileManager] main +0x13f5 (main.cpp:422)
CrashDaemon(20:20): 0x26f4add8: [/bin/FileManager] _start +0x58 (crt0.cpp:39)
CrashDaemon(20:20): 
CrashDaemon(20:20): --- Backtrace for thread #3 (TID 32) ---
CrashDaemon(20:20): 0x790951bb: [libsystem.so] syscall1 +0xb (syscall.cpp:20)
CrashDaemon(20:20): 0x2b5bf537: [libc.so] serenity_mmap +0x77 (mman.cpp:19)
CrashDaemon(20:20): 0x2b59756d: [libc.so] malloc +0x64d (malloc.cpp:155)
CrashDaemon(20:20): 0x935fd10c: [libgfx.so] AK::Detail::ByteBuffer<32ul>::ensure_capacity_slowpath(unsigned long) +0x6c (ByteBuffer.h:242)
CrashDaemon(20:20): 0x7e5f01eb: [libcompress.so] AK::DuplexMemoryStream::write(AK::Span<unsigned char const>) +0xab (Vector.h:165)
CrashDaemon(20:20): 0x7e5ec103: [libcompress.so] Compress::DeflateDecompressor::decompress_all(AK::Span<unsigned char const>) +0x263 (Stream.h:24)
CrashDaemon(20:20): 0x7e5f073b: [libcompress.so] Compress::Zlib::decompress() +0x3b (Zlib.cpp:52)
CrashDaemon(20:20): 0x7e5f07bb: [libcompress.so] Compress::Zlib::decompress_all(AK::Span<unsigned char const>) +0x5b (Zlib.cpp:59)
CrashDaemon(20:20): 0x93650811: [libgfx.so] Gfx::decode_png_bitmap(Gfx::PNGLoadingContext&) +0x91 (Optional.h:130)
CrashDaemon(20:20): 0x93651e47: [libgfx.so] Gfx::load_png_impl(unsigned char const*, unsigned long) +0x177 (PNGLoader.cpp:795)
CrashDaemon(20:20): 0x93651fac: [libgfx.so] Gfx::load_png(AK::String const&) +0xbc (Atomic.h:246)
CrashDaemon(20:20): 0x935f721f: [libgfx.so] Gfx::Bitmap::load_from_file(AK::String const&, int) +0x110f (Bitmap.cpp:151)
CrashDaemon(20:20): 0xb1155e79: [libgui.so] GUI::render_thumbnail(AK::StringView const&) +0x49 (Atomic.h:246)
CrashDaemon(20:20): 0xb115fddd: [libgui.so] Threading::BackgroundAction<AK::RefPtr<Gfx::Bitmap, AK::RefPtrTraits<Gfx::Bitmap> > >::BackgroundAction(AK::Function<AK::RefPtr<Gfx::Bitmap, AK::RefPtrTraits<Gfx::Bitmap> > ()>, AK::Function<void (AK::RefPtr<Gfx::Bitmap, AK::RefPtrTraits<Gfx::Bitmap> >)>)::{lambda()#1}::operator()() const +0x9d (FileSystemModel.cpp:572)
CrashDaemon(20:20): 0xb11602be: [libgui.so] AK::Function<void ()>::CallableWrapper<Threading::BackgroundAction<AK::RefPtr<Gfx::Bitmap, AK::RefPtrTraits<Gfx::Bitmap> > >::BackgroundAction(AK::Function<AK::RefPtr<Gfx::Bitmap, AK::RefPtrTraits<Gfx::Bitmap> > ()>, AK::Function<void (AK::RefPtr<Gfx::Bitmap, AK::RefPtrTraits<Gfx::Bitmap> >)>)::{lambda()#1}>::call() +0x1e (Function.h:152)
CrashDaemon(20:20): 0xa3e31d96: [libthreading.so] background_thread_func() +0x106 (Atomic.h:206)
CrashDaemon(20:20): 0xa3e32695: [libthreading.so] Threading::Thread::start()::{lambda(void*)#1}::_FUN(void*) +0x55 (Function.h:91)
CrashDaemon(20:20): 0x78d04126: [libpthread.so] pthread_create_helper +0x36 (pthread.cpp:49)

```

**Comment by bgianfo** [comment] 2021-06-06 23:49
The back trace is only of two threads, there's a bug where they are reported / captured twice.
The thread in the back trace asserted because `dup(..)` failed.  

https://github.com/SerenityOS/serenity/blob/de9b454f897aee3d7b1cd1a8235a40360da5425f/Userland/Libraries/LibIPC/Encoder.cpp#L149-L161

Was the system low on memory during this? That's the only explanation for `dup(..)` failing that I can imagine... unless we h ave some race in the kernel somewhere.

**Comment by tomuta** [comment] 2021-07-12 03:00
This looks very much like a duplicate of #7641

**Comment by kleinesfilmroellchen** [comment] 2022-01-13 19:35
If nobody complains because it can still be reproduced, I'll close this now as a duplicate.

**Closed by kleinesfilmroellchen** 2022-01-13 19:35 UTC
Labels: duplicate
