### ISSUE TITLE
Ladybird: `HTMLOptionElement` is not rendered

### ISSUE THREAD

**Issue by fdellwing** [SerenityOS/serenity#20562] opened 2023-08-13 18:50 UTC
```
<html><body>
<select>
<option>foobar</option>
</select>
</body></html>
```

The `select` and it's containing `option` is not rendered at all:

```
Viewport <#document> at (0,0) content-size 1918x957 [0+0+0 1918 0+0+0] [0+0+0 957 0+0+0] children: not-inline
  BlockContainer <html> at (0,0) content-size 1918x957 [0+0+0 1918 0+0+0] [0+0+0 957 0+0+0] [BFC] children: not-inline
    BlockContainer <body> at (8,8) content-size 1902x0 [8+0+0 1902 0+0+8] [8+0+0 0 0+0+8] children: inline
      TextNode <#text>
      InlineNode <select>
        TextNode <#text>
        TextNode <#text>
      TextNode <#text>
```

**Comment by MacDue** [comment] 2023-08-13 19:49
Duplicate of https://github.com/SerenityOS/serenity/issues/17970 (these are not implemented yet)

**Closed by MacDue** 2023-08-13 19:49 UTC
