### ISSUE TITLE
Kernel Panic when attempt to use Display Settings

### ISSUE THREAD

**Issue by stefanos82** [SerenityOS/serenity#12249] opened 2022-02-01 23:02 UTC
I have tried a couple of themes and I saw a slowness on SerenityOS as a whole, but didn't pay attention; then, I tried to change my resolution to `800x600` so I can see how it looks on my screen (it's an HD monitor with very limited resolution I'm afraid) and that's when I have noticed SerenityOS froze as a whole.

Here's what the host's terminal printed:

```
912.822 Taskbar(30:30): Theme switched to Basalt at path /res/themes/Basalt.ini
913.860 [#0 SyncTask(3:3)]: Ext2FS: Flushed 4 blocks to disk
918.583 Taskbar(30:30): Theme switched to Coffee at path /res/themes/Coffee.ini
919.009 [#0 SyncTask(3:3)]: Ext2FS: Flushed 4 blocks to disk
926.908 Taskbar(30:30): Theme switched to Cupertino at path /res/themes/Cupertino.ini
927.181 [#0 SyncTask(3:3)]: Ext2FS: Flushed 4 blocks to disk
933.025 DisplaySettings(45:45): Started thread "", tid = 46
941.325 WindowServer(17:17): Started thread "", tid = 47
941.358 DisplaySettings(45:45): Saving wallpaper path '' to ConfigServer
941.871 [#0 SyncTask(3:3)]: Ext2FS: Flushed 4 blocks to disk
942.979 [#0 SyncTask(3:3)]: Ext2FS: Flushed 2 blocks to disk
944.129 [#0 SyncTask(3:3)]: Ext2FS: Flushed 2 blocks to disk
944.692 WindowServer(17:17): Updating fonts: 'Katica 10 400 0' and 'Csilla 10 400 0'
944.808 WindowServer(17:17): Closing device /dev/fb0 in preparation for resolution change
944.813 [#0 WindowServer(17:17)]: BochsGraphicsAdapter: resolution set to 800x600
944.813 [#0 WindowServer(17:17)]: Framebuffer Console: taking 1921024 bytes
944.832 [#0 WindowServer(17:17)]: VC 0: Resized to 100 x 75
944.836 [#0 WindowServer(17:17)]: VC 1: Resized to 100 x 75
944.836 [#0 WindowServer(17:17)]: VC 2: Resized to 100 x 75
944.857 [#0 WindowServer(17:17)]: VC 3: Resized to 100 x 75
944.857 [#0 WindowServer(17:17)]: VC 4: Resized to 100 x 75
944.857 [#0 WindowServer(17:17)]: VC 5: Resized to 100 x 75
944.864 WindowServer(17:17): update_virtual_rect for screen #0: [0,0 800x600]
944.864 WindowServer(17:17): update_virtual_rect for screen #0: [0,0 800x600]
[DisplaySettings(45:45)]: ASSERTION FAILED: blocked_thread_list.contains(current_thread)
[DisplaySettings(45:45)]: ./Kernel/Locking/Mutex.cpp:217 in void Kernel::Mutex::block(Kernel::Thread&, Kernel::Mutex::Mode, Kernel::SpinlockLocker<Kernel::Spinlock>&, u32)
[DisplaySettings(45:45)]: KERNEL PANIC! :^(
[DisplaySettings(45:45)]: Aborted
[DisplaySettings(45:45)]: at ./Kernel/Arch/x86/common/CPU.cpp:35 in void abort()
[DisplaySettings(45:45)]: Kernel + 0x0000000000f9aa22  Kernel::__panic(char const*, unsigned int, char const*) +0x162
[DisplaySettings(45:45)]: Kernel + 0x000000000144ec34  abort.localalias +0x382
[DisplaySettings(45:45)]: Kernel + 0x000000000144e8b2  abort.localalias +0x0
[DisplaySettings(45:45)]: Kernel + 0x0000000000dc900e  Kernel::Mutex::block(Kernel::Thread&, Kernel::LockMode, Kernel::SpinlockLocker<Kernel::Spinlock>&, unsigned int) [clone .localalias] +0x9de
[DisplaySettings(45:45)]: Kernel + 0x0000000000dcee8b  Kernel::Mutex::lock(Kernel::LockMode, Kernel::LockLocation const&) +0x51b
[DisplaySettings(45:45)]: Kernel + 0x000000000098d357  Kernel::Ext2FS::get_inode(Kernel::InodeIdentifier) const [clone .localalias] +0xd7
[DisplaySettings(45:45)]: Kernel + 0x0000000000992278  Kernel::Ext2FSInode::lookup(AK::StringView) [clone .localalias] +0x3d8
[DisplaySettings(45:45)]: Kernel + 0x0000000000bb7345  Kernel::VirtualFileSystem::resolve_path_without_veil(AK::StringView, Kernel::Custody&, AK::RefPtr<Kernel::Custody, AK::RefPtrTraits<Kernel::Custody> >*, int, int) [clone .localalias] +0xe85
[DisplaySettings(45:45)]: Kernel + 0x0000000000bbe76e  Kernel::VirtualFileSystem::resolve_path(AK::StringView, Kernel::Custody&, AK::RefPtr<Kernel::Custody, AK::RefPtrTraits<Kernel::Custody> >*, int, int) [clone .localalias] +0x6e
[DisplaySettings(45:45)]: Kernel + 0x0000000000bdf362  Kernel::VirtualFileSystem::open(AK::StringView, int, unsigned short, Kernel::Custody&, AK::Optional<Kernel::UidAndGid>) +0xc2
[DisplaySettings(45:45)]: Kernel + 0x00000000011b2a89  Kernel::Process::sys$open(AK::Userspace<Kernel::Syscall::SC_open_params const*>) +0x10f9
[DisplaySettings(45:45)]: Kernel + 0x00000000010a1738  syscall_handler +0x2218
[DisplaySettings(45:45)]: Kernel + 0x0000000001478911  syscall_entry +0x51
```

**Comment by bgianfo** [comment] 2022-02-01 23:38
Looks like a duplicate of #9401

**Closed by bgianfo** 2022-02-01 23:38 UTC
Labels: duplicate
