### ISSUE TITLE
WindowServer: Minimization animation targets are not updated after screen resolution change

### ISSUE THREAD

**Issue by xTibor** [SerenityOS/serenity#1372] opened 2020-03-07 13:15 UTC
**Reproduction:**
1. Open any minimizable window at 640x480
2. Set the screen resolution to 800x600
3. Minimize/unminimize the window: https://streamable.com/wwolc

**Comment by auronandace** [comment] 2021-04-15 15:11
I can't reproduce this. From the date of the issue it was when there was a global menu, which is no longer the case. Can this issue be closed now?

**Comment by awesomekling** [comment] 2021-04-15 15:24
Thanks for checking that. Closing and we can open a new issue if the bug is seen again.

**Closed by awesomekling** 2021-04-15 15:24 UTC
Labels: bug
