### ISSUE TITLE
LibWeb: wrong vertical alignment for a span inside a button

### ISSUE THREAD

**Issue by Moldytzu** [SerenityOS/serenity#18829] opened 2023-05-14 11:51 UTC
`<button style="height:100px;width:100px;"><span style="background-color:red;height:30px;width:30px;display:block;">`
Ladybird:
![image](https://github.com/SerenityOS/serenity/assets/40271862/bbba2999-91ae-451e-9b88-a0d09272282e)
Firefox:
![image](https://github.com/SerenityOS/serenity/assets/40271862/4fd84105-d800-4729-83c2-a2196ad03b6a)

**Comment by MacDue** [comment] 2023-05-14 16:40
Thanks for the issue, but this is duplicate of #18701

**Closed by MacDue** 2023-05-14 16:40 UTC
