### ISSUE TITLE
FTP protocol

### ISSUE THREAD

**Issue by machinecp** [SerenityOS/serenity#2671] opened 2020-06-30 19:48 UTC
Hello guys in the functionalities of the operating system already have an FTP system?
I would like to work on it, although my strength is not the c ++ language, if they do not have I will try to do it, because I think they already have network support.

**Comment by linusg** [comment] 2020-06-30 19:53
No FTP support yet (I haven't looked if something in `Ports/` might qualify, but that doesn't count anyway :grin:) . There was some work towards it, but the PR has been closed by its author (@sppmacd) recently: https://github.com/SerenityOS/serenity/pull/2284

Also see https://github.com/SerenityOS/serenity/issues/2223 for some related discussion.

**Comment by machinecp** [comment] 2020-06-30 20:28
oh thank you very much :) I will review the issues

**Comment by linusg** [comment] 2020-12-12 19:47
Closing as dupe of #2223.

**Closed by linusg** 2020-12-12 19:47 UTC
Labels: duplicate
