### ISSUE TITLE
Browser: Scrollbar flickering when shrinking window

### ISSUE THREAD

**Issue by frhun** [SerenityOS/serenity#14494] opened 2022-07-05 15:54 UTC
The scrollbars in Browser flicker when shrinking the Browser window.
This is caused by the content size being the basis of calculating the scrollbar visibility, but that size only gets calculated after the resize.
The solution to this would be to calculate the minimum content size and pass it to `AbstractScrollableWidget::set_min_content_size()`

**Comment by linusg** [comment] 2022-07-05 16:41
Duplicate of #5437, #10650, and #13518.

**Closed by linusg** 2022-07-05 16:41 UTC
