### ISSUE TITLE
Failed to boot after run ./run　command

### ISSUE THREAD

**Issue by PaperJetJia** [SerenityOS/serenity#1086] opened 2020-01-17 02:11 UTC
First of all, Thanks for your selfless help. 

This the issue I've encountered.

![Screenshot from 2020-01-17 09-52-04](https://user-images.githubusercontent.com/50317297/72577877-2ec24e00-390f-11ea-8a1d-5fd8015962ce.png)

I have to mention that after I run BuildIt.sh in Toolchain directory, I got this:
![Screenshot from 2020-01-17 10-00-35](https://user-images.githubusercontent.com/50317297/72578216-64b40200-3910-11ea-90dc-4477325e2470.png)

I'm using ubuntu 18.04.2 LTS.
![Screenshot from 2020-01-17 09-56-29](https://user-images.githubusercontent.com/50317297/72578017-c1fb8380-390f-11ea-9812-b63bfd98bb01.png)

Thanks!

**Comment by N00byEdge** [comment] 2020-01-17 12:12
Duplicate of #1075 I guess

**Comment by awesomekling** [comment] 2020-01-17 21:37
Have you tried a clean build in a completely fresh checkout? I tried one just now and it works fine.

**Comment by PaperJetJia** [comment] 2020-01-18 06:01
Thanks a lot!
But after I run "./makeall.sh" in the Kernel directory, I got this.
(BTW, the "./BuildIt.sh" command is fine without errors.)

![Screenshot from 2020-01-18 13-55-37](https://user-images.githubusercontent.com/50317297/72659419-4b878000-39fa-11ea-99f9-7481c1b4b1b8.png)

The  "./run" is still same as above.

![Screenshot from 2020-01-18 13-59-30](https://user-images.githubusercontent.com/50317297/72659457-d1a3c680-39fa-11ea-949a-9c323222531d.png)

**Comment by marprok** [comment] 2020-01-18 21:15
@PaperJetJia Have you tried to execute `Kernel/build-image-qemu.sh`?

**Comment by PaperJetJia** [comment] 2020-01-19 00:47
@marprok Thanks, sir! 
I've just tried it and got this:
```shell
paperjet@paperjet-X442UR:~/repos/serenity-master/Kernel$ sudo ./build-image-qemu.sh
[sudo] password for paperjet: 
setting up disk image...
Formatting '_disk_image', fmt=raw size=629145600
done
creating new filesystem... done
mounting filesystem... done
creating initial filesystem structure... done
setting up device nodes... done
installing base system... cp: cannot stat '../Root/*': No such file or directory
unmounting filesystem... done
```

Then I run `./run`:
```shell
paperjet@paperjet-X442UR:~/repos/serenity-master/Kernel$ ./run
WARNING: Image format was not specified for '_disk_image' and probing guessed raw.
         Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
         Specify the 'raw' format explicitly to remove the restrictions.
CPU Reset (CPU 0)
EAX=00000000 EBX=00000000 ECX=00000000 EDX=00000000
ESI=00000000 EDI=00000000 EBP=00000000 ESP=00000000
EIP=00000000 EFL=00000000 [-------] CPL=0 II=0 A20=0 SMM=0 HLT=0
ES =0000 00000000 00000000 00000000
CS =0000 00000000 00000000 00000000
SS =0000 00000000 00000000 00000000
DS =0000 00000000 00000000 00000000
FS =0000 00000000 00000000 00000000
GS =0000 00000000 00000000 00000000
LDT=0000 00000000 00000000 00000000
TR =0000 00000000 00000000 00000000
GDT=     00000000 00000000
IDT=     00000000 00000000
CR0=00000000 CR2=00000000 CR3=00000000 CR4=00000000
DR0=00000000 DR1=00000000 DR2=00000000 DR3=00000000 
DR6=00000000 DR7=00000000
CCS=00000000 CCD=00000000 CCO=DYNAMIC 
EFER=0000000000000000
FCW=0000 FSW=0000 [ST=0] FTW=ff MXCSR=00000000
FPR0=0000000000000000 0000 FPR1=0000000000000000 0000
FPR2=0000000000000000 0000 FPR3=0000000000000000 0000
FPR4=0000000000000000 0000 FPR5=0000000000000000 0000
FPR6=0000000000000000 0000 FPR7=0000000000000000 0000
XMM00=00000000000000000000000000000000 XMM01=00000000000000000000000000000000
XMM02=00000000000000000000000000000000 XMM03=00000000000000000000000000000000
XMM04=00000000000000000000000000000000 XMM05=00000000000000000000000000000000
XMM06=00000000000000000000000000000000 XMM07=00000000000000000000000000000000
qemu: could not load kernel 'kernel': No such file or directory
paperjet@paperjet-X442UR:~/repos/serenity-master/Kernel$ 
```
Sorry to bother you again.

**Comment by marprok** [comment] 2020-01-19 08:31
@PaperJetJia Can you try and make the whole project again? Just go to the serenity root folder and execute `make`. When this is done(assuming no errors appear) execute `Kernel/run`.

**Comment by PaperJetJia** [comment] 2020-01-20 02:28
@marprok Thanks, sir! 
I retry this and run `make` but I got this:
```shell
paperjet@paperjet-X442UR:~/serenity-master$ make
make[1]: Entering directory '/home/paperjet/serenity-master/Libraries'
make[2]: Entering directory '/home/paperjet/serenity-master/Libraries/LibC'
LibC: C++ crt0.o
make[2]: /home/paperjet/serenity-master/Toolchain/Local/bin/i686-pc-serenity-g++: Command not found
../../Makefile.common:99: recipe for target 'crt0.o' failed
make[2]: *** [crt0.o] Error 127
make[2]: Leaving directory '/home/paperjet/serenity-master/Libraries/LibC'
../Makefile.subdir:3: recipe for target 'LibC/.' failed
make[1]: *** [LibC/.] Error 2
make[1]: Leaving directory '/home/paperjet/serenity-master/Libraries'
Makefile.subdir:3: recipe for target 'Libraries' failed
make: *** [Libraries] Error 2
```
I'm considering reinstall my ubuntu system. I don't want to bother you over and over again.
Thanks !

**Comment by marprok** [comment] 2020-01-20 06:45
@PaperJetJia You don't have to reinstall your entire OS. I would recommend you to do a fresh clone of the serenity repository and try the entire process one more time. First you go to Toolchan and run `BuildIt.sh`, after it is done go to the serenity root directory and run `make`. Finally try and execute the `Kernel/sync.sh` which should create the disk image that serenity uses. After all of the above is done, you can proceed and execute the `Kernel/run` script and hope for the best.

**Comment by supercomputer7** [comment] 2020-01-20 19:54
I saw one time that problem when you can't build the toolchain (same reason as in the picture).
Just clone the project again or do some cleaning & pulling, then try again.

**Comment by PaperJetJia** [comment] 2020-01-21 05:20
@marprok @supercomputer7  
Thank you for being so considerate!
I followed the steps but the problem is still the same. Although I reinstall my OS and retry several times (from `git clone` to run), the issue is still in there. 
This is the first time I post an issue, maybe I didn't make the problem clear. 
I'm new to the operating system, thanks for your considerate help, and I've decided to postpone this for a moment. See you guys!

**Comment by Quaker762** [comment] 2020-01-21 05:44
@awesomekling I'm going to give this a crack on a VM later and see what the
issue is. I reckon we should move back to using `UseIt.sh` (but that's
obviously just my opinion)

**Comment by Quaker762** [comment] 2020-01-23 09:19
@PaperJetJia Okay so I've had a quick look into this and couldn't reproduce it. Can you try this for me please:

1. Delete any instances of `serenity` on your system.
2. Create a new folder in your home directory called `SerenityOS` or something similar
3. Clone serenity in there and run `mv serenity serenity-blah` or something similar
4. Rerun `BuildIt.sh`
5. Run `./makeall`

Post the results here so we can try and get this fixed :)

**Comment by PaperJetJia** [comment] 2020-01-24 01:58
@Quaker762 Thank you for being so considerate!

After I run `./makeall.sh` I got this. 
```shell
paperjet@paperjet-X442UR:~/SerenityOS/serenity-blah/Kernel$ ./makeall.sh
[sudo] password for paperjet: 
uid=0(root) gid=0(root) groups=0(root)
make: Entering directory '/home/paperjet/SerenityOS/serenity-blah'
make[1]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Libraries'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Libraries/LibC'
LibC: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Libraries/LibC'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Libraries/LibM'
LibM: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Libraries/LibM'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Libraries/LibHTML'
make[3]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Libraries/LibHTML/CodeGenerators'
make[4]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Libraries/LibHTML/CodeGenerators/Generate_CSS_PropertyID_cpp'
Generate_CSS_PropertyID_cpp: CLEAN
make[4]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Libraries/LibHTML/CodeGenerators/Generate_CSS_PropertyID_cpp'
make[4]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Libraries/LibHTML/CodeGenerators/Generate_CSS_PropertyID_h'
Generate_CSS_PropertyID_h: CLEAN
make[4]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Libraries/LibHTML/CodeGenerators/Generate_CSS_PropertyID_h'
make[3]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Libraries/LibHTML/CodeGenerators'
LibHTML: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Libraries/LibHTML'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Libraries/LibPCIDB'
LibPCIDB: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Libraries/LibPCIDB'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Libraries/LibThread'
LibThread: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Libraries/LibThread'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Libraries/LibMarkdown'
LibMarkdown: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Libraries/LibMarkdown'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Libraries/LibVT'
LibVT: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Libraries/LibVT'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Libraries/LibGUI'
LibGUI: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Libraries/LibGUI'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Libraries/LibAudio'
LibAudio: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Libraries/LibAudio'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Libraries/LibIPC'
LibIPC: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Libraries/LibIPC'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Libraries/LibDraw'
LibDraw: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Libraries/LibDraw'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Libraries/LibELF'
LibELF: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Libraries/LibELF'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Libraries/LibPthread'
LibPthread: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Libraries/LibPthread'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Libraries/LibProtocol'
LibProtocol: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Libraries/LibProtocol'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Libraries/LibCore'
LibCore: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Libraries/LibCore'
make[1]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Libraries'
make[1]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/AK'
AK: CLEAN
make[1]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/AK'
make[1]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/DevTools'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/DevTools/Inspector'
Inspector: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/DevTools/Inspector'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/DevTools/HackStudio'
HackStudio: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/DevTools/HackStudio'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/DevTools/IPCCompiler'
IPCCompiler: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/DevTools/IPCCompiler'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/DevTools/VisualBuilder'
VisualBuilder: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/DevTools/VisualBuilder'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/DevTools/ProfileViewer'
ProfileViewer: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/DevTools/ProfileViewer'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/DevTools/FormCompiler'
FormCompiler: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/DevTools/FormCompiler'
make[1]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/DevTools'
make[1]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Servers'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Servers/ProtocolServer'
ProtocolServer: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Servers/ProtocolServer'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Servers/TelnetServer'
TelnetServer: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Servers/TelnetServer'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Servers/WindowServer'
WindowServer: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Servers/WindowServer'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Servers/TTYServer'
TTYServer: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Servers/TTYServer'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Servers/AudioServer'
AudioServer: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Servers/AudioServer'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Servers/SystemServer'
SystemServer: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Servers/SystemServer'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Servers/LookupServer'
LookupServer: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Servers/LookupServer'
make[1]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Servers'
make[1]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Applications'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Applications/FontEditor'
FontEditor: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Applications/FontEditor'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Applications/PaintBrush'
PaintBrush: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Applications/PaintBrush'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Applications/FileManager'
FileManager: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Applications/FileManager'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Applications/ChanViewer'
ChanViewer: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Applications/ChanViewer'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Applications/TextEditor'
TextEditor: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Applications/TextEditor'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Applications/Welcome'
Welcome: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Applications/Welcome'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Applications/Piano'
Piano: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Applications/Piano'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Applications/IRCClient'
IRCClient: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Applications/IRCClient'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Applications/QuickShow'
QuickShow: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Applications/QuickShow'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Applications/SystemMonitor'
SystemMonitor: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Applications/SystemMonitor'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Applications/DisplayProperties'
DisplayProperties: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Applications/DisplayProperties'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Applications/About'
About: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Applications/About'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Applications/Browser'
Browser: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Applications/Browser'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Applications/Terminal'
Terminal: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Applications/Terminal'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Applications/SoundPlayer'
SoundPlayer: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Applications/SoundPlayer'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Applications/Calculator'
Calculator: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Applications/Calculator'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Applications/Taskbar'
Taskbar: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Applications/Taskbar'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Applications/HexEditor'
HexEditor: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Applications/HexEditor'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Applications/Help'
Help: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Applications/Help'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Applications/SystemDialog'
SystemDialog: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Applications/SystemDialog'
make[1]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Applications'
make[1]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Kernel'
Kernel: CLEAN
make[1]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Kernel'
make[1]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/MenuApplets'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/MenuApplets/Clock'
Clock: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/MenuApplets/Clock'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/MenuApplets/Audio'
Audio: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/MenuApplets/Audio'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/MenuApplets/CPUGraph'
CPUGraph: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/MenuApplets/CPUGraph'
make[1]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/MenuApplets'
make[1]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Shell'
Shell: CLEAN
make[1]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Shell'
make[1]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Userland'
Userland: CLEAN
make[1]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Userland'
make[1]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Games'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Games/Minesweeper'
Minesweeper: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Games/Minesweeper'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Games/Snake'
Snake: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Games/Snake'
make[1]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Games'
make[1]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Demos'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Demos/HelloWorld'
HelloWorld: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Demos/HelloWorld'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Demos/WidgetGallery'
WidgetGallery: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Demos/WidgetGallery'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Demos/Fire'
Fire: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Demos/Fire'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Demos/HelloWorld2'
HelloWorld2: CLEAN
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Demos/HelloWorld2'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Demos/DynamicLink'
make[3]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Demos/DynamicLink/LinkDemo'
LinkDemo: CLEAN
make[3]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Demos/DynamicLink/LinkDemo'
make[3]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Demos/DynamicLink/LinkLib'
LinkLib: CLEAN
make[3]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Demos/DynamicLink/LinkLib'
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Demos/DynamicLink'
make[1]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Demos'
make: Leaving directory '/home/paperjet/SerenityOS/serenity-blah'
make: Entering directory '/home/paperjet/SerenityOS/serenity-blah'
make[1]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Libraries'
make[2]: Entering directory '/home/paperjet/SerenityOS/serenity-blah/Libraries/LibC'
LibC: C++ crt0.o
make[2]: /home/paperjet/SerenityOS/serenity-blah/Toolchain/Local/bin/i686-pc-serenity-g++: Command not found
../../Makefile.common:99: recipe for target 'crt0.o' failed
make[2]: *** [crt0.o] Error 127
make[2]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Libraries/LibC'
../Makefile.subdir:3: recipe for target 'LibC/.' failed
make[1]: *** [LibC/.] Error 2
make[1]: Leaving directory '/home/paperjet/SerenityOS/serenity-blah/Libraries'
Makefile.subdir:3: recipe for target 'Libraries' failed
make: *** [Libraries] Error 2
make: Leaving directory '/home/paperjet/SerenityOS/serenity-blah'
```

**Comment by awesomekling** [comment] 2020-01-26 17:45
Closing old build-related issues since we have a build bot and several people building the system many times per day. There's no need to open build-related issues, please fix the problem on your end instead. :)

**Closed by awesomekling** 2020-01-26 17:45 UTC
