### ISSUE TITLE
vim and less crash with an assertion in printf_internal

### ISSUE THREAD

**Issue by NattyNarwhal** [SerenityOS/serenity#646] opened 2019-10-12 14:45 UTC
```
vim(17): printf_internal: Unimplemented format specifier .
USERSPACE(17) ASSERTION FAILED: false
/home/calvin/src/serenity/AK/PrintfImplementation.h:357 in int printf_internal(PutChFunc, char*, const char*&, va_list) [with PutChFunc = void (*)(char*&, char); va_list = char*]
```

```
less(18): printf_internal: Unimplemented format specifier .
USERSPACE(18) ASSERTION FAILED: false
/home/calvin/src/serenity/AK/PrintfImplementation.h:357 in int printf_internal(PutChFunc, char*, const char*&, va_list) [with PutChFunc = void (*)(char*&, char); va_list = char*]
signal: less(18) sent 6 to less(18)
terminate_due_to_signal less(18) <- 6
Finalizing Thread 0 in less(18)
0x0002f411  Scheduler::switch_now() +51
0x0002f8b5  Scheduler::yield() +69
0x00022eb3  Thread::block_helper() +27
0x0004f7a8  Thread::BlockResult Thread::block<Thread::SemiPermanentBlocker, Thread::SemiPermanentBlocker::Reason>(Thread::SemiPermanentBlocker::Reason&&) +118
0x0001bab7  Process::sys$kill(int, int) +189
0x00024cfc  syscall_trap_entry +545
0x00024a8e  syscall_trap_handler +40
0x080728bc  raise +22
0x080480c6  abort +13
0x08072844  kill +0
0x0806e065  vsprintf +3207
0x0806e0a2  sprintf +23
0x08066677  _nc_read_entry +39
0x0805ed2e  tgetent_sp +46
```

Seems like it's probably a shared ncurses issue?

**Comment by NattyNarwhal** [comment] 2019-10-13 02:17
so does GNU ar:

```
ar(18): printf_internal: Unimplemented format specifier .
USERSPACE(18) ASSERTION FAILED: false
/home/calvin/src/serenity/AK/PrintfImplementation.h:357 in int printf_internal(PutChFunc, char*, const char*&, va_list) [with PutChFunc = void (*)(char*&, char); va_list = char*]
signal: ar(18) sent 6 to ar(18)
terminate_due_to_signal ar(18) <- 6
Finalizing Thread 0 in ar(18)
ar(18) Couldn't find user region for V0x69727453
0x0002f407  Scheduler::switch_now() +51
0x0002f8ab  Scheduler::yield() +69
0x00022ed3  Thread::block_helper() +27
0x0004f7b0  Thread::BlockResult Thread::block<Thread::SemiPermanentBlocker, Thread::SemiPermanentBlocker::Reason>(Thread::SemiPermanentBlocker::Reason&&) +118
0x0001badb  Process::sys$kill(int, int) +189
0x00024d1c  syscall_trap_entry +545
0x00024aae  syscall_trap_handler +40
0x080cc966  raise +22
0x080481b4  abort +13
0x080cc8ee  kill +0
0x080c7f5f  vsprintf +3207
0x080c7f9c  sprintf +23
0x0804d103  print_arelt_descr +195
0x080dbe20  plugin_vec +0
0x6d49676e  ??
```

**Comment by Pulgovisk** [comment] 2019-10-14 11:24
Related to #623

**Comment by awesomekling** [comment] 2019-10-14 19:46
Dupe of #623

**Closed by awesomekling** 2019-10-14 19:46 UTC
