### ISSUE TITLE
Taskbar: render window icons at 16x16, regardless of icon size

### ISSUE THREAD

**Issue by GMTA** [SerenityOS/serenity#7931] opened 2021-06-08 23:33 UTC
The taskbar renders a button with the window icon, regardless of the size of that icon:
![image](https://user-images.githubusercontent.com/3210731/121270551-3ac2fd00-c8c2-11eb-9f8c-4e33aac0722d.png)

In the example above, you can see that `GUI::Window` correctly scales down the icon to 16x16 (probably `Painter::draw_scaled_bitmap`). However, the `GUI::Button` in the taskbar does not perform automatic scaling causing the icon to show up too large.

Note: creating a new 16x16 scaled-down icon and providing that to `GUI::Button` works, but does not look nice when using 2x screen scale.

**Comment by linusg** [comment] 2021-06-09 09:31
Duplicate of #5806.

**Closed by linusg** 2021-06-09 09:31 UTC
