### ISSUE TITLE
LibGUI: Menus can appear off screen

### ISSUE THREAD

**Issue by mikeakers** [SerenityOS/serenity#14337] opened 2022-06-19 16:15 UTC
If a window is positioned too close to the right or bottom edge of the desktop and you open a menu, the menu can appear partially off screen. The way other operating systems handle this is by updating the menu's position in this scenario so the menu appears completely on screen. I'm going to attempt to do the same thing in serenity.

What happens today in Serenity:

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/673699/174490354-5246507e-8181-4d0e-b6f2-61b5e62e7b64.png">

The same scenario in Windows 2000

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/673699/174490368-27657c47-669f-4fa4-961e-09fd57dedaf1.png">

**Comment by linusg** [comment] 2022-06-19 19:59
Duplicate of #5952.

**Closed by linusg** 2022-06-19 19:59 UTC
