### ISSUE TITLE
Kernel: Pointer overflow in sigaction

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#5497] opened 2021-02-24 10:58 UTC
Found with fuzz-syscalls:
```
fuzz-syscalls(53): #3889: Calling sigaction(0x0000000d, 0x0000000d, 0xffffffff) with 0x9c3d7000 containing [0x716800ec, 0xc0000000, 0xc0000000, 0x9c3d7000, 0xc0000000, 0x0000000d, 0x9c3d7000, 0x00000001, 0x00000001]
[#0 H(53:53)]: KUBSAN: type mismatch, 'struct sigaction' (1-bit)
[#0 H(53:53)]: KUBSAN: at ../Kernel/Syscalls/sigaction.cpp, line 78, column: 26
[#0 H(53:53)]: 0xc0486161  print_location +0x225
[#0 H(53:53)]: 0xc040955f  Kernel::Process::sys$sigaction(int, sigaction const*, sigaction*) +0x40f
[#0 H(53:53)]: 0xc0371ae3  syscall_handler +0x1f0e
[#0 H(53:53)]: 0xc036fb9d  syscall_asm_entry +0x31
[#0 H(53:53)]: KUBSAN: addition of unsigned offset to 0xffffffff overflowed to 0x00000007
[#0 H(53:53)]: KUBSAN: at ../Kernel/Syscalls/sigaction.cpp, line 78, column: 26
[#0 H(53:53)]: 0xc0486161  print_location +0x225
[#0 H(53:53)]: 0xc04880c7  __ubsan_handle_pointer_overflow +0x178
[#0 H(53:53)]: 0xc0409579  Kernel::Process::sys$sigaction(int, sigaction const*, sigaction*) +0x429
[#0 H(53:53)]: 0xc0371ae3  syscall_handler +0x1f0e
[#0 H(53:53)]: 0xc036fb9d  syscall_asm_entry +0x31
[H(53:53)]: CPU[0] NP(error) fault at invalid address V0x00000007
[#0 H(53:53)]: copy_to_user(0x00000007, 0xc58b1b88, 4) failed at V0x00000007
```

**Comment by BenWiederhake** [comment] 2021-03-02 18:22
I cannot reproduce this. It was probably fixed in 6a6eb8844a79e317aa87de8c8200b7feb47f8ff9.

**Closed** 2021-03-09 00:35 UTC
Labels: bug
