### ISSUE TITLE
LibAudio: Wave playback is distorted if host audio uses sample rate that is not 44100

### ISSUE THREAD

**Issue by ncmiller** [SerenityOS/serenity#7957] opened 2021-06-09 18:52 UTC
When playing [this Wave file](https://www.learningcontainer.com/download/wav-file-sample/) in SerenityOS, the playback is slightly faster and a major step higher than it should be.

This appears to be an issue with playback of any Wave file (not just the one linked above).

**Comment by ncmiller** [comment] 2021-06-10 23:16
I suspected this might be due to resampling, so I created different versions of the same file at different sample rates: 8000, 44100, 48000, 96000. 

However, testing showed that they all exhibit the same the same pitch problem (major step too high).

**Comment by ncmiller** [comment] 2021-06-12 19:24
I'm pretty sure this is happening to me because my host audio has a sample rate of 48000, and the WavLoader is setting the target sample rate to 44100.

I think this should be fixable in qemu settings somehow.

**Comment by TobyAsE** [comment] 2021-09-10 22:16
@kleinesfilmroellchen I think I remember reading about this issue in discord and that you fixed it. Is that correct?

**Comment by kleinesfilmroellchen** [comment] 2021-09-10 22:19
It should be fixed, yes, but my tests were all with FLACs, so I'll try reproducing tomorrow.

**Comment by kleinesfilmroellchen** [comment] 2021-09-12 08:42
Seems to be fixed on master, at least when using even lower sample rates (e.g. 44.1k with 8k system sample rate). I think we can close it then.

**Comment by TobyAsE** [comment] 2021-09-12 11:10
I'll close this issue then.
If you @ncmiller think this is wrong, feel free to re-open it.

**Closed by TobyAsE** 2021-09-12 11:10 UTC
