### ISSUE TITLE
LibJS: m_has_value verification failure in Op::GetObjectPropertyIterator on goodeats.io

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#23734] opened 2024-03-26 23:40 UTC
For example, for the menu for Sheffield Plate: https://goodeats.io/mamsp/all
```
VERIFICATION FAILED: m_has_value at /home/lukew/Desktop/serenity-project/serenity/Meta/Lagom/../../AK/Optional.h:215
/home/lukew/Desktop/serenity-project/serenity/Build/lagom/lib/liblagom-ak.so.0(ak_verification_failed+0xef) [0x7379790c6f5f]
/home/lukew/Desktop/serenity-project/serenity/Build/lagom/lib/liblagom-js.so.0(+0x2772f8) [0x737976c772f8]
/home/lukew/Desktop/serenity-project/serenity/Build/lagom/lib/liblagom-js.so.0 JS::Bytecode::Op::GetObjectPropertyIterator::execute_impl(JS::Bytecode::Interpreter&) const 0x9c) [0x737976c6db7c]
/home/lukew/Desktop/serenity-project/serenity/Build/lagom/lib/liblagom-js.so.0 JS::Bytecode::Interpreter::run_bytecode() 0x640) [0x737976c53b70]
/home/lukew/Desktop/serenity-project/serenity/Build/lagom/lib/liblagom-js.so.0 JS::Bytecode::Interpreter::run_and_return_frame(JS::Bytecode::Executable&, JS::Bytecode::BasicBlock const*, JS::Bytecode::CallFrame*) 0x22f) [0x737976c5301f]
/home/lukew/Desktop/serenity-project/serenity/Build/lagom/lib/liblagom-js.so.0 JS::ECMAScriptFunctionObject::ordinary_call_evaluate_body() 0x989) [0x737976d857f9]
/home/lukew/Desktop/serenity-project/serenity/Build/lagom/lib/liblagom-js.so.0 JS::ECMAScriptFunctionObject::internal_call(JS::Value, AK::Span<JS::Value const>) 0x16d) [0x737976d847ad]
/home/lukew/Desktop/serenity-project/serenity/Build/lagom/lib/liblagom-js.so.0 JS::call_impl(JS::VM&, JS::FunctionObject&, JS::Value, AK::Span<JS::Value const>) 0x1e) [0x737976cf76be]
```

**Comment by ADKaster** [comment] 2024-03-27 00:05
@Hendiadyoin1 @DanShaders

**Comment by ADKaster** [comment] 2024-03-27 00:06
Wait, I misread, sorry for pings. Thought this was about the new BigInteger stuff 😅

**Comment by awesomekling** [comment] 2024-03-27 07:00
Dupe of #22973

**Closed by awesomekling** 2024-03-27 07:00 UTC
Labels: bug, web compatibility, has-repro
