### ISSUE TITLE
Termninal Crashes When Resizing Window

### ISSUE THREAD

**Issue by Imalaia3** [SerenityOS/serenity#9956] opened 2021-09-11 07:47 UTC
When you type something in the Terminal like "hello" and resize the window to minimum size the Terminal crashes.

Abort Signal (6)
Terminal Output: ASSERTION FAILED: TODO ../../Userland/Libraries/LibLine/Editor

**Comment by alimpfard** [comment] 2021-09-11 07:54
dupe of #7296.

**Closed by alimpfard** 2021-09-11 07:54 UTC
