### ISSUE TITLE
Piano: Crash on setting notes in the bottom row while they being played

### ISSUE THREAD

**Issue by xTibor** [SerenityOS/serenity#1158] opened 2020-02-01 19:25 UTC
**Reproduction:**

1. Scroll the piano roll down to the bottom
2. Choose any cell from the bottom row and wait until it's column getting highlighted
3. Start clicking mindlessly on the cell

**Stacktrace:**

```
USERSPACE(23) ASSERTION FAILED: note >= 0 && note < note_count
AudioEngine.cpp:151 in void AudioEngine::set_note(int, Music::Switch)

0xdeadc0de  Thread::die_if_needed() +120
0xdeadc0de  syscall_handler +926
0xdeadc0de  syscall_asm_entry +28
0x080b0680  raise +22
0x08048320  abort +13
0x080b0608  kill +0
0x08049372  AudioEngine::set_note(int, Music::Switch) +186
0x0804a9b1  RollWidget::mousedown_event(GMouseEvent&) +291
0x0804f01d  GWidget::handle_mousedown_event(GMouseEvent&) +49
0x0808d33a  CObject::dispatch_event(CEvent&, CObject*) +86
0x0806937d  GWindow::event(CEvent&) +891
0x0808d33a  CObject::dispatch_event(CEvent&, CObject*) +86
0x0808f02a  CEventLoop::pump(CEventLoop::WaitMode) +502
0x0808f1e9  CEventLoop::exec() +71
0x0805fc31  GApplication::exec() +29
0x0804886e  main +1099
0x08048fc3  _start +94
```

**Comment by willmcpherson2** [comment] 2020-02-02 03:23
I can't seem to reproduce this no matter how much I click on the playing column.
I know that this line is responsible:
https://github.com/SerenityOS/serenity/blob/117820f6100754b391cb108b6fb2428e03ce2d87/Applications/Piano/RollWidget.cpp#L130

**Comment by xTibor** [comment] 2020-02-02 03:37
https://streamable.com/whaoc

**Comment by willmcpherson2** [comment] 2020-02-02 04:52
Ok, this seems to be caused by certain window sizes causing an extra row of notes to be drawn, so we can probably blame this function:
https://github.com/SerenityOS/serenity/blob/117820f6100754b391cb108b6fb2428e03ce2d87/Applications/Piano/RollWidget.cpp#L53
I should be able to fix this easily
Thanks for the information @xTibor

**Comment by willmcpherson2** [comment] 2021-03-02 12:13
I can no longer reproduce this. I can make the scrollbar momentarily draw at the wrong size, but `RollWidget::paint_event` will always give the correct number of [`notes_to_paint`](https://github.com/SerenityOS/serenity/blob/17e6287333517d98189596b169e7a10c184424b0/Userland/Applications/Piano/RollWidget.cpp#L80).

This could be due to my laggy emulator, so if someone could test with KVM that would be much appreciated.

**Comment by kleinesfilmroellchen** [comment] 2022-03-15 12:38
I haven't seen this, like, ever, so I'm closing this.

**Closed by kleinesfilmroellchen** 2022-03-15 12:38 UTC
Labels: bug
