### ISSUE TITLE
LibWeb: Background painted in wrong position on mozilla.com

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#22401] opened 2023-12-23 09:05 UTC
This looks wonky on https://mozilla.com/

![image](https://github.com/SerenityOS/serenity/assets/5954907/b6801a7a-8362-49d3-b40a-bca2705523bc)

Simplified reduction:
```html
<!DOCTYPE html><style>
    body {
        background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAIAAAAlC+aJAAAAUElEQVRo3u3PQQ0AMAgEsGP+xeEIVOxB0jpodSaXvRwnICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg8N8ChgACTxD8p8QAAAAASUVORK5CYII=);
        background-position: left 50vw center;
        background-repeat: no-repeat;
        background-size: 64px 64px;
    }
</style><body>whf
```

**Comment by awesomekling** [comment] 2024-01-01 10:39
Another instance of this bug is Wikipedia "external links" sections:

![image](https://github.com/SerenityOS/serenity/assets/5954907/22b1ba23-8de0-4ed7-bab8-9bdeb00966a1)

Reduction:
```html
<!DOCTYPE html><style>
    span {
        background-image: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMiIgaGVpZ2h0PSIxMiIgdmlld0JveD0iMCAwIDEyIDEyIj4KCTx0aXRsZT4KCQlleHRlcm5hbCBsaW5rCgk8L3RpdGxlPgoJPHBhdGggZmlsbD0iIzM2YyIgZD0iTTYgMWg1djVMOC44NiAzLjg1IDQuNyA4IDQgNy4zbDQuMTUtNC4xNkw2IDFaTTIgM2gydjFIMnY2aDZWOGgxdjJhMSAxIDAgMCAxLTEgMUgyYTEgMSAwIDAgMS0xLTFWNGExIDEgMCAwIDEgMS0xWiIvPgo8L3N2Zz4K);
        background-position: center right;
        background-repeat: no-repeat;
        background-size: 0.857em;
        padding-right: 1em;
    }
</style><body><span>text
```

**Comment by AtkinsSJ** [comment] 2024-01-01 11:16
From the logs:
```
2060.856 WebContent(22397): Unable to parse value for CSS property 'background-position'.
2060.856 WebContent(22397): Dumping all tokens:
2060.856 WebContent(22397):    Token: Ident: center
2060.856 WebContent(22397):    Token: Whitespace
2060.856 WebContent(22397):    Token: Ident: right
```
So, that's my bad. :sweat_smile: I thought there were tests covering this.

**Comment by shannonbooth** [comment] 2024-01-03 08:43
I've looked into this somewhat, and now partially the problem. Here's a patch that fixes the issue:

```patch
diff --git a/Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp b/Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
index da9ad26042..70ffed7190 100644
--- a/Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
+++ b/Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
@@ -2874,8 +2874,8 @@ RefPtr<StyleValue> Parser::parse_comma_separated_value_list(TokenStream<Componen
     values.append(first.release_nonnull());
 
     while (tokens.has_next_token()) {
-        if (!tokens.next_token().is(Token::Type::Comma))
-            return nullptr;
+        if (tokens.peek_token().is(Token::Type::Comma))
+            tokens.next_token();
 
         if (auto maybe_value = parse_one_value(tokens)) {
             values.append(maybe_value.release_nonnull());
```

What seems to be happening is that `parse_comma_separated_value_list` assumes that it is passed through a stream that only consists of commas and values, but not whitespace.

I'm currently trying to understand how this would have _used_ to work since it's marked as a regression (and how / when it broke), but am I correct in suspecting that this function should handle whitespace as well?

(note that the patch isn't explicitly looking for whitespace token since that is stripped by the caller `Parser::parse_css_value`)

**Comment by shannonbooth** [comment] 2024-01-06 03:56
#22611 fixes the ` background-position: center right;` case

I believe I have a fix for the `background-position: left 50vw center;` case locally, and mozilla.com renders fine now:

![image](https://github.com/SerenityOS/serenity/assets/35911232/87635743-3760-4832-9bde-bac7aeb5d21b)

Interestingly, the simplified reproduction _doesn't_ render fine.

Ladybird:
![image](https://github.com/SerenityOS/serenity/assets/35911232/f71c87ab-8518-4b2f-a76a-8f72ad5b398a)

Firefox:
![image](https://github.com/SerenityOS/serenity/assets/35911232/ebb65254-68df-4b34-b6cc-2db4dd60b932)

I may be misunderstanding something here (or done something wrong with my fix), but I suspect that this one may be a layout issue

**Closed** 2024-01-10 22:27 UTC
Labels: bug, regression, spec compliance, web compatibility
