### ISSUE TITLE
TextEditor: Crash when closing a markdown document

### ISSUE THREAD

**Issue by sk-spr** [SerenityOS/serenity#15025] opened 2022-08-25 20:29 UTC
When closing any .md document in TextEditor (with preview enabled as is default), including empty documents, a crash appears to occur. This is the backtrace provided by Crash Reporter. From the backtrace, this appears to be a LibWeb-related problem.
```
==== Thread #0 (TID 85) ====
NotPresent fault on Read at address 0xedededed

0x98165e2c: [/usr/lib/libweb.so.serenity] Web::HTML::EventLoop::unregister_environment_settings_object(AK::Badge<Web::HTML::EnvironmentSettingsObject>, Web::HTML::EnvironmentSettingsObject&) +0x3c (Vector.h:421 => Vector.h:422 => EventLoop.cpp:366)
0x981e985d: [/usr/lib/libweb.so.serenity] Web::HTML::EnvironmentSettingsObject::~EnvironmentSettingsObject() +0x4d (Environments.cpp:28)
0x981ed4af: [/usr/lib/libweb.so.serenity] Web::HTML::WindowEnvironmentSettingsObject::~WindowEnvironmentSettingsObject() +0x3f (WindowEnvironmentSettingsObject.h:18)
0x34e11d05: [/usr/lib/libjs.so.serenity] JS::Realm::~Realm() +0xd5 (OwnPtr.h:108 => OwnPtr.h:44 => Realm.h:18)
0x34be336f: [/usr/lib/libjs.so.serenity] JS::HeapBlock::deallocate(JS::Cell*) +0x7f (HeapBlock.cpp:49)
0x34be09df: [/usr/lib/libjs.so.serenity] auto JS::Heap::sweep_dead_cells(bool, Core::ElapsedTimer const&)::{lambda(auto:1&)#1}::operator()<JS::HeapBlock>(JS::HeapBlock&) const +0x10f (Heap.cpp:237 => HeapBlock.h:65 => HeapBlock.h:57 => HeapBlock.h:63)
0x34be0bdb: [/usr/lib/libjs.so.serenity] JS::Heap::sweep_dead_cells(bool, Core::ElapsedTimer const&) +0x16b (CellAllocator.h:29 => Heap.h:96 => Heap.cpp:231)
0x34be1a2e: [/usr/lib/libjs.so.serenity] JS::Heap::collect_garbage(JS::Heap::CollectionType, bool) [clone .localalias] +0xee (Heap.cpp:105)
0x34be1c76: [/usr/lib/libjs.so.serenity] JS::Heap::~Heap() +0x36 (Heap.cpp:57)
0x97fdae92: [/usr/lib/libweb.so.serenity] JS::VM::~VM() +0x372 (VM.h:40)
0x97fd52b8: [/usr/lib/libweb.so.serenity] AK::RefPtr<JS::VM>::~RefPtr() +0x38 (RefCounted.h:66 => RefCounted.h:58 => NonnullRefPtr.h:35 => RefPtr.h:216 => RefPtr.h:102)
0x01a33a69: [/usr/lib/libc.so] __cxa_finalize +0xd9 (cxxabi.cpp:152)
0x01a5ea38: [/usr/lib/libc.so] exit +0x18 (stdlib.cpp:189)
0x42a29fee: [/bin/WebContent] _entry +0x4e (crt0.cpp:45)
```

**Comment by MacDue** [comment] 2022-09-04 15:46
This seems to be a duplicate of #14804

**Closed** 2022-09-04 15:47 UTC
Labels: duplicate

**Comment by sk-spr** [comment] 2022-09-05 11:42
It does, my bad.
