### ISSUE TITLE
WebContent (PID 99) has crashed - Segmentation violation (signal 11)

### ISSUE THREAD

**Issue by djwisdom** [SerenityOS/serenity#14804] opened 2022-08-08 10:02 UTC
![99_Screenshot](https://user-images.githubusercontent.com/391659/183392640-06c089e7-1aee-427d-8227-4fe57f5905d1.png)
[99_WebContent_backtrace.txt](https://github.com/SerenityOS/serenity/files/9280822/99_WebContent_backtrace.txt)
[99_CPU_Registers.txt](https://github.com/SerenityOS/serenity/files/9280823/99_CPU_Registers.txt)
[99_Memory_Regions.txt](https://github.com/SerenityOS/serenity/files/9280824/99_Memory_Regions.txt)

I tried searching issues if there already exists similar ticket, seeing that none yet was submitted (afaik) I'm endorsing this one.

**Comment by ADKaster** [comment] 2022-08-08 17:00
What website were you visiting when you hit this crash? Looks like there might be an object there that was garbage collected while it was still alive

**Comment by djwisdom** [comment] 2022-08-08 21:23
github. com

**Comment by stendavid** [comment] 2022-08-08 22:03
I got the same error from just opening and closing HackStudio

**Comment by stendavid** [comment] 2022-08-09 08:48
Fwiw, I tried debugging it. It looked like something with the order of destruction of Web::HTML:EventLoop and objects that reference it, but the details went way over my head :)

**Comment by clarking** [comment] 2022-08-10 10:19
![serenity_fail](https://user-images.githubusercontent.com/8283993/183877551-0e4a46b8-37cf-4a17-b9ec-3a6ba16024b8.png)
same here, but my build also fails to write the core dump. it happens when i close HackStudio

**Comment by AtkinsSJ** [comment] 2022-08-13 13:40
I think I've found the simplest repro for this:

1. Run `br foobarbaz`
2. Close Browser

It fails to load, but the UI never updates to say there was an error, and the statusbar just shows "Loading foobarbaz" forever. Here's the logs at that point:
```
265.411 WebContent(78:78): ResourceLoader: Starting load of: "http://foobarbaz/"
265.439 LookupServer(19:19): LookupServer: Question count (0 vs 1) :(
265.443 LookupServer(19:19): Received response from '1.1.1.1' but no result(s), trying next nameserver
265.486 LookupServer(19:19): LookupServer: Question count (0 vs 1) :(
265.490 LookupServer(19:19): Received response from '1.0.0.1' but no result(s), trying next nameserver
265.490 LookupServer(19:19): Tried all nameservers but never got a response :(
265.490 RequestServer(80:80): ConnectionCache: Connection to http://foobarbaz/ failed: name server returned permanent failure
265.494 RequestServer(80:80): Request with a null socket finished for URL http://foobarbaz/
265.502 WebContent(78:78): ResourceLoader: Starting load of: "http://foobarbaz/favicon.ico"
265.542 LookupServer(19:19): LookupServer: Question count (0 vs 1) :(
265.542 LookupServer(19:19): Received response from '1.1.1.1' but no result(s), trying next nameserver
265.613 LookupServer(19:19): LookupServer: Question count (0 vs 1) :(
265.613 LookupServer(19:19): Received response from '1.0.0.1' but no result(s), trying next nameserver
265.613 LookupServer(19:19): Tried all nameservers but never got a response :(
265.613 RequestServer(80:80): ConnectionCache: Connection to http://foobarbaz/favicon.ico failed: name server returned permanent failure
265.613 RequestServer(80:80): Request with a null socket finished for URL http://foobarbaz/favicon.ico
265.680 WebContent(78:78): ResourceLoader: Failed load of: "http://foobarbaz/", Error: Load failed, Duration: 273ms
265.680 WebContent(78:78): ResourceLoader: Starting load of: "file:///res/html/error.html"
265.680 WebContent(78:78): ResourceLoader: Failed load of: "http://foobarbaz/favicon.ico", Error: Load failed, Duration: 178ms
```

**Comment by crpz1** [comment] 2022-08-21 11:39
This also occurs in Mail.

My backtraces are the same except they also contain `NotPresent fault on Read at address 0xedededed`

**Comment by paulie-g** [comment] 2022-08-22 11:06
Same here. Simplest (imho) steps to reproduce:

1. Open Text Editor
2. Select 'View->Markdown Preview'
3. Close/Exit
```
NotPresent fault on Read at address 0xedededed

0x66b08cac: [/usr/lib/libweb.so.serenity] Web::HTML::EventLoop::unregister_environment_settings_object(AK::Badge<Web::HTML::EnvironmentSettingsObject>, Web::HTML::EnvironmentSettingsObject&) +0x3c (Vector.h:421 => Vector.h:422 => EventLoop.cpp:366)
0x66b8c79d: [/usr/lib/libweb.so.serenity] Web::HTML::EnvironmentSettingsObject::~EnvironmentSettingsObject() +0x4d (Environments.cpp:28)
0x66b9041f: [/usr/lib/libweb.so.serenity] Web::HTML::WindowEnvironmentSettingsObject::~WindowEnvironmentSettingsObject() +0x3f (WindowEnvironmentSettingsObject.h:18)
0x0520a4f5: [/usr/lib/libjs.so.serenity] JS::Realm::~Realm() +0xd5 (OwnPtr.h:108 => OwnPtr.h:44 => Realm.h:18)
0x04fe51af: [/usr/lib/libjs.so.serenity] JS::HeapBlock::deallocate(JS::Cell*) +0x7f (HeapBlock.cpp:49)
0x04fe281f: [/usr/lib/libjs.so.serenity] auto JS::Heap::sweep_dead_cells(bool, Core::ElapsedTimer const&)::{lambda(auto:1&)#1}::operator()<JS::HeapBlock>(JS::HeapBlock&) const +0x10f (Heap.cpp:237 => HeapBlock.h:65 => HeapBlock.h:57 => HeapBlock.h:63)
0x04fe2a1b: [/usr/lib/libjs.so.serenity] JS::Heap::sweep_dead_cells(bool, Core::ElapsedTimer const&) +0x16b (CellAllocator.h:29 => Heap.h:96 => Heap.cpp:231)
0x04fe386e: [/usr/lib/libjs.so.serenity] JS::Heap::collect_garbage(JS::Heap::CollectionType, bool) +0xee (Heap.cpp:105)
0x04fe3ab6: [/usr/lib/libjs.so.serenity] JS::Heap::~Heap() +0x36 (Heap.cpp:57)
0x669868e2: [/usr/lib/libweb.so.serenity] JS::VM::~VM() +0x372 (VM.h:40)
0x66980d08: [/usr/lib/libweb.so.serenity] AK::RefPtr<JS::VM>::~RefPtr() +0x38 (RefCounted.h:66 => RefCounted.h:58 => NonnullRefPtr.h:35 => RefPtr.h:216 => RefPtr.h:102)
0x3f712a59: [/usr/lib/libc.so] __cxa_finalize +0xd9 (cxxabi.cpp:152)
0x3f73da38: [/usr/lib/libc.so] exit +0x18 (stdlib.cpp:189)
0xa4de1ffe: [/bin/WebContent] _entry +0x4e (crt0.cpp:45)
```

**Comment by alat-rights** [comment] 2023-02-16 08:49
Likely same issue: 
<img width="790" alt="image" src="https://user-images.githubusercontent.com/54920181/219314478-9d5c985a-2565-4b89-a686-3ce0abcc89d8.png">

**Comment by awesomekling** [comment] 2023-10-24 13:16
Haven't seen this particular stack trace in forever. Closing as this bug is not really actionable.

**Closed by awesomekling** 2023-10-24 13:16 UTC
Labels: bug
