### ISSUE TITLE
LibJS: Array.prototype.slice is not generic

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#6206] opened 2021-04-09 23:33 UTC
Array.prototype.slice is generic according to spec: `The slice function is intentionally generic; it does not require that its this value be an Array object. Therefore it can be transferred to other kinds of objects for use as a method.`

This is required by jQuery:
```
WebContent(29): Throwing JavaScript exception: [TypeError] Not an Array object
WebContent(29):   slice at jquery-1.7.1.js:224:20
WebContent(29):   call at jquery-1.7.1.js:224:20
WebContent(29):   toArray at jquery-1.7.1.js:224:20
WebContent(29):   get at jquery-1.7.1.js:233:16
WebContent(29):   initPage at init.js:101:64
WebContent(29):   init at init.js:48:18
WebContent(29):   <anonymous> at init.js:704:10
WebContent(29):   apply at jquery-1.7.1.js:1046:35
WebContent(29):   fire at jquery-1.7.1.js:1046:35
WebContent(29):   fireWith at jquery-1.7.1.js:1164:11
WebContent(29):   ready at jquery-1.7.1.js:435:22
WebContent(29):   DOMContentLoaded at jquery-1.7.1.js:923:15
```

**Comment by linusg** [comment] 2021-04-10 10:51
Duplicate of #2329.

**Closed by linusg** 2021-04-10 10:51 UTC
