### ISSUE TITLE
QEMU Q35 ACPI tables might need special handle if overlapping two physical pages

### ISSUE THREAD

**Issue by supercomputer7** [SerenityOS/serenity#6948] opened 2021-05-08 12:23 UTC
Testing latest changes from master on qemu Q35 machine type, boot process halts at this stage:
```
[Kernel]: ACPI: Using RSDP @ P0x000f5a90
[Kernel]: ACPI: Main Description Table valid? true
[Kernel]: ACPI: Using RSDT, enumerating tables @ P0x1ffe21ac
[Kernel]: ACPI: RSDT revision 1, total length: 56
[Kernel]: ACPI: Initializing Fixed ACPI data
[Kernel]: ACPI: Searching for the Fixed ACPI Data Table
[Kernel]: ACPI: Fixed ACPI data, Revision 3, length: 244 bytes
[Kernel]: ACPI: DSDT P0x1ffe0040
[#0 Kernel]: KUBSAN: member call on null pointer of type 'struct Thread'
[#0 Kernel]: KUBSAN: at ../Kernel/Arch/i386/CPU.cpp, line 280, column: 51
[#0 Kernel]: 0xc04ed2da (next: 0xc0107ef4)
[#0 Kernel]: 0xc04ef14a (next: 0xc0107f74)
[#0 Kernel]: 0xc0573f39 (next: 0xc0108034)
[#0 Kernel]: 0xc056a9b0 (next: 0xc0108108)
[#0 Kernel]: 0xc06138de (next: 0xc0108128)
[#0 Kernel]: 0xc0613c50 (next: 0xc0108178)
[#0 Kernel]: 0xc060d0b5 (next: 0xc01081e8)
[#0 Kernel]: 0xc060d2f9 (next: 0xc0108238)
[#0 Kernel]: 0xc0663815 (next: 0xc0108298)
[#0 Kernel]: 0xc0100145 (next: 0x00000000)
[Kernel]: KERNEL PANIC! :^(
[Kernel]: UB is configured to be deadly.
[Kernel]: at ../Kernel/UBSanitizer.cpp:28 in void print_location(const Kernel::UBSanitizer::SourceLocation&)
[#0 Kernel]: 0xc036c708 (next: 0xc0107e54)
[#0 Kernel]: 0xc04ed34c (next: 0xc0107ef4)
[#0 Kernel]: 0xc04ef14a (next: 0xc0107f74)
[#0 Kernel]: 0xc0573f39 (next: 0xc0108034)
[#0 Kernel]: 0xc056a9b0 (next: 0xc0108108)
[#0 Kernel]: 0xc06138de (next: 0xc0108128)
[#0 Kernel]: 0xc0613c50 (next: 0xc0108178)
[#0 Kernel]: 0xc060d0b5 (next: 0xc01081e8)
[#0 Kernel]: 0xc060d2f9 (next: 0xc0108238)
[#0 Kernel]: 0xc0663815 (next: 0xc0108298)
[#0 Kernel]: 0xc0100145 (next: 0x00000000)
```

**Comment by bcoles** [comment] 2021-05-08 12:26
Possible dupe of https://github.com/SerenityOS/serenity/issues/6154#issuecomment-835290762

**Closed** 2021-07-02 11:16 UTC
Labels: bug, regression
