### ISSUE TITLE
Kernel: system freeze failed assertion connecting to closed port: current_mode != Mode::Unlocked

### ISSUE THREAD

**Issue by bcoles** [SerenityOS/serenity#4948] opened 2021-01-14 14:40 UTC
Reproduce:

* `nc 127.0.0.1 1234` (where `1234` is a closed TCP port)
* CTRL+C

Log:

```
[nc(28:28)]: Terminating nc(28) due to signal 2
[nc(28:28)]: ASSERTION FAILED: current_mode != Mode::Unlocked
../Kernel/Lock.cpp:150 in void Kernel::Lock::unlock()
[nc(28:28)]: 0xc011939e  __assertion_failed(char const*, char const*, unsigned int, char const*) +0xe2
[nc(28:28)]: 0xc016584f  Kernel::Lock::unlock() +0x9d
[nc(28:28)]: 0xc01766f1  Kernel::TCPSocket::protocol_connect(Kernel::FileDescription&, Kernel::ShouldBlock) +0x273
[nc(28:28)]: 0xc0167ff7  Kernel::IPv4Socket::connect(Kernel::FileDescription&, AK::Userspace<sockaddr const*>, unsigned int, Kernel::ShouldBlock) +0xb9
[nc(28:28)]: 0xc01a020c  Kernel::Process::sys$connect(int, AK::Userspace<sockaddr const*>, unsigned int) +0x162
[nc(28:28)]: 0xc01880c8  syscall_handler +0x6be
[nc(28:28)]: 0xc0187a02  syscall_asm_entry +0x31
```

**Comment by tomuta** [comment] 2021-01-14 16:32
Not sure how that assertion can possibly fail there...

**Comment by tomuta** [comment] 2021-01-15 02:09
Closing as a duplicate of #4352

**Closed by tomuta** 2021-01-15 02:09 UTC
Labels: bug
