### ISSUE TITLE
Cursor keeps blinking even when window is blocked by a modal dialog

### ISSUE THREAD

**Issue by tomuta** [SerenityOS/serenity#5301] opened 2021-02-12 04:10 UTC
Seems like we fixed this recently and the issue came back?

Steps to reproduce:
1. Open TextEditor
2. Click Open button
3. The cursor continues to blink

**Comment by linusg** [comment] 2021-03-20 19:07
To add some additional info, this doesn't seem to happen for modals opened via the menu (`Text Edior -> {New,Open...}` / `View -> Editor font...`), only when opening them via the toolbar or keyboard shortcuts. [Relevant IRC log.](https://freenode.logbot.info/serenityos/20210101#c6372724-c6372819)

**Comment by LucasChollet** [comment] 2022-04-30 15:38
Can be closed as I'm unable to reproduce this issue!

**Closed** 2022-04-30 16:04 UTC
Labels: bug, regression
