### ISSUE TITLE
HackStudio: Regular assertion failure in ClassViewWidget

### ISSUE THREAD

**Issue by MaxWipfli** [SerenityOS/serenity#7751] opened 2021-06-03 21:34 UTC
When e.g. opening `/usr/src/serenity/AK` in HackStudio and then opening `Base64.cpp` (that's what I tested with), an asseration in ClassViewWidget fails.

Here's the debug output:
```
HackStudio(31:31): USERSPACE(31) ASSERTION FAILED: child.declaration
../../Userland/DevTools/HackStudio/ClassViewWidget.cpp:150
CrashDaemon(20:20): New coredump file: /tmp/coredump/HackStudio_31_1622755912
CrashDaemon(20:20): --- Backtrace for thread #0 (TID 31) ---
CrashDaemon(20:20): 0xa3b3f1ce: [libsystem.so] syscall2 +0xe (syscall.cpp:25)
CrashDaemon(20:20): 0x84e8c135: [libc.so] raise +0x25 (signal.cpp:21)
CrashDaemon(20:20): 0x84e752a6: [libc.so] abort +0x2a (stdlib.cpp:233)
CrashDaemon(20:20): 0x84e75e0b: [libc.so] __assertion_failed +0xeb (Format.h:236)
CrashDaemon(20:20): 0x8c8c669f: [/bin/HackStudio] HackStudio::ClassViewModel::add_declaration(GUI::AutocompleteProvider::Declaration const&) [clone .localalias] +0x3cf (ClassViewWidget.cpp:150)
CrashDaemon(20:20): 0x8c8c69a3: [/bin/HackStudio] HackStudio::ClassViewModel::ClassViewModel() [clone .localalias] +0xb3 (ClassViewWidget.cpp:108)
CrashDaemon(20:20): 0x8c8c6a36: [/bin/HackStudio] HackStudio::ClassViewModel::create() [clone .localalias] +0x36 (Atomic.h:147)
CrashDaemon(20:20): 0x8c8c6b6d: [/bin/HackStudio] HackStudio::ClassViewWidget::refresh() +0x3d (Atomic.h:246)
CrashDaemon(20:20): 0x8c9060cc: [/bin/HackStudio] AK::Function<void ()>::CallableWrapper<HackStudio::HackStudioWidget::create_project_tab(GUI::Widget&)::{lambda()#1}>::call() const +0x2c (Function.h:147)
CrashDaemon(20:20): 0x8c9241ef: [/bin/HackStudio] HackStudio::ProjectDeclarations::set_declared_symbols(AK::String const&, AK::Vector<GUI::AutocompleteProvider::Declaration, 0ul> const&) +0xa5f (Function.h:79)
CrashDaemon(20:20): 0x8c9186f6: [/bin/HackStudio] non-virtual thunk to HackStudio::ServerConnection::declarations_in_document(AK::String const&, AK::Vector<GUI::AutocompleteProvider::Declaration, 0ul> const&) [clone .localalias] +0x26 (LanguageClient.cpp:99)
CrashDaemon(20:20): 0x8c8f1991: [/bin/HackStudio] IPC::Connection<LanguageClientEndpoint, LanguageServerEndpoint>::handle_messages() +0x601 (OwnPtr.h:17)
CrashDaemon(20:20): 0x8c8f3c43: [/bin/HackStudio] AK::Function<void ()>::CallableWrapper<IPC::Connection<LanguageClientEndpoint, LanguageServerEndpoint>::Connection(LanguageClientStub&, AK::NonnullRefPtr<Core::LocalSocket>)::{lambda()#2}>::call() const +0x63 (Atomic.h:246)
CrashDaemon(20:20): 0x2200e933: [libcore.so] Core::Notifier::event(Core::Event&) +0x93 (Atomic.h:206)
CrashDaemon(20:20): 0x2200fbce: [libcore.so] Core::Object::dispatch_event(Core::Event&, Core::Object*) +0x7e (Object.h:113)
CrashDaemon(20:20): 0x21ff6693: [libcore.so] Core::EventLoop::pump(Core::EventLoop::WaitMode) [clone .localalias] +0x4f3 (Atomic.h:246)
CrashDaemon(20:20): 0x21ff6e7b: [libcore.so] Core::EventLoop::exec() +0x5b (EventLoop.cpp:362)
CrashDaemon(20:20): 0xb408b0a8: [libgui.so] GUI::Application::exec() +0x28 (Application.cpp:106)
CrashDaemon(20:20): 0x8c8c4780: [/bin/HackStudio] main +0x780 (NonnullRefPtr.h:276)
CrashDaemon(20:20): 0x8c8c4db8: [/bin/HackStudio] _start +0x58 (crt0.cpp:39)
```

**Comment by bcoles** [comment] 2021-06-04 03:23
Dupe of #7702

**Closed** 2021-06-04 06:17 UTC
Labels: duplicate
