### ISSUE TITLE
Kernel: There may be no physical pages left even after purging

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#3389] opened 2020-09-02 15:43 UTC
I got this with ```allocate 211```. Trace:
```
[allocate(23:23)]: kmalloc(): Adding memory to heap at V0xc0801000, bytes: 1048576
[allocate(23:23)]: MM: Purge saved the day! Purged 16 pages from PurgeableVMObject{0xc044a398}
[allocate(23:23)]: MM: Purge saved the day! Purged 16 pages from PurgeableVMObject{0xc0462d38}
[allocate(23:23)]: MM: Purge saved the day! Purged 16 pages from PurgeableVMObject{0xc0462df8}
[allocate(23:23)]: MM: Purge saved the day! Purged 16 pages from PurgeableVMObject{0xc0482098}
[allocate(23:23)]: MM: Purge saved the day! Purged 16 pages from PurgeableVMObject{0xc0478af8}
[allocate(23:23)]: MM: Purge saved the day! Purged 16 pages from PurgeableVMObject{0xc046a538}
[allocate(23:23)]: MM: Purge saved the day! Purged 9 pages from PurgeableVMObject{0xc04b29d8}
[allocate(23:23)]: MM: Purge saved the day! Purged 16 pages from PurgeableVMObject{0xc0475958}
[allocate(23:23)]: MM: Purge saved the day! Purged 16 pages from PurgeableVMObject{0xc04c8818}
[ResourceGraph.MenuApplet(12:12)]: MM: Purge saved the day! Purged 9 pages from PurgeableVMObject{0xc04c88d8}
[Taskbar(20:20)]: MM: Purge saved the day! Purged 16 pages from PurgeableVMObject{0xc04c8f38}
[Taskbar(20:20)]: MM: Purge saved the day! Purged 16 pages from PurgeableVMObject{0xc04c8b18}
[Taskbar(24:24)]: MM: Purge saved the day! Purged 16 pages from PurgeableVMObject{0xc04cd1f8}
[Taskbar(24:24)]: ASSERTION FAILED: page
../Kernel/VM/MemoryManager.cpp:513 in Kernel::MemoryManager::allocate_user_physical_page(Kernel::MemoryManager::ShouldZeroFill, bool*)::<lambda(auto:9&)> [with auto:9 = Kernel::PurgeableVMObject]
[Taskbar(24:24)]: MM: Purge saved the day! Purged 9 pages from PurgeableVMObject{0xc04d1bb8}
[Taskbar(24:24)]: 0xc011e9b7  __assertion_failed(char const*, char const*, unsigned int, char const*) +185
[Taskbar(24:24)]: 0xc018a248  Kernel::MemoryManager::allocate_user_physical_page(Kernel::MemoryManager::ShouldZeroFill, bool*) +486
[Taskbar(24:24)]: 0xc018ea98  Kernel::Region::handle_zero_fault(unsigned long) +248
[Taskbar(24:24)]: 0xc018b2bf  Kernel::MemoryManager::handle_page_fault(Kernel::PageFault const&) +429
[Taskbar(24:24)]: 0xc0121d8f  page_fault_handler +274
[Taskbar(24:24)]: 0xc011e2cb  page_fault_asm_entry +38
[Taskbar(24:24)]: MM: Purge saved the day! Purged 9 pages from PurgeableVMObject{0xc04d26b8}
[Taskbar(24:24)]: MM: Purge saved the day! Purged 16 pages from PurgeableVMObject{0xc04d4678}
[Taskbar(24:24)]: MM: Purge saved the day! Purged 721 pages from PurgeableVMObject{0xc04da438}
[Taskbar(24:24)]: 0x080ad47a  FILE::Buffer::realize(int) +64
[Taskbar(24:24)]: 0x080ad86a  FILE::read_into_buffer() +22
[Taskbar(24:24)]: 0x080ad9ca  FILE::gets(unsigned char*, unsigned long) +98
[Taskbar(24:24)]: 0x080adcd7  fgets +39
[Taskbar(24:24)]: 0x080ac76c  getpwent +160
[Taskbar(24:24)]: 0x080aca43  getpwuid +16
[Taskbar(24:24)]: 0x080a8d06  Core::StandardPaths::home_directory() +82
[Taskbar(24:24)]: 0x08049f09  AK::Function<void (unsigned int)>::CallableWrapper<TaskbarWindow::create_quick_launch_bar()::{lambda(auto:1)#1}>::call(unsigned int) const +47
[Taskbar(24:24)]: 0x0804e744  GUI::Button::click(unsigned int) +104
[Taskbar(24:24)]: 0x0804bfe9  GUI::AbstractButton::mouseup_event(GUI::MouseEvent&) +107
[Taskbar(24:24)]: 0x080a7208  Core::Object::dispatch_event(Core::Event&, Core::Object*) +74
[Taskbar(24:24)]: 0x08062ae2  GUI::Window::handle_mouse_event(GUI::MouseEvent&) +236
[Taskbar(24:24)]: 0x080a7208  Core::Object::dispatch_event(Core::Event&, Core::Object*) +74
[Taskbar(24:24)]: 0x080a0c0c  Core::EventLoop::pump(Core::EventLoop::WaitMode) +308
[Taskbar(24:24)]: 0x080a0d8b  Core::EventLoop::exec() +43
[Taskbar(24:24)]: 0x080484b7  main +207
[Taskbar(24:24)]: 0x08048e8e  _start +94
```

**Comment by tomuta** [comment] 2020-09-03 02:05
There are some major problems with how memory purging works. I have a branch where I'm trying to address a lot of these problems.

**Comment by kleinesfilmroellchen** [comment] 2022-12-12 20:39
Can't reproduce this way of provoking OOM, closing.

**Closed by kleinesfilmroellchen** 2022-12-12 20:39 UTC
Labels: bug
