### ISSUE TITLE
TextEditor: Ghosting of some fonts on selected texts

### ISSUE THREAD

**Issue by djwisdom** [SerenityOS/serenity#13717] opened 2022-04-17 05:14 UTC
The behavior is evident on some long width selected text and only if the window containing the selected text is the active one.

![image](https://user-images.githubusercontent.com/391659/163701440-3df3c5a3-af91-4426-bc97-6d888fb42aa2.png)

**Comment by kleinesfilmroellchen** [comment] 2022-04-23 11:09
I think this is a regression; the issue is not "ghosting" but that the text selection rectangles are not calculated correctly.

**Comment by Nukiloco** [comment] 2022-04-23 20:05
I think this is similar to #13253?

**Comment by kleinesfilmroellchen** [comment] 2022-04-24 11:13
I knew this had been reported before! Thanks, closing as duplicate.

**Closed by kleinesfilmroellchen** 2022-04-24 11:13 UTC
Labels: bug, duplicate, regression
