### ISSUE TITLE
PixelPaint: Saving project with invisible layer causes crash when reopening

### ISSUE THREAD

**Issue by IvanHansgaardHansen** [SerenityOS/serenity#5475] opened 2021-02-22 09:03 UTC
**To reproduce:**
1. Open PixelPaint.
2. Using the default project with the two squares, select the background layer and uncheck "Visible".
3. _Save As..._ (.pp).
4. _Open..._ the file you just saved.

The steps above cause the assertion in `../Userland/Applications/PixelPaint/Image.cpp:209` to fail.

I'm pretty sure this issue is related to the same bug which causes #5377 which I am also working on, trying to fix.

**Comment by TobyAsE** [comment] 2021-09-10 17:42
I'm closing this as I can't reproduce this anymore and it's already quite old.
If the issue still persists on your end feel free to re-open the issue!

**Closed by TobyAsE** 2021-09-10 17:42 UTC
Labels: bug
