### ISSUE TITLE
LibWeb: Text overlapping issue

### ISSUE THREAD

**Issue by InfRandomness** [SerenityOS/serenity#6697] opened 2021-04-27 22:52 UTC
Hi, it seems that there is an issue in the Help program, at certain spots in some pages, text happens to overlap : 

![image](https://user-images.githubusercontent.com/43730933/116322217-dfc6c200-a7bb-11eb-8945-2d486c8ce7c5.png)
(Mitigations(7))

![image](https://user-images.githubusercontent.com/43730933/116322252-f240fb80-a7bb-11eb-854c-41dfab9c49fa.png)
(kernel_modules(7))

**Comment by InfRandomness** [comment] 2021-04-28 21:06
Can I give a shot at fixing this myself ?

**Comment by IdanHo** [comment] 2021-04-28 21:08
> Can I give a shot at fixing this myself ?

Sure why not, first come first serve :)

**Comment by linusg** [comment] 2021-05-19 22:48
Duplicate of #7121 - yes, this one was opened first but has a worse title and less info :)

**Closed by linusg** 2021-05-19 22:48 UTC
Labels: bug
