### ISSUE TITLE
LibWeb: Opening local file in multi-process mode fails with "Permission denied"

### ISSUE THREAD

**Issue by MaxWipfli** [SerenityOS/serenity#6911] opened 2021-05-07 09:57 UTC
`br README.md` does not work, as the process responsible for opening the local file has not unveiled the correct path:
```
[#0 WebContent(32:32)]: Rejecting path '/home/anon/README.md' since it hasn't been unveiled with 'r' permission.
```

When using single-process mode with `br -s README.md`, everything works as expected.

**Comment by linusg** [comment] 2021-05-07 11:17
Duplicate of #5259.

**Closed by linusg** 2021-05-07 11:17 UTC
