### ISSUE TITLE
Kernel: Handle signals sent to process that never made a syscall

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#691] opened 2019-10-27 09:02 UTC
If a process receives a signal before it has made a single syscall, things will currently fall apart.

This is because `dispatch_signal()` expects to find a userspace register dump at the top of the kernel stack, but with no syscalls made yet, there's nothing there.

Also, I'm not sure if this code is correct in the case where a process is just running regular userspace code. Wouldn't we be using an outdated register dump when signalling such a process, since it's not currently executing in the kernel?

Reproducible by pressing `Ctrl+R` in `HackStudio` repeatedly until you get something like this:

```
NP(error) fault at invalid address V0xfffffff4
hs(17:0) Unrecoverable page fault, write to address 0xfffffff4
CRASH: Page Fault Process: hs(17)
exception code: 0002
  pc=0008:00023a16 ds=0010 es=0010 fs=0010 gs=0010
 stk=dc2a:c0addc2a
kstk=0010:c0ade000, base=c0ace000
eax=fffffff8 ebx=c0afffbe ecx=00000000 edx=fffffff4
ebp=c0addb56 esp=c0addc2a esi=003401e8 edi=00000000
```

cc @DrewStratford

**Comment by DrewStratford** [comment] 2019-10-27 14:50
To begin, for some reason I can't build the `make` port on my system, so my debugging experience may differ from yours (in HackStudio Ctrl-r just outputs `make: Command not found`).

That being said, I can still reproduce the bug by holding Ctrl-r. The thing is though, based on my logging, `dispatch_signal()` isn't being called at all. I'd be interested in seeing a longer log from your build, including a log of `dispatch_signal()` calls.


> This is because dispatch_signal() expects to find a userspace register dump at the top of the kernel stack, but with no syscalls made yet, there's nothing there.

Also, this shouldn't be the case. Since we only call `dispatch_signal()` in the scheduler. This means that the thread that we're calling it on either yielded via a PIT interrupt or a some yielding syscall, both of which would push a `RegisterDump` on to the kernel stack.

**Comment by awesomekling** [comment] 2019-10-27 14:59
> To begin, for some reason I can't build the `make` port on my system, so my debugging experience may differ from yours (in HackStudio Ctrl-r just outputs `make: Command not found`).

Oh that sucks. Any idea why? I just tested here and it builds nicely on my (Ubuntu 19.04) system.

> > This is because dispatch_signal() expects to find a userspace register dump at the top of the kernel stack, but with no syscalls made yet, there's nothing there.
> 
> Also, this shouldn't be the case. Since we only call `dispatch_signal()` in the scheduler. This means that the thread that we're calling it on either yielded via a PIT interrupt or a some yielding syscall, both of which would push a `RegisterDump` on to the kernel stack.

Hmm, oh, unless the process is new and has never executed yet! :)

**Comment by stievie** [comment] 2019-10-27 15:24
> > To begin, for some reason I can't build the `make` port on my system, so my debugging experience may differ from yours (in HackStudio Ctrl-r just outputs `make: Command not found`).
> 
> Oh that sucks. Any idea why? I just tested here and it builds nicely on my (Ubuntu 19.04) system.

Same here, it says:
```
i686-pc-serenity-gcc -DLOCALEDIR=\"/usr/local/share/locale\" -DLIBDIR=\"/usr/local/lib\" -DINCLUDEDIR=\"/usr/local/include\" -DHAVE_CONFIG_H -I.  -I./glob   -I/usr/include/guile/2.0 -pthread  -g -O2 -MT ar.o -MD -MP -MF .deps/ar.Tpo -c -o ar.o ar.c
i686-pc-serenity-gcc -DLOCALEDIR=\"/usr/local/share/locale\" -DLIBDIR=\"/usr/local/lib\" -DINCLUDEDIR=\"/usr/local/include\" -DHAVE_CONFIG_H -I.  -I./glob   -I/usr/include/guile/2.0 -pthread  -g -O2 -MT arscan.o -MD -MP -MF .deps/arscan.Tpo -c -o arscan.o arscan.c
i686-pc-serenity-gcc: error: unrecognized command line option '-pthread'
```

I'm on Manjaro
`Linux manjaro 5.3.6-1-MANJARO #1 SMP PREEMPT Sat Oct 12 09:30:05 UTC 2019 x86_64 GNU/Linux`

**Comment by DrewStratford** [comment] 2019-10-28 01:25
> Hmm, oh, unless the process is new and has never executed yet! :)

Oh okay, that definitely makes sense. I've been able to reproduce it by creating a fake `make` executable. My quick n' dirty fix for this is to introduce an `has_run` variable and only dispatch signals after this has been set, though this may be a bit too hacky. 
The long term solution is to move to a software threading scheme where we don't have to keep the `tss` and `RegisterDumps` in sync. This'll be a lot more work though.

Even then, I think the crash described in my first reply is an entirely different bug, so holding Ctrl-r still wont work properly.

**Closed** 2019-11-04 09:13 UTC
Labels: bug
