### ISSUE TITLE
Soundplayer causes kernel panic

### ISSUE THREAD

**Issue by devsh0** [SerenityOS/serenity#5725] opened 2021-03-11 05:41 UTC
Booting Serenity and trying to play a wave file > 1MB causes a kernel panic. Note that this only happens if you do it the first thing after booting. For example, opening the browser or file manager and then playing sound doesn't cause this issue.

Steps to reproduce:

1. Boot Serenity
2. In the terminal window type sp /path/to/wave_file_gt_1mb.wav

It is very important to not open any application and try playing the sound file from the terminal. More specifically, as long as you don't see "kmalloc: Adding memory to heap at V0xc1001000, bytes: 1048576" in the debug log, the issue can be realized. Once that message pops up, playing works fine even directly from terminal.

Relevant debug log:

```
WindowServer(16): Entering WindowServer main loop
utmpupdate(26): Updating utmp from UID=100 GID=100 EGID=5 PID=25
Terminal(23): Load config file from /home/anon/.config/Terminal.ini
[#0 SyncTask(2:2)]: Ext2FS: Flushed 4 blocks to disk
[SoundPlayer(27:27)]: KERNEL PANIC! :^(
[SoundPlayer(27:27)]: kmalloc: Out of memory (requested size: 28)
[SoundPlayer(27:27)]: at ../Kernel/Heap/kmalloc.cpp:247 in void* kmalloc(size_t)
[SoundPlayer(27:27)]: KERNEL PANIC! :^(
[SoundPlayer(27:27)]: kmalloc: Out of memory (requested size: 43)
[SoundPlayer(27:27)]: at ../Kernel/Heap/kmalloc.cpp:247 in void* kmalloc(size_t)
```

I suspect we are doing something that the comments here ask not to do:

https://github.com/SerenityOS/serenity/blob/de6c5128fd5d6250879b4cf5df67bcbff576da7a/Kernel/Heap/kmalloc.cpp#L64-L90

...but I'm not sure. I cannot afford kernel debugging because that will require building a lot of things over and over again and that's a big deal for my machine :)

From SoundPlayer debugging, the panic is raised executing one of the calls to WaveLoaderPlugin::get_more_samples(). At some point the following snippet in LibAudio->Buffer.cpp seems to cause the problem:

https://github.com/SerenityOS/serenity/blob/de6c5128fd5d6250879b4cf5df67bcbff576da7a/Userland/Libraries/LibAudio/Buffer.cpp#L58-L71

**Comment by bcoles** [comment] 2021-03-11 05:47
Affects a lot of programs. Dupe of #5724.

**Comment by devsh0** [comment] 2021-03-11 05:51
Can confirm. Following reproduction steps mentioned in #5724 has the same effect.

**Closed** 2021-03-11 10:10 UTC
Labels: bug, duplicate
