### ISSUE TITLE
LibC: implement socket shutdown function

### ISSUE THREAD

**Issue by MWGuy** [SerenityOS/serenity#1141] opened 2020-01-26 22:07 UTC
**https://linux.die.net/man/3/shutdown**

**Comment by MWGuy** [comment] 2020-01-26 22:11
Functions ``shutdown`` and ``getrusage`` (#1140) needs for linking openssl apps

**Comment by bugaevc** [comment] 2020-01-27 07:16
> https://linux.die.net/man/3/shutdown

You mean https://pubs.opengroup.org/onlinepubs/009695399/functions/shutdown.html 😉

**Comment by awesomekling** [comment] 2020-01-27 19:06
Dupe of #428

**Closed by awesomekling** 2020-01-27 19:06 UTC
