### ISSUE TITLE
Apps crash with ASSERTION FAILED: node == m_head

### ISSUE THREAD

**Issue by diversys** [SerenityOS/serenity#4806] opened 2021-01-04 22:43 UTC
Running on macOS with qemu (i.e. without KVM) I noticed that some apps crash on start or close with this:
```
Browser(27): FrameLoader::load: file:///res/html/misc/welcome.html
Browser(27): Added new tab 0x015207e8, loading file:///res/html/misc/welcome.html
WindowServer(15): Decoding a ShareableBitmap with shbuf_id=86, size=[16x16]
Browser(27): I believe this content has MIME type 'text/html', , encoding 'utf-8'
USERSPACE(27) ASSERTION FAILED: node == m_head
.././AK/InlineLinkedList.h:266
```

**Comment by linusg** [comment] 2021-01-04 22:47
Likely duplicate of #4528. Make sure you rebuild the toolchain properly.

**Closed by linusg** 2021-01-04 22:47 UTC

**Comment by diversys** [comment] 2021-01-04 23:35
```
cd serenity
rm -rf Build Toolchain/{Build,Local}
cd Toolchain
./BuildIt.sh
cd ../Build
cmake .. -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10 -G Ninja
git pull && ninja install && ninja image && ninja run
```

Still crashes with 
```
USERSPACE(26) ASSERTION FAILED: node == m_head
.././AK/InlineLinkedList.h:266
```
