### ISSUE TITLE
GCC port crashes when optimizations are enabled 

### ISSUE THREAD

**Issue by EXL** [SerenityOS/serenity#2580] opened 2020-06-18 12:40 UTC
Is it just for me or for everyone?

```
$ g++ --version
g++ (GCC) 10.1.0
```

Steps to reproduce:

1. Open *HackStudio* on the **little** project.
2. Open *Makefile*, remove `-g` flag from `CXXFLAGS` and add some optimization flag e.g. `-O2`, and save file.
3. Open *main.cpp*, add `#include <LibGfx/Font.h>` header, and save file.
4. Try to build project.

Result (virtual machine hangs):

![Screenshot from 2020-06-18 19-34-55](https://user-images.githubusercontent.com/232116/85020878-30808e00-b19b-11ea-8ac4-bf77ff0cd530.png)

QEMU log:

```
HackStudio(31): Unimplemented token character: +
[SyncTask(2:2)]: Ext2FS: Flushed 4 blocks to disk
[HackStudio(41:41)]: do_exec(/usr/local/bin/make)
FIXME(LibC): setlocale(0, )
[make(42:42)]: do_exec(/usr/local/bin/g++)
[g++(43:43)]: do_exec(/usr/local/libexec/gcc/i686-pc-serenity/10.1.0/cc1plus)
[cc1plus(43:43)]: NP(error) fault at invalid address V0x021b0000
[colonel(0:0)]: Unblock cc1plus(43:43) due to signal
[cc1plus(43:43)]: ASSERTION FAILED: offset == 0
/home/exl/Projects/SerenityOS/Kernel/FileSystem/InodeFile.cpp:67 in virtual Kernel::KResultOr<Kernel::Region*> Kernel::InodeFile::mmap(Kernel::Process&, Kernel::FileDescription&, VirtualAddress, size_t, size_t, int, bool)
[cc1plus(43:43)]: 0xc011d20b  _Z18__assertion_failedPKcS0_jS0_ +180
[cc1plus(43:43)]: 0xc01307de  _ZN6Kernel9InodeFile4mmapERNS_7ProcessERNS_15FileDescriptionE14VirtualAddressmmib +128
[cc1plus(43:43)]: 0xc012e52d  _ZN6Kernel15FileDescription4mmapERNS_7ProcessE14VirtualAddressmmib +121
[cc1plus(43:43)]: 0xc0159fc8  _ZN6Kernel7Process8sys$mmapEPKNS_7Syscall14SC_mmap_paramsE +1442
[cc1plus(43:43)]: 0xc016a6a4  syscall_handler +1158
[cc1plus(43:43)]: 0xc016a1bf  syscall_asm_entry +29
[cc1plus(43:43)]: 0x091bcb2b  mmap +36
[cc1plus(43:43)]: 0x08ffef3f  backtrace_get_view +95
[cc1plus(43:43)]: 0x08ffd878  elf_add.constprop.0 +632
[cc1plus(43:43)]: 0x08ffee2a  backtrace_initialize +58
[cc1plus(43:43)]: 0x08ffb684  fileline_initialize +212
[cc1plus(43:43)]: 0x08ffb7a9  backtrace_pcinfo +41
[cc1plus(43:43)]: 0x08ffb0a1  unwind +129
[cc1plus(43:43)]: 0x091b9e7e  _Unwind_Backtrace +110
[cc1plus(43:43)]: 0x08ffb123  backtrace_full +115
[cc1plus(43:43)]: 0x08fbb507  _Z30diagnostic_action_after_outputP18diagnostic_context12diagnostic_t +311
[cc1plus(43:43)]: 0x08fbaaad  _Z28diagnostic_report_diagnosticP18diagnostic_contextP15diagnostic_info +445
[cc1plus(43:43)]: 0x08fbb1ae  _ZL15diagnostic_implP13rich_locationPK19diagnostic_metadataiPKcPPc12diagnostic_t +110
[cc1plus(43:43)]: 0x08fbb3b5  _Z14internal_errorPKcz +69
[cc1plus(43:43)]: 0x086de0bd  _ZL12crash_signali +77
[cc1plus(43:43)]: 0xc080100e  ??
```

**Comment by awesomekling** [comment] 2020-06-20 12:36
There are two issues here:

* The GCC port ICE'ing when run with optimizations
* The Kernel panicking due to missing support for non-zero offset to file-backed mmap(). I've opened #2597 for this

**Comment by ccapitalK** [comment] 2020-12-03 10:47
I can't reproduce this, the gcc port doesn't ICE when I try to do this on head of master. Can you still reproduce this @EXL? If not, we can probably close this.

**Closed** 2020-12-04 17:00 UTC
