### ISSUE TITLE
FileManager: Double clicking on a markdown file (/home/anon/README.md) opens browser, causes pledge violation. 

### ISSUE THREAD

**Issue by bgianfo** [SerenityOS/serenity#6983] opened 2021-05-09 09:28 UTC
Repro steps:
- Open FileManger
- Double Click on README.md 
- Browser opens, then shows permission denied
- Look in serial console, see WebContent got killed because of pledge.

Log:
```
Browser(63:63): Added new tab 0x04e10608, loading file:///home/anon/README.md
WebContent(66:66): FrameLoader::load: file:///home/anon/README.md
[#0 WebContent(66:66)]: Rejecting path '/home/anon/README.md' since it hasn't been unveiled with 'r' permission.
[#0 WebContent(66:66)]: 0xc02bc7bb  Kernel::VFS::validate_path_against_process_veil(AK::StringView, int) +0x309
[#0 WebContent(66:66)]: 0xc02c0694  Kernel::VFS::resolve_path(AK::StringView, Kernel::Custody&, AK::RefPtr<Kernel::Custody, AK::RefPtrTraits<Kernel::Custody> >*, int, int) +0x200
[#0 WebContent(66:66)]: 0xc02c13a2  Kernel::VFS::open(AK::StringView, int, unsigned short, Kernel::Custody&, AK::Optional<Kernel::UidAndGid>) +0x18a
[#0 WebContent(66:66)]: 0xc042c5c1  Kernel::Process::sys$open(AK::Userspace<Kernel::Syscall::SC_open_params const*>) +0x17d3
[#0 WebContent(66:66)]: 0xc03a8a90  syscall_handler +0x1e7d
[#0 WebContent(66:66)]: 0xc03a6bdb  syscall_asm_entry +0x31
WebContent(66:66): ResourceLoader::load: Error: Permission denied
```

**Comment by bcoles** [comment] 2021-05-09 10:21
Interestingly, double clicking `README.md` in Terminal opens the file in `TextEditor`, rather than `Browser`.

> causes pledge violation

`unveil` not `pledge`. 

It seems Browser is expected to be able to open files in `/home/`:

```
$ grep -rn unveil Userland/Applications/Browser/
Userland/Applications/Browser/main.cpp:88:    if (unveil("/home", "rwc") < 0) {
Userland/Applications/Browser/main.cpp:89:        perror("unveil");
Userland/Applications/Browser/main.cpp:93:    if (unveil("/res", "r") < 0) {
Userland/Applications/Browser/main.cpp:94:        perror("unveil");
Userland/Applications/Browser/main.cpp:98:    if (unveil("/etc/passwd", "r") < 0) {
Userland/Applications/Browser/main.cpp:99:        perror("unveil");
Userland/Applications/Browser/main.cpp:103:    if (unveil("/tmp/portal/image", "rw") < 0) {
Userland/Applications/Browser/main.cpp:104:        perror("unveil");
Userland/Applications/Browser/main.cpp:108:    if (unveil("/tmp/portal/webcontent", "rw") < 0) {
Userland/Applications/Browser/main.cpp:109:        perror("unveil");
Userland/Applications/Browser/main.cpp:113:    unveil(nullptr, nullptr);
```

Where as `WebContent` is not:

```
$ grep -rn unveil Userland/Services/WebContent
Userland/Services/WebContent/main.cpp:19:    if (unveil("/res", "r") < 0) {
Userland/Services/WebContent/main.cpp:20:        perror("unveil");
Userland/Services/WebContent/main.cpp:23:    if (unveil("/tmp/portal/request", "rw") < 0) {
Userland/Services/WebContent/main.cpp:24:        perror("unveil");
Userland/Services/WebContent/main.cpp:27:    if (unveil("/tmp/portal/image", "rw") < 0) {
Userland/Services/WebContent/main.cpp:28:        perror("unveil");
Userland/Services/WebContent/main.cpp:31:    if (unveil("/tmp/portal/websocket", "rw") < 0) {
Userland/Services/WebContent/main.cpp:32:        perror("unveil");
Userland/Services/WebContent/main.cpp:35:    if (unveil(nullptr, nullptr) < 0) {
Userland/Services/WebContent/main.cpp:36:        perror("unveil");
```

**Comment by MaxWipfli** [comment] 2021-05-09 12:57
This is basically a duplicate of #5259, although this part probably deserves it's own issue:

> Interestingly, double clicking README.md in Terminal opens the file in TextEditor, rather than Browser.

**Comment by linusg** [comment] 2021-05-09 14:18
Closing as duplicate of #5259.

**Closed by linusg** 2021-05-09 14:18 UTC
Labels: bug

**Comment by bgianfo** [comment] 2021-05-09 22:10
> Interestingly, double clicking `README.md` in Terminal opens the file in `TextEditor`, rather than `Browser`.
> 
> > causes pledge violation
> 
> `unveil` not `pledge`.
> 
> It seems Browser is expected to be able to open files in `/home/`:
> 
> ```
> $ grep -rn unveil Userland/Applications/Browser/
> Userland/Applications/Browser/main.cpp:88:    if (unveil("/home", "rwc") < 0) {
> Userland/Applications/Browser/main.cpp:89:        perror("unveil");
> Userland/Applications/Browser/main.cpp:93:    if (unveil("/res", "r") < 0) {
> Userland/Applications/Browser/main.cpp:94:        perror("unveil");
> Userland/Applications/Browser/main.cpp:98:    if (unveil("/etc/passwd", "r") < 0) {
> Userland/Applications/Browser/main.cpp:99:        perror("unveil");
> Userland/Applications/Browser/main.cpp:103:    if (unveil("/tmp/portal/image", "rw") < 0) {
> Userland/Applications/Browser/main.cpp:104:        perror("unveil");
> Userland/Applications/Browser/main.cpp:108:    if (unveil("/tmp/portal/webcontent", "rw") < 0) {
> Userland/Applications/Browser/main.cpp:109:        perror("unveil");
> Userland/Applications/Browser/main.cpp:113:    unveil(nullptr, nullptr);
> ```
> 
> Where as `WebContent` is not:
> 
> ```
> $ grep -rn unveil Userland/Services/WebContent
> Userland/Services/WebContent/main.cpp:19:    if (unveil("/res", "r") < 0) {
> Userland/Services/WebContent/main.cpp:20:        perror("unveil");
> Userland/Services/WebContent/main.cpp:23:    if (unveil("/tmp/portal/request", "rw") < 0) {
> Userland/Services/WebContent/main.cpp:24:        perror("unveil");
> Userland/Services/WebContent/main.cpp:27:    if (unveil("/tmp/portal/image", "rw") < 0) {
> Userland/Services/WebContent/main.cpp:28:        perror("unveil");
> Userland/Services/WebContent/main.cpp:31:    if (unveil("/tmp/portal/websocket", "rw") < 0) {
> Userland/Services/WebContent/main.cpp:32:        perror("unveil");
> Userland/Services/WebContent/main.cpp:35:    if (unveil(nullptr, nullptr) < 0) {
> Userland/Services/WebContent/main.cpp:36:        perror("unveil");
> ```

**Comment by bgianfo** [comment] 2021-05-09 22:12
> > causes pledge violation
> 
> `unveil` not `pledge`.
> 
Sure, sleepy brain.

Go look at who pledged and unveiled a substantial portion of the tree... 😁

**Comment by bgianfo** [comment] 2021-05-09 22:13
@linusg not sure why you closed this? Markdown files shouldn't be opened in the browser?

**Comment by linusg** [comment] 2021-05-09 22:38
Maybe they should, maybe they shouldn't - either way, we got #6988 to track that issue :)
