### ISSUE TITLE
FileManager: opening Properties dialog locks parent window

### ISSUE THREAD

**Issue by diversys** [SerenityOS/serenity#4648] opened 2020-12-30 08:46 UTC

**Comment by linusg** [comment] 2020-12-30 18:46
FWIW the same happens in GNOME's file manager (the only one I can test right now), so arguably that's a feature, not a bug.

**Comment by diversys** [comment] 2020-12-30 20:17
TBH, I can't imagine how it could be a feature :) Imagine that you need to open several Properties dialogs to compare file/folder sizes.

**Comment by awesomekling** [comment] 2021-01-01 23:37
Fixed in 7e6c27a6884829846391d905380346c3b485db9b, where I apparently bungled the bug#

**Closed by awesomekling** 2021-01-01 23:37 UTC
Labels: enhancement
