### ISSUE TITLE
df: doesn't show correct used disk space

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#4229] opened 2020-11-29 02:24 UTC
df doesn't show the correct used disk space

![Screenshot at 2020-11-29 02-22-16](https://user-images.githubusercontent.com/1429783/100530425-f3103a00-31e9-11eb-924f-9de8e73aa28f.png)

**Comment by danboid** [comment] 2020-11-29 02:28
It's more obviously borked when you run `df -h`

![Screenshot at 2020-11-29 02-27-26](https://user-images.githubusercontent.com/1429783/100530477-89446000-31ea-11eb-90f6-fd00510d82be.png)

**Comment by bcoles** [comment] 2020-11-29 02:59
It's a block count. See #735

**Comment by danboid** [comment] 2020-11-29 11:43
Somethings not quite right here though with my df output.

For `/` it says the disk is 1 GB and 1 GB has been used whilst in the next column it says there is 83 MB free. The used column would really need to be shown in MB for it to be useful so I think some tweaking is required here.

**Comment by bcoles** [comment] 2020-11-29 11:54
> 
> 
> Somethings not quite right here though with my df output.
> 
> For `/` it says the disk is 1 GB and 1 GB has been used whilst in the next column it says there is 83 MB free. The used column would really need to be shown in MB for it to be useful so I don't have to calculate the used space myself. I think some tweaking is required here.

So the issue is that it's rounded? Fair enough.

The rounding behavior is pretty similar to behavior of `df -h` on Linux when a disk is almost full. Not uncommon to show 0% available when there is space available.

```
# df 
Filesystem     1K-blocks     Used Available Use% Mounted on
udev              980332        0    980332   0% /dev
tmpfs             203744     1024    202720   1% /run
/dev/sda1       38958432 36951320         0 100% /
tmpfs            1018704    84288    934416   9% /dev/shm
tmpfs               5120        0      5120   0% /run/lock
tmpfs               4096        0      4096   0% /sys/fs/cgroup
tmpfs             203740       84    203656   1% /run/user/0
# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            958M     0  958M   0% /dev
tmpfs           199M  1.0M  198M   1% /run
/dev/sda1        38G   36G     0 100% /
tmpfs           995M   83M  913M   9% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           4.0M     0  4.0M   0% /sys/fs/cgroup
tmpfs           199M   84K  199M   1% /run/user/0
```

**Comment by kleinesfilmroellchen** [comment] 2022-01-14 21:54
Closing this as it looks invalid.

**Closed by kleinesfilmroellchen** 2022-01-14 21:54 UTC
Labels: invalid
