### ISSUE TITLE
HelpApplication: Searching the letter "d" crashes the process with a segfault

### ISSUE THREAD

**Issue by u9g** [SerenityOS/serenity#12827] opened 2022-03-01 04:25 UTC

**Comment by bgianfo** [comment] 2022-03-01 05:55
Please include a backtrace for all crash bugs.

**Comment by desttinghim** [comment] 2022-03-01 06:05
Not OP but I reproduced this crash, though typing any character in the search makes it occur:
```
NotPresent fault on Read at address 0x00000011

0x5f9a887d: [/bin/Help] ManualModel::data(GUI::ModelIndex const&, GUI::ModelRole) const [clone .localalias] +0xcd (ManualModel.cpp:156)
0x258d58f1: [libgui.so.serenity] GUI::ModelIndex::data(GUI::ModelRole) const +0x41 (ModelIndex.cpp:19)
0x25894688: [libgui.so.serenity] GUI::FilteringProxyModel::data(GUI::ModelIndex const&, GUI::ModelRole) const [clone .localalias] +0xc8 (FilteringProxyModel.cpp:46)
0x258d58f1: [libgui.so.serenity] GUI::ModelIndex::data(GUI::ModelRole) const +0x41 (ModelIndex.cpp:19)
0x258c5d32: [libgui.so.serenity] GUI::ListView::update_content_size() +0xf2 (ListView.cpp:45)
0x258c63bc: [libgui.so.serenity] non-virtual thunk to GUI::ListView::model_did_update(unsigned int) [clone .localalias] +0x2c (ListView.cpp:66)
0x258cf0a6: [libgui.so.serenity] GUI::Model::for_each_client(AK::Function<void (GUI::ModelClient&)>) +0x76 (Function.h:91)
0x258cf200: [libgui.so.serenity] GUI::Model::did_update(unsigned int) +0x60 (Model.cpp:54)
0x25895148: [libgui.so.serenity] GUI::FilteringProxyModel::set_filter_term(AK::StringView) +0x98 (FilteringProxyModel.cpp:52 => FilteringProxyModel.cpp:88)
0x5f99f70c: [/bin/Help] AK::Function<void ()>::CallableWrapper<serenity_main(Main::Arguments)::{lambda()#3}>::call() +0x6c (main.cpp:122 => Function.h:151)
0x2591ea17: [libgui.so.serenity] AK::Function<void ()>::CallableWrapper<GUI::TextEditor::did_change(GUI::AllowCallback)::{lambda()#1}>::call() +0x87 (Function.h:91)
0x347cf355: [libcore.so.serenity] AK::Function<void ()>::CallableWrapper<Core::Object::deferred_invoke(AK::Function<void ()>)::{lambda()#1}>::call() +0x245 (Function.h:91)
0x347b88a8: [libcore.so.serenity] Core::EventLoop::pump(Core::EventLoop::WaitMode) [clone .localalias] +0x2a8 (Function.h:91)
0x347b90da: [libcore.so.serenity] Core::EventLoop::exec() +0x11a (EventLoop.cpp:428)
0x25831f17: [libgui.so.serenity] GUI::Application::exec() +0x27 (Application.cpp:119)
0x5f9a33f2: [/bin/Help] serenity_main(Main::Arguments) +0x1e22 (main.cpp:391)
0x56c951e7: [libmain.so.serenity] main +0x77 (Main.cpp:23)
0x5f99dd05: [/bin/Help] _entry +0x65 (crt0.cpp:49)
```

**Comment by AtkinsSJ** [comment] 2022-03-01 09:08
Duplicate of #12300

**Closed by AtkinsSJ** 2022-03-01 09:08 UTC
