### ISSUE TITLE
Bugs around DebugSession

### ISSUE THREAD

**Issue by BenWiederhake** [SerenityOS/serenity#4327] opened 2020-12-05 15:50 UTC
When running `functrace` on a short-lived program, such as `echo whf`, the program immediately crashes, apparently because it doesn't stop the program soon enough:

```
functrace(24): perror(): open: No such file or directory
USERSPACE(24) ASSERTION FAILED: executable->is_valid()
../Libraries/LibDebug/DebugSession.cpp:44
[functrace(24:24)]: CPU[0] NP(error) fault at invalid address V0x02601c58
[functrace(24:24)]: 0xc0181eb1  Kernel::Process::sys$exit(int) +31
[functrace(24:24)]: 0xc017b917  syscall_handler +691
[functrace(24:24)]: 0xc017b65c  syscall_asm_entry +49
[functrace(24:24)]: 0x080480d5  d_type.cold +0
[functrace(24:24)]: 0x0805c5a9  __cxa_atexit +0
[functrace(24:24)]: 0x080516c4  Debug::DebugSession::initialize_executable_mapped_file(int) +90
[functrace(24:24)]: 0x080516f3  Debug::DebugSession::DebugSession(int) +31
[functrace(24:24)]: 0x080519cc  Debug::DebugSession::exec_and_attach(AK::String const&) +382
[functrace(24:24)]: 0x08048239  main +218
[functrace(24:24)]: 0x0804ef76  _start +94
[Shell(22:22)]: select was interrupted
Shell(22): Job entry "functrace echo whf" deleted in 54 ms
```

When running it on a GUI program like `Browser` or `SystemMonitor`, it seems to work for a moment, and then crashes the Kernel:

```
[Terminal(20:20)]: ASSERTION FAILED: !g_scheduler_lock.own_lock()
../Kernel/Syscall.cpp:198 in void Kernel::syscall_handler(Kernel::TrapFrame*)
[Terminal(20:20)]: CPU[0] NP(error) fault at invalid address V0x00c02ab8
[Terminal(20:20)]: 0xc011f355  __assertion_failed(char const*, char const*, unsigned int, char const*) +185
[Terminal(20:20)]: 0xc017b805  syscall_handler +417
[Terminal(20:20)]: 0xc017b65c  syscall_asm_entry +49
[Terminal(20:20)]: 0x080fc638  select +57
[Terminal(20:20)]: 0x080de648  Core::EventLoop::wait_for_event(Core::EventLoop::WaitMode) +528
[Terminal(20:20)]: 0x080de9c5  Core::EventLoop::pump(Core::EventLoop::WaitMode) +23
[Terminal(20:20)]: 0x080dedb1  Core::EventLoop::exec() +43
[Terminal(20:20)]: 0x080495d7  main +4591
[Terminal(20:20)]: 0x0804a4ae  _start +94
```

**Comment by ccapitalK** [comment] 2020-12-10 00:42
I think I have found the root cause. In DebugSession::exec_and_attach(), after forking the tracer process manually calls `ptrace(); waitpid()` a hard-coded 3 times to get the tracee to the end of the `execvp()` call that it needs to make. At some point, the amount of syscalls made on the tracee path must have changed (probably due to a change in some other library). This can be fixed by setting it to two `waitpid()` calls, but I think we need a better solution where we actually detect why each waitpid call was made.

**Closed** 2020-12-11 08:55 UTC
