### ISSUE TITLE
Taskbar: killing an applet turns tray background black

### ISSUE THREAD

**Issue by diversys** [SerenityOS/serenity#6117] opened 2021-04-04 17:03 UTC
`killall Network.applet`

![image](https://user-images.githubusercontent.com/1316513/113516040-cba6f080-9580-11eb-8cf1-74b48dc819c3.png)

**Comment by linusg** [comment] 2021-04-04 17:07
Duplicate of #6061

**Closed by linusg** 2021-04-04 17:07 UTC
