### ISSUE TITLE
SerenityOS: Issues & More

### ISSUE THREAD

**Issue by jsdevv** [SerenityOS/serenity#2698] opened 2020-07-04 18:21 UTC
Recently I wanted to get on Serenity but it was acting like services wouldn't start and loads of glitches were happening so I decided to rebuild Serenity / Re-clone it in another folder but the issues persisted. There are no errors in console, is there any changes that were made to serenity recently that would make it act like this?

After re-cloning and building, I had set a theme & display resolution, so after I had re-run Serenity, it said in the Terminal that it had applied the theme but it clearly hadn't.

**Comment by awesomekling** [comment] 2020-07-04 18:25
Most likely a dupe of #2693

**Closed by awesomekling** 2020-07-04 18:25 UTC
