### ISSUE TITLE
Help  - Horizontal scrollbar artifact remains displayed most of the time

### ISSUE THREAD

**Issue by djwisdom** [SerenityOS/serenity#13518] opened 2022-04-05 04:11 UTC
Playing with the splitter may or may not update the horizontal scrollbar.
Visual description follows:

The Help

![image](https://user-images.githubusercontent.com/391659/161675592-c4aeb08f-0101-4f1b-922f-39168907f718.png)

The artifact:

![image](https://user-images.githubusercontent.com/391659/161675693-ccfd5ce6-7e53-482d-a013-75e04c1a720e.png)

Moving splitter until the horizontal scroll bar disappears:

![image](https://user-images.githubusercontent.com/391659/161675922-384f92d1-27f8-457c-bad8-1e1f4cead0cc.png)

Click+Drag splitter to the right very slowly: artifact refreshes but most of the time still remains.
Click+Drag splitter to the left more often than not removes the artifact nicely.

Horizontal scrollbar should have been active here like it is on the left side but it is not working. The line `m_mem_add_button = *find_descendant_of_type_named` has still remaining strings to the right but horizontal scroll bar did not fire for this layout.

![image](https://user-images.githubusercontent.com/391659/161676686-030908dc-2374-425c-8c61-a38a6e45148f.png)

Slightly moving the splitter to the right showed an initial attempt at displaying the horizontal scrollbar:

![image](https://user-images.githubusercontent.com/391659/161676850-75f9017d-bb20-49a8-b44f-373c12b6e35d.png)

Slightly moving back splitter to the left immediately removes the initial attempt of horizontal scrollbar to make its presence known:

![image](https://user-images.githubusercontent.com/391659/161677014-4d85a6de-8e05-4367-8c60-723bf5162d8d.png)

Even in full-screen mode when the entry is nicely contained inside and there is obviously no need to display both horizontal and vertical scrollbar, their artifact remains:

![image](https://user-images.githubusercontent.com/391659/161677212-5a8e82c0-e872-4ea4-937c-643f86cac97e.png)

**Comment by linusg** [comment] 2022-04-05 12:00
Duplicate of #5437.

**Closed by linusg** 2022-04-05 12:00 UTC
