### ISSUE TITLE
[Layout / Presentation / Homepage] Please consider adding more varied screenshots of SerenityOS

### ISSUE THREAD

**Issue by rubyFeedback** [SerenityOS/serenity#3741] opened 2020-10-11 00:46 UTC
Hello SerenityOS contributors, especially Andreas.

SerenityOS made some headlights recently; I do not know know what the "end" goal is, per se,
but quite a lot of folks are curious about it. Probably for different reasons.

Anyway.

I believe one important component for SerenityOS is actually a teaching / education aspect. There
may be other, more important aspects (I don't know), perhaps a viable competitor to other OS,
but to me the teaching / education aspect seems to be the most important one. At the least for
my subjective view.

Recently I found a thread on reddit about the "happy second birthday of SerenityOS". Being
curious I checked it out. It was quite interesting to see what changed.

I looked at the most recent image in particular:

http://serenityos.org/happy/2nd/2020-10-10.png

Now - keep in mind that I do not have a lot of experience (with SerenityOS). My first impression
in regarsd to that screenshot was "looks like oldschool windows". This is not necessarily bad,
per se, but it just was my impression; the fox toolkit also looks a bit oldschool windows-sy.

But! I then had another thought. My second thought was ... what if people want to style that
layout? CAN it be styled? ARE there themes? Could we even use CSS to drive the theme
for it?

I have no idea if that is possible right now; or how much work it would be to add it.

But this brings me to why I write this issue request, actually - not so much about the code
side.

Would it be possible for you folks, to try to compile a bit more different images in general,
ESPECIALLY if we can customize it?

Right now I think these images all look like windows 2000 or before that, and while that it
is perfectly fine usability wise, I'd also like to know how much one could adjust that look
as such. These days I'd of course just use CSS to ad-hoc custom define anything, but
general (or generic) themes may be ok - just anything.

So this request can be summarized into the following TL; DR:

- Please consider adding more varied screenshots in the coming ~12 months or so,
sort of like a "todo for the third year birthday" aka, to als make SerenityOS "look good"
(in another style that is; whether the windows theme is good or not is quite subjective
but if people have a range of options to compare, then perhaps some styles and
looks may look better for them, and I think screenshots would be really nice in that
case).

Thank you for reading - please feel free to disregard or close this issue at any moment in
time should this be out of scope for the project or otherwise not implementable.

**Comment by awesomekling** [comment] 2020-10-11 13:33
Hello there! The 90s look & feel is a primary feature of the system. In fact, it's the *very first thing* mentioned in the About section of the project ReadMe:

> SerenityOS is a love letter to '90s user interfaces

The screenshots I posted in the "happy 2nd birthday" post yesterday were random development snapshots, not an attempt to showcase the system's theming capabilities. Of course, anyone is free to make any screenshots they like of the system. The system colors are fully themeable, and some layout metrics can be changed as well. :)

Closing this since it's not a bug report.

**Closed by awesomekling** 2020-10-11 13:33 UTC
