### ISSUE TITLE
Piano: Crashes on launch

### ISSUE THREAD

**Issue by JonArcherII** [SerenityOS/serenity#1586] opened 2020-04-02 16:30 UTC
```
Piano(20): Started a thread, tid = 21
[Piano(20:21)]: BUG! Unexpected NP fault at V0xc08ba000
[Piano(20:21)]: Unrecoverable page fault, write to address V0xc08ba000
[Piano(20:21)]: CRASH: Page Fault. Ring 3.
```

**Comment by willmcpherson2** [comment] 2020-04-03 06:28
I believe this is already filed at #1436

**Comment by awesomekling** [comment] 2020-04-03 07:55
Indeed, dupe of #1436

**Closed by awesomekling** 2020-04-03 07:55 UTC
