### ISSUE TITLE
Kernel: Array OOB and type mismatch in syscall_handler

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#5257] opened 2021-02-07 20:34 UTC
I have _no_ idea how this happened. I just had the system sat in the background while trying to load YouTube, came back to it and this was getting spammed endlessly in the console:
```
[#0 ProtocolServer(31:31)]: KUBSAN: out of bounds access into array of 'unsigned char [256]' (8-bit), index type 'int' (32-bit)
[#0 ProtocolServer(31:31)]: KUBSAN: at ../Kernel/Syscall.cpp, line 161, column: 91
[#0 ProtocolServer(31:31)]: 0xc01e1b50  print_location +0xcc
[#0 ProtocolServer(31:31)]: 0xc019f3d3  syscall_handler +0x3c1
[#0 ProtocolServer(31:31)]: 0xc019f00a  syscall_asm_entry +0x31
[#0 ProtocolServer(31:31)]: KUBSAN: type mismatch, 'u8' (1-bit)
[#0 ProtocolServer(31:31)]: KUBSAN: at ../Kernel/Syscall.cpp, line 161, column: 91
[#0 ProtocolServer(31:31)]: 0xc01e1b50  print_location +0xcc
[#0 ProtocolServer(31:31)]: 0xc019f3fb  syscall_handler +0x3e9
[#0 ProtocolServer(31:31)]: 0xc019f00a  syscall_asm_entry +0x31
[#0 ProtocolServer(31:31)]: KUBSAN: out of bounds access into array of 'unsigned char [256]' (8-bit), index type 'int' (32-bit)
[#0 ProtocolServer(31:31)]: KUBSAN: at ../Kernel/Syscall.cpp, line 161, column: 91
[#0 ProtocolServer(31:31)]: 0xc01e1b50  print_location +0xcc
[#0 ProtocolServer(31:31)]: 0xc019f3d3  syscall_handler +0x3c1
[#0 ProtocolServer(31:31)]: 0xc019f00a  syscall_asm_entry +0x31
[#0 ProtocolServer(31:31)]: KUBSAN: type mismatch, 'u8' (1-bit)
[#0 ProtocolServer(31:31)]: KUBSAN: at ../Kernel/Syscall.cpp, line 161, column: 91
[#0 SymbolServer(38:38)]: 0xc01e1b50  print_location +0xcc
[#0 SymbolServer(38:38)]: 0xc019f3fb  syscall_handler +0x3e9
[#0 SymbolServer(38:38)]: 0xc019f00a  syscall_asm_entry +0x31
[#0 SymbolServer(38:38)]: KUBSAN: out of bounds access into array of 'unsigned char [256]' (8-bit), index type 'int' (32-bit)
[#0 SymbolServer(38:38)]: KUBSAN: at ../Kernel/Syscall.cpp, line 161, column: 91
[#0 SymbolServer(38:38)]: 0xc01e1b50  print_location +0xcc
[#0 SymbolServer(38:38)]: 0xc019f3d3  syscall_handler +0x3c1
[#0 SymbolServer(38:38)]: 0xc019f00a  syscall_asm_entry +0x31
[#0 SymbolServer(38:38)]: KUBSAN: type mismatch, 'u8' (1-bit)
[#0 SymbolServer(38:38)]: KUBSAN: at ../Kernel/Syscall.cpp, line 161, column: 91
[#0 SymbolServer(38:38)]: 0xc01e1b50  print_location +0xcc
[#0 SymbolServer(38:38)]: 0xc019f3fb  syscall_handler +0x3e9
[#0 SymbolServer(38:38)]: 0xc019f00a  syscall_asm_entry +0x31
[#0 SymbolServer(38:38)]: KUBSAN: out of bounds access into array of 'unsigned char [256]' (8-bit), index type 'int' (32-bit)
[#0 SymbolServer(38:38)]: KUBSAN: at ../Kernel/Syscall.cpp, line 161, column: 91
[#0 SymbolServer(38:38)]: 0xc01e1b50  print_location +0xcc
[#0 SymbolServer(38:38)]: 0xc019f3d3  syscall_handler +0x3c1
[#0 SymbolServer(38:38)]: 0xc019f00a  syscall_asm_entry +0x31
[#0 SymbolServer(38:38)]: KUBSAN: type mismatch, 'u8' (1-bit)
[#0 SymbolServer(38:38)]: KUBSAN: at ../Kernel/Syscall.cpp, line 161, column: 91
[#0 SymbolServer(38:38)]: 0xc01e1b50  print_location +0xcc
[#0 SymbolServer(38:38)]: 0xc019f3fb  syscall_handler +0x3e9
```

**Comment by tomuta** [comment] 2021-02-09 16:59
This is a duplicate of #4912

**Closed** 2021-02-13 10:03 UTC
Labels: bug, duplicate
