### ISSUE TITLE
Kernel: bytes_written != 0 assertion failure in TTY::write

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#8090] opened 2021-06-16 12:24 UTC
To reproduce:
Run `br -s` in Terminal.
Go to the Serenity GitHub page.

Trace:
```
[Browser(30:30)]: ASSERTION FAILED: bytes_written != 0
[Browser(30:30)]: ../../Kernel/TTY/TTY.cpp:100 in Kernel::TTY::write(Kernel::FileDescription&, u64, const Kernel::UserOrKernelBuffer&, size_t)::<lambda(const u8*, size_t)>
[#0 Browser(30:30)]: 0xc05eef7f  abort +0x4b
[#0 Browser(30:30)]: 0xc05e2263  __assertion_failed(char const*, char const*, unsigned int, char const*) +0xd5
[#0 Browser(30:30)]: 0xc0508a51  Kernel::TTY::write(Kernel::FileDescription&, unsigned long long, Kernel::UserOrKernelBuffer const&, unsigned long)::{lambda(unsigned char const*, unsigned long)#1}::operator()(unsigned char const*, unsigned long) const +0x2f9
[#0 Browser(30:30)]: 0xc050910f  Kernel::KResultOr<unsigned long> Kernel::UserOrKernelBuffer::read_buffered<256ul, Kernel::TTY::write(Kernel::FileDescription&, unsigned long long, Kernel::UserOrKernelBuffer const&, unsigned long)::{lambda(unsigned char const*, unsigned long)#1}>(unsigned long, unsigned long, Kernel::TTY::write(Kernel::FileDescription&, unsigned long long, Kernel::UserOrKernelBuffer const&, unsigned long)::{lambda(unsigned char const*, unsigned long)#1}) const [clone .constprop.0] +0x4bb
[#0 Browser(30:30)]: 0xc050ce75  Kernel::TTY::write(Kernel::FileDescription&, unsigned long long, Kernel::UserOrKernelBuffer const&, unsigned long) +0x261
[#0 Browser(30:30)]: 0xc025d98d  Kernel::FileDescription::write(Kernel::UserOrKernelBuffer const&, unsigned long) +0x3e9
[#0 Browser(30:30)]: 0xc04fbbb9  Kernel::Process::do_write(Kernel::FileDescription&, Kernel::UserOrKernelBuffer const&, unsigned long) +0x503
[#0 Browser(30:30)]: 0xc04fd48b  Kernel::Process::sys$write(int, AK::Userspace<unsigned char const*>, long) +0x8a7
[#0 Browser(30:30)]: 0xc0403ca2  syscall_handler +0x1e85
[#0 Browser(30:30)]: 0xc0401e14  Kernel::syscall_asm_entry_dummy() +0x31
```

**Comment by gunnarbeutner** [comment] 2021-06-16 12:55
Minimal reproduction program:

```C
#include <unistd.h>

int main() {
    char buf[81920] = { 0 };
    write(1, buf, sizeof(buf));
}
```

**Comment by BertalanD** [comment] 2021-06-16 16:38
The internal 65535-byte `SlavePty` runs out of space when we try to write this many bytes (`br` outputs ~85kB in one go). 

I see that it was added as a bugfix for another issue. I don't see why not being able to write should be a fatal error.

cc @ccapitalK

**Comment by ccapitalK** [comment] 2021-06-16 23:00
Oh, it's not that it should be a fatal error for the write to be blocked, however if we are at the point where the device cant be written to, then `can_write()` should be returning false, which is why we VERIFY that bytes_written is not zero. That being said , I believe this opens us up to a TOCTTOU bug, so we should probably remove the VERIFY and instead return EAGAIN in that case (the new write syscall handler should be able to handle that).

**Comment by BertalanD** [comment] 2021-06-17 04:29
The VERIFY currently actually checks each 256-byte buffered write though, not the end result, so might fail even if we have written *some* data already.

The result of the whole write operation is checked in `Process::do_write`,  so we don't need the additional check in `TTY`.

**Comment by BertalanD** [comment] 2021-06-21 14:20
@ccapitalK 

I'm fixing this now. Do you think that there should be a mechanism for checking that `on_tty_write` will not return zero, or can we just go ahead anyways (since `buffer.read_buffered` will stop after partial reads)?

**Closed** 2021-06-21 14:57 UTC
Labels: bug

**Comment by ccapitalK** [comment] 2021-06-21 15:06
> @ccapitalK
> 
> I'm fixing this now. Do you think that there should be a mechanism for checking that `on_tty_write` will not return zero, or can we just go ahead anyways (since `buffer.read_buffered` will stop after partial reads)?

Yeah, the way you wrote your patch should be fine. IIRC the reason why I put that verify in there was because I had another patch out there around the same time for changing the write syscall path, and as part of that change I wanted to ensure we weren't returning zero from any of the internal write methods (IIRC my reasoning was that POSIX mandates that we don't ever return 0 from `sys$write()`, and in the write syscall handler we weren't handling 0 being returned by an internal write handler as a special case, so anywhere where we return 0 from write internally could potentially end up returning 0 to userspace, which violates the standard).
