### ISSUE TITLE
Kernel/Ext2FS: Crash when trying to delete any of preinstalled desktop shortcuts

### ISSUE THREAD

**Issue by luk1337** [SerenityOS/serenity#9167] opened 2021-08-01 23:09 UTC
Not exactly sure where this block_index comes from but for some reason, it's `1852400175` while the block count is only `285184`.

```
[SyncTask(3:3)]: ASSERTION FAILED: block_index <= super_block().s_blocks_count
[SyncTask(3:3)]: ../../Kernel/FileSystem/Ext2FileSystem.cpp:655 in void Kernel::Ext2FS::free_inode(Kernel::Ext2FSInode&)
[SyncTask(3:3)]: KERNEL PANIC! :^(
[SyncTask(3:3)]: Aborted
[SyncTask(3:3)]: at ../../Kernel/Arch/x86/common/CPU.cpp:29 in void abort()
[#0 SyncTask(3:3)]: Kernel + 0x003bc5d9  Kernel::__panic(char const*, unsigned int, char const*) +0xb1
[#0 SyncTask(3:3)]: Kernel + 0x006102c9  abort.localalias +0x1d2
[#0 SyncTask(3:3)]: Kernel + 0x006100f7  abort.localalias +0x0
[#0 SyncTask(3:3)]: Kernel + 0x00256a1c  Kernel::Ext2FS::free_inode(Kernel::Ext2FSInode&) [clone .localalias] +0x1e4
[#0 SyncTask(3:3)]: Kernel + 0x00257842  Kernel::Ext2FSInode::~Ext2FSInode() [clone .localalias] +0x19e
[#0 SyncTask(3:3)]: Kernel + 0x00257972  Kernel::Ext2FSInode::~Ext2FSInode() [clone .localalias] +0x1c
[#0 SyncTask(3:3)]: Kernel + 0x00237a59  AK::RefCounted<Kernel::Inode>::unref() const +0x115
[#0 SyncTask(3:3)]: Kernel + 0x00271c0c  AK::HashMap<AK::DistinctNumeric<unsigned long long, Kernel::__InodeIndex_tag, false, true, true, false, false, false>, AK::RefPtr<Kernel::Ext2FSInode, AK::RefPtrTraits<Kernel::Ext2FSInode> >, AK::Traits<AK::DistinctNumeric<unsigned long long, Kernel::__InodeIndex_tag, false, true, true, false, false, false> >, false>::Entry::~Entry() +0x21c
[#0 SyncTask(3:3)]: Kernel + 0x00272441  AK::HashTable<AK::HashMap<AK::DistinctNumeric<unsigned long long, Kernel::__InodeIndex_tag, false, true, true, false, false, false>, AK::RefPtr<Kernel::Ext2FSInode, AK::RefPtrTraits<Kernel::Ext2FSInode> >, AK::Traits<AK::DistinctNumeric<unsigned long long, Kernel::__InodeIndex_tag, false, true, true, false, false, false> >, false>::Entry, AK::HashMap<AK::DistinctNumeric<unsigned long long, Kernel::__InodeIndex_tag, false, true, true, false, false, false>, AK::RefPtr<Kernel::Ext2FSInode, AK::RefPtrTraits<Kernel::Ext2FSInode> >, AK::Traits<AK::DistinctNumeric<unsigned long long, Kernel::__InodeIndex_tag, false, true, true, false, false, false> >, false>::EntryTraits, false>::remove(AK::HashTableIterator<AK::HashTable<AK::HashMap<AK::DistinctNumeric<unsigned long long, Kernel::__InodeIndex_tag, false, true, true, false, false, false>, AK::RefPtr<Kernel::Ext2FSInode, AK::RefPtrTraits<Kernel::Ext2FSInode> >, AK::Traits<AK::DistinctNumeric<unsigned long long, Kernel::__InodeIndex_tag, false, true, true, false, false, false> >, false>::Entry, AK::HashMap<AK::DistinctNumeric<unsigned long long, Kernel::__InodeIndex_tag, false, true, true, false, false, false>, AK::RefPtr<Kernel::Ext2FSInode, AK::RefPtrTraits<Kernel::Ext2FSInode> >, AK::Traits<AK::DistinctNumeric<unsigned long long, Kernel::__InodeIndex_tag, false, true, true, false, false, false> >, false>::EntryTraits, false>, AK::HashMap<AK::DistinctNumeric<unsigned long long, Kernel::__InodeIndex_tag, false, true, true, false, false, false>, AK::RefPtr<Kernel::Ext2FSInode, AK::RefPtrTraits<Kernel::Ext2FSInode> >, AK::Traits<AK::DistinctNumeric<unsigned long long, Kernel::__InodeIndex_tag, false, true, true, false, false, false> >, false>::Entry, AK::HashTable<AK::HashMap<AK::DistinctNumeric<unsigned long long, Kernel::__InodeIndex_tag, false, true, true, false, false, false>, AK::RefPtr<Kernel::Ext2FSInode, AK::RefPtrTraits<Kernel::Ext2FSInode> >, AK::Traits<AK::DistinctNumeric<unsigned long long, Kernel::__InodeIndex_tag, false, true, true, false, false, false> >, false>::Entry, AK::HashMap<AK::DistinctNumeric<unsigned long long, Kernel::__InodeIndex_tag, false, true, true, false, false, false>, AK::RefPtr<Kernel::Ext2FSInode, AK::RefPtrTraits<Kernel::Ext2FSInode> >, AK::Traits<AK::DistinctNumeric<unsigned long long, Kernel::__InodeIndex_tag, false, true, true, false, false, false> >, false>::EntryTraits, false>::Bucket>) +0x1fb
[#0 SyncTask(3:3)]: Kernel + 0x0024e172  AK::HashMap<AK::DistinctNumeric<unsigned long long, Kernel::__InodeIndex_tag, false, true, true, false, false, false>, AK::RefPtr<Kernel::Ext2FSInode, AK::RefPtrTraits<Kernel::Ext2FSInode> >, AK::Traits<AK::DistinctNumeric<unsigned long long, Kernel::__InodeIndex_tag, false, true, true, false, false, false> >, false>::remove(AK::DistinctNumeric<unsigned long long, Kernel::__InodeIndex_tag, false, true, true, false, false, false> const&) [clone .isra.0] +0x106
[#0 SyncTask(3:3)]: Kernel + 0x0024e2ad  Kernel::Ext2FS::uncache_inode(AK::DistinctNumeric<unsigned long long, Kernel::__InodeIndex_tag, false, true, true, false, false, false>) [clone .localalias] +0x11d
[#0 SyncTask(3:3)]: Kernel + 0x0026a705  Kernel::Ext2FS::flush_writes() [clone .localalias] +0x100f
[#0 SyncTask(3:3)]: Kernel + 0x0028c8e9  Kernel::FileSystem::sync() +0x971
[#0 SyncTask(3:3)]: Kernel + 0x002eb583  Kernel::VirtualFileSystem::sync() +0x15
[#0 SyncTask(3:3)]: Kernel + 0x00545396  void Kernel::Process::kernel_process_trampoline<Kernel::SyncTask::spawn()::{lambda()#1}>(void*) +0x99
[#0 SyncTask(3:3)]: Kernel + 0x00616180  exit_kernel_thread +0x0
```

**Comment by awesomekling** [comment] 2021-08-06 22:05
Is your filesystem okay? Please include `e2fsck -f _disk_image` when filing Ext2FS bugs :)

**Comment by luk1337** [comment] 2021-08-06 22:11
Yeah, my filesystem is ok until I boot up SerenityOS, as e2fsck only starts complaining after I boot up SerenityOS and shut it down:
```
e2fsck 1.45.6 (20-Mar-2020)
Pass 1: Checking inodes, blocks, and sizes
Inode 7961, i_blocks is 8, should be 16.  Fix<y>? yes
Inode 7939, i_blocks is 8, should be 16.  Fix<y>? yes
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 4: Checking reference counts
Pass 5: Checking group summary information

_disk_image: ***** FILE SYSTEM WAS MODIFIED *****
_disk_image: 8873/71424 files (4.9% non-contiguous), 166112/285696 blocks
```

Not sure if related to the issue tho.

**Comment by bcoles** [comment] 2022-04-03 11:05
I can't reproduce this issue after a fresh boot, or reboot, or shutdown followed by fresh boot.

I'm guessing the disk image was corrupted... somehow. That's disconcerting, but likely unrelated to deleting desktop shortcuts.

**Comment by IdanHo** [comment] 2022-04-03 17:50
Closing until someone can reproduce this

**Closed by IdanHo** 2022-04-03 17:50 UTC
Labels: bug
