### ISSUE TITLE
PS2Mouse: Keypresses cause incorrect mouse position

### ISSUE THREAD

**Issue by willmcpherson2** [SerenityOS/serenity#956] opened 2019-12-29 14:50 UTC
Pressing a key while moving the mouse quickly results in an incorrect cursor position
This is logged:
```
PS2Mouse: Stream out of sync.
```
Having this fixed will be good for future Piano features.

**Comment by DrewStratford** [comment] 2020-01-01 01:47
I had a look in `PS2MouseDriver.cpp` and found that, despite succeding this check: https://github.com/SerenityOS/serenity/blob/8602fa5b49aa4e2b039764a14698f0baa3ad0532/Kernel/Devices/PS2MouseDevice.cpp#L50-L52
we're still occasionally reading errant keyboard data into the mouse driver. This seems pretty odd and I can't really work out why it would be happening. Maybe there's some sort of race condition between reading the status register and the data register?

**Comment by xTibor** [comment] 2020-01-03 13:27
This may even be some QEMU quirk. I built a VirtualBox image out of curiosity and the PS/2 stuff works rock solid there. No keyboard data passed to the mouse IRQ no matter how I torture it.

**Comment by willmcpherson2** [comment] 2020-01-03 13:30
Thanks for the info guys

**Comment by xTibor** [comment] 2020-01-03 13:47
We may be hitting this bug? Would worth a shot trying to reproduce this with qemu-master.
https://lists.gnu.org/archive/html/qemu-devel/2018-05/msg03286.html

**Comment by xTibor** [comment] 2020-01-04 12:49
Still debugging this and already found a bug in QEMU's PS/2 code. This line in particular:

https://github.com/qemu/qemu/blob/f0dcfddecee8b860e015bb07d67cfcbdfbfd51d9/hw/input/ps2.c#L639

This calculation breaks when the mouse type is set to the default `mouse_type == 0 /* PS2 */`. It checks if there's 1 byte space left on the PS/2 queue but proceeds to write 3 bytes to it. The last two bytes of the event then could get discarded in `ps2_queue_noirq` when the queue is full. This bug doesn't affects us because we're setting IntelliMouse mode `mouse_type == 3 /* IMPS/2 */`.

I have a feeling the out of sync bug will also be some brain damage like this.

**Comment by xTibor** [comment] 2020-01-04 17:08
Known QEMU bug: https://bugs.launchpad.net/qemu/+bug/1722884

**Comment by awesomekling** [comment] 2020-01-27 22:06
Okay, since it's a known QEMU bug, I don't think there's anything we can do here. Closing this.

**Closed by awesomekling** 2020-01-27 22:06 UTC
