### ISSUE TITLE
curl cause kernel panic lol

### ISSUE THREAD

**Issue by nonetrix** [SerenityOS/serenity#4915] opened 2021-01-12 04:11 UTC
I ran this and it crashed
    curl -s -L http://bit.ly/10hA8iC | bash
btw this is a rickroll just wanted to see if it even would work and if I could port it unfortunately it uses python 

    [curl(100:100)]: kmalloc(): Adding memory to heap at V0xc2946000, bytes: 1048576
    [curl(100:100)]: CPU[0] NP(error) fault at invalid address V0x00000008
    [curl(100:100)]: copy_from_user(0xc06521d8, 0x00000008, 4) failed at V0x00000008
    LookupServer(101): Using network config file at /etc/LookupServer.ini
    [curl(100:100)]: ASSERTION FAILED: level == SOL_SOCKET
    ./Kernel/Net/Socket.cpp:110 in virtual Kernel::KResult 
    Kernel::Socket::setsockopt(int, int, AK::Userspace<const void*>, socklen_t)
    [curl(100:100)]: 0xc01193d6  __assertion_failed(char const*, char const*, unsigned int, char const*) +0xe2
    [curl(100:100)]: 0xc0173e79  .L603 +0xbf
    [curl(100:100)]: 0xc016a2c7  Kernel::IPv4Socket::setsockopt(int, int, AK::Userspace<void const*>, unsigned int) +0x41
    [curl(100:100)]: 0xc01a062a Kernel::Process::sys$setsockopt(AK::Userspace<Kernel::Syscall::SC_setsockopt_params const*>) +0x152
    [curl(100:100)]: 0xc0188124  syscall_handler +0x6be
    [curl(100:100)]: 0xc0187a5e  syscall_asm_entry +0x31

**Comment by bcoles** [comment] 2021-01-12 06:50
This looks like a duplicate of #4159.

**Closed** 2021-01-12 06:52 UTC
Labels: duplicate
